### ISSUE TITLE
Always expecting data when performing a process call in api_client

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1001]
This line always expects data when performing a call like `post`. During the `process` the output is parsed and when its `None` a exception is raised.

https://github.com/openvstorage/framework/blob/master/ovs/extensions/api/client.py#L140

Calls like `set_domains` can return `None` when performed in a `post` call.

**Comment by khenderick** [comment]
Fixed by #1033, packaged in openvstorage-2.7.4-rev.4139.df50495

@grimpy, I've added a `delete` call, and I somehow remember you once needed one.

**Comment by JeffreyDevloo** [comment]
We did not encounter the issue anymore during our automated setups.
