### ISSUE TITLE
unable to create a backend with the same name after deletion

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1012]
constraint logic does not remove constraint on delete - pls fix

**Comment by khenderick** [comment]
Fixed by #1013, #1014 and openvstorage/framework-alba-plugin#234, packaged in openvstorage-2.7.4-rev.4110.61da5ac and openvstorage-backend-1.7.4-rev.738.c050b22

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest ovs
- Assigned roles
- Added backend 'mybackend'
- Removed backend 'mybackend'
- Added backend 'mybackend'

### Output

Backend created succesfully both times.

### Test result

Test passed.

### Package information
- openvstorage                          2.7.4-rev.4110.61da5ac-1                                 amd64        openvStorage
- openvstorage-backend                  1.7.4-rev.738.c050b22-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core             1.7.4-rev.738.c050b22-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps          1.7.4-rev.738.c050b22-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin            1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                     2.7.4-rev.4110.61da5ac-1                                 amd64        openvStorage core
- openvstorage-hc                       1.7.4-rev.738.c050b22-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                      1.6.4-rev.380.cfbfc0a-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                  2.7.4-rev.4110.61da5ac-1                                 amd64        openvStorage Web Applications
