### ISSUE TITLE
Flexible scrubber

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1020]
Currently the scrubber runs every day which might be too often in large scale deployments as it can be quite aggressive. This ticket is to add more flexibility around the scrubber.
- [x] Add a new API call to scrub a volume on demand (parameters: voldrv where to scrub) 
- [x] Add the new scrub call to the GUI on the vdisk detail page (icon http://fontawesome.io/icon/cogs/)
- [x]  Disable the daily Schedule scrub task. The task can be enabled by setting a flag in arakoon.

Out of scope: scrubbing upto a certain snapshot as https://github.com/openvstorage/volumedriver/issues/143 needs to be delivered first.

**Comment by wimpers** [comment]
@khenderick is this something you see doable fro Fargo?

**Comment by khenderick** [comment]
At least, the current implementation lasted 14 days

**Comment by khenderick** [comment]
@wimpers, I can start and see when it lands.

**Comment by khenderick** [comment]
On hold until linked volumedriver ticket is resolved.

**Comment by wimpers** [comment]
@saelbrec, maybe it would be a better idea to leave the scheduled task on by default? Just to be on the safe side.

**Comment by khenderick** [comment]
So, the requirements changed so the "up to a given snapshot" requirement is postponed. Let's start.

**Comment by khenderick** [comment]
Just for the record: an imo better idea would be to make the scrubber configurable via the GUI. E.g. allow users to define times when the scrubber can run. This also allows flexibility, but can make sure that volumes need to be scrubbed e.g. at least once a week.

**Comment by khenderick** [comment]
Fixed by #1027, packaged in openvstorage-backend-1.7.4-rev.760.c681183

**Comment by wimpers** [comment]
@khenderick  What should be documented? Which flag to set to disable/enable the daily task?

**Comment by khenderick** [comment]
@wimpers, right, forgot about that. Setting the `/ovs/framework/auto_scrub` key to `false` will disable the automatic scrubbing.

**Comment by kinvaris** [comment]
- Scrubbing validated in https://github.com/openvstorage/framework/issues/538: PASSED
- Scrub a single volume on a certain machine with SCRUB disks validated: PASSED

![](https://i.imagebanana.com/img/8neckua9/Selection_010.png)

![](https://i.imagebanana.com/img/fkv8gv0c/Selection_009.png)
