### ISSUE TITLE
Automatic API generation + documentation

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1021]
Make the framework API automatic and self-describing.

A suggestion for this might be [Swagger](http://swagger.io/) as https://github.com/swagger-api/swagger-ui/issues/807 is being fixed.

**Comment by khenderick** [comment]
Partial implementation:
- Documentation
- `swagger.json` is generated

Is not yet usable, since the correct oauth2 flow is not yet supported.

openvstorage/framework#1097 and openvstorage/framework-alba-plugin#255, packaged in openvstorage-2.7.4-rev.4223.88b2c61 and openvstorage-backend-1.7.4-rev.795.3f4f094

**Comment by khenderick** [comment]
QA (@JeffreyDevloo, @kinvaris), feel free to give give some extra love to API related tests, since various decorators have been changed so there might be some (unintended) impact.

**Comment by JeffreyDevloo** [comment]
Since all of our autotests depends on the API for 90%, I can conclude that the current changes have not yet impacted any of our tests.
In short: love given.

**Comment by khenderick** [comment]
On hold for upstream pull request

**Comment by wimpers** [comment]
Swagger issue is fixed

**Comment by khenderick** [comment]
Fixed by #1422, packaged in dev openvstorage-2.7.12-dev.1486480862.4f3d0f5

**Comment by khenderick** [comment]
@openvstorage/qa, you need Swagger >= v2.2.10 to use this.

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
Validation in:
https://github.com/openvstorage/integrationtests/issues/445

**Comment by JeffreyDevloo** [comment]
### Summary
Validated together with https://github.com/openvstorage/framework/issues/1134
### Test result
Test passed.
