### ISSUE TITLE
OVS update - SDM updated on 'Update Framework'

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1052]
## Problem description

The SDM package was updated when 'Update Framework' was started in the GUI.
Before the update, there was no indication that there was a new Storage Driver package.

Packages before updating:
- openvstorage                       2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager

Packages after updating Framework:
- openvstorage                       2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage
- openvstorage-sdm                   1.6.4-rev.390.89e2ad4-1                                  amd64        Open vStorage Backend ASD Manager

Screenshot before the starting the update:
![selection_003](https://cloud.githubusercontent.com/assets/17570109/19469672/94cb0cea-951c-11e6-9891-883e0ae55505.png)

**Comment by wimpers** [comment]
SDM is part of framework.
