### ISSUE TITLE
Avahi reports: Failed to add service, but setup is completed with success.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1068]
When trying to setup my second node, I got the problem that the cluster was not visible. When looking deeper into avahi. It seemed like the character limit was reached for the avahi service.

`Oct 20 13:21:14 ovs-node01-1604 avahi-daemon[26250]: Failed to add service 'ovs_cluster_jonas-test-20okt-1604_ovs-node01-1604`

The character limit for avahi is 65 characters.

This should be checked when trying to enter a new cluster name!

**Comment by wimpers** [comment]
Let's limit the names of the cluster and hostname.

**Comment by wimpers** [comment]
Was earlier reported also http://jira.cloudfounders.com/browse/OVS-4099

**Comment by kinvaris** [comment]
@wimpers, we should also need to cut down on `ovs_cluster` part because it takes up 20% of the string

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1303 --> openvstorage-2.7.9-rev.4476.91633b0

@QA:
Avahi clusternames are limited to 63 characters
Therefore the implementation is now as following:
```
'ovs_cl_<cluster_name>_<node_name>_<ip>'
```
For \<node_name\> we take the last 24 characters of the name in case its longer than 24 chars
Eg:
node_name = 'my_ovs_cluster_my_long_node_name' --> would become 'luster_my_long_node_name'

For \<ip\> a maximum of 15 chars is preserved (eg: 255.255.255.255)

The start part 'ovs_cl' is 6 chars, so substracting all this (along with the underscores) from the maximum of 63, we end with this:
```
63 - 6 - 15 - 24 - 3 (underscores) = 15
```
So the <cluster_name> can always have a minimum of 15 characters (and potentially longer if the node name is shorter)

Tested scenarios:
* 1st node: New code - 2nd node: New code (SUCCESS)
* 1st node: Old code - 2nd node: New code (SUCCESS)
* 1st node: New code - 2nd node: Old code (FAILURE) --> Can't let nodes with old code join a cluster set up using new code (joining manually instead does work for this)
