### ISSUE TITLE
Durandal activate triggers twice for all wizards

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1077]
The 'activate' code in our wizards, which is supposed to only happen once on launch of a wizard, gets always triggered twice. This causes a bunch of APIs to be executed twice upon opening a wizard and thus causing unnecessary load and delay

**Comment by JeffreyDevloo** [comment]
Could be because of https://github.com/BlueSpire/Durandal/pull/437.
Framework uses Durandal 2.0.0. The router is composing all items with the activator.create() call and every component has it's own activate function.

**Comment by khenderick** [comment]
Latest Durandal unfortunately introduces a whole bunch of issues (most likely because I squeezed quite some stuff out of 2.0.0 which might be changed (or implemented) in 2.1 and onwards)

**Comment by wimpers** [comment]
Will be solved as part of a larger ticket (Update durandal)
