### ISSUE TITLE
Expose force migrate call in API

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1079]
Follow up from https://github.com/openvstorage/volumedriver/issues/158 : expose force migrate call in API. Default should be false.

**Comment by wimpers** [comment]
Do we want to put this in our gui?

**Comment by khenderick** [comment]
Awaiting a decision on whether to expose it into the GUI. Current state: exposure over API ready in #1373

**Comment by wimpers** [comment]
Not for now.

**Comment by wimpers** [comment]
@khenderick I guess your are ready?

**Comment by khenderick** [comment]
Still need to wrap up, get it reviewed, ... But I know enough to continue.

**Comment by khenderick** [comment]
Packaged on dev: openvstorage-2.7.11-dev.1485330534.68f0d39

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation in:
https://github.com/openvstorage/integrationtests/issues/446
