### ISSUE TITLE
extend the amount of maintenance agent for global backends

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1083]
At this moment we are not able to deploy more than 3 maintenance agent for 1 global backend.
It would be great if we can overwrite this with following config (/ovs/alba/backends/{0}/maintenance/nr_of_agents)?
And give us the option to deploy multiple maintenance agents on 1 backend server (not only one per backend).

We (OPS) should have the option to deploy as many maintenance agents as we want and reduce this back to a minimum.

**Comment by wimpers** [comment]
@khenderick  any reason why we limited the amount of maintenance agents to be deployed on a global backend.

**Comment by khenderick** [comment]
Current implementation:
- Only nodes that have a claimed asd for that backend are considered to be "valid" nodes for deploying maintenance agents for that backend.
- There should be only one maintenance agent for a particular backend on a node
- The configuration key `/ovs/alba/backends/<guid>/maintenance/nr_of_agents` (defaults to 3) contains the amount of maintenance agents that should be deployed for a backend, given the right conditions (see above)
- In case no agents can be deployed (e.g. no asds claimed, or a global backend), an absolute minimum of agents is deployed on random nodes (so they might be suboptimal): 1 for a local backend, and 3 for a global backend.
- Every hour, the maintenance agents checkup will validate the current configuration and deploy a better configuration if required.

**Comment by khenderick** [comment]
New implementation:
- The configuration key `.../nr_of_agents` will also be used as the minimum for a global backend.
- However, it won't be able to deploy more maintenance agents than there are nodes.

**Comment by khenderick** [comment]
Fixed by openvstorage/framework-alba-plugin#259, packaged in openvstorage-backend-1.7.4-rev.801.33cbb60

**Comment by wimpers** [comment]
Closed by PM.
