### ISSUE TITLE
ovs monitor services do not display dead services on 16.04

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1084]
When checking `ovs monitor services` for dead, activating or inactive services we see that none of those services are present in the section `non-running ovs services`.

Maybe its best to grep for `systemctl -a | grep ovs- | grep "dead\|activating\|inactive"` instead of just `loaded inactive`

**Comment by khenderick** [comment]
Fixed by #1085, packaged in openvstorage-2.7.4-rev.4197.3e7b233
