### ISSUE TITLE
Scrubbing service stays present after scrubbing is done on 16.04

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1087]
Scrubbing service stays present after scrubbing is done:

```
● ovs-albaproxy_myvpool_stor-01_scrub.service                                                                                                                           not-found inactive dead      ovs-albaproxy_myvpool_stor-01_scru
b.service
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1094 --> openvstorage-2.7.4-rev.4206.ee90361
https://github.com/openvstorage/alba-asdmanager/pull/135 --> openvstorage-sdm-1.6.4-rev.396.650816d

**Comment by kvanhijf** [comment]
@QA: Can be tested by deploying 1 vDisk and running ScheduledTaskController.execute_scrub(). The scrub proxy will be deployed and should be properly removed once done, regardless of actual scrubbing is required for the vDisk
ovs monitor services should no longer show anything related to scrub proxy services, nor should 'systemctl -a' have any entries for this service

**Comment by kinvaris** [comment]
Failed: 

During one of our CI tests we observed this problem during remove_vpool:

```
Oct 27 16:19:23 ovs-node03-1604 celery[9330]: Traceback (most recent call last):
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1160, in remove_storagedriver
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:     ServiceManager.remove_service(albaproxy_service, client=client)
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:   File "/opt/OpenvStorage/ovs/extensions/services/systemd.py", line 139, in remove_service
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:     client.run('systemctl disable {0}.service')
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:   File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 59, in inner_function
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:     return outer_function(self, *args, **kwargs)
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:   File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 274, in run
Oct 27 16:19:23 ovs-node03-1604 celery[9330]:     raise CalledProcessError(exit_code, command, output)
Oct 27 16:19:23 ovs-node03-1604 celery[9330]: CalledProcessError: Command 'systemctl disable {0}.service' returned non-zero exit status 1
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1098 --> openvstorage-2.7.4-rev.4208.4e2f3a1
https://github.com/openvstorage/alba-asdmanager/pull/138 --> openvstorage-sdm-1.6.4-rev.402.30d13fc

2nd attempt was necessary because already disabled services gave errors during removal of service

**Comment by kinvaris** [comment]
validated in https://github.com/openvstorage/framework/issues/538
