### ISSUE TITLE
Delete vDisk from GUI

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1108]
Add the option to delete a vDisk to the GUI. We have a delete API available.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1111 --> openvstorage-2.7.4-rev.4251.b3a026a

**Comment by kvanhijf** [comment]
@QA: It should now be possible to delete a vDisk from within the vDisk detail page

Important:
GUI should not allow to delete a vDisk when it has clones
GUI should not allow to convert a vDisk into vTemplate when it has clones

API should not allow to delete a vDisk when it has clones
API should not allow to convert a vDisk into vTemplate when it has clones

Controllers should not allow to delete a vDisk when it has clones
Controllers should not allow to convert a vDisk into vTemplate when it has clones

**Comment by pploegaert** [comment]
GUI part validated OK
- add vdisk - appears on fs - OK
- create a clone - can no longer be removed - OK
- cannot be converted into vtemplate - OK
