### ISSUE TITLE
GUI - backends - asd nodes: display disksize of available disks

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1112]
In an environment with a mix of different disks, it would be nice to get a clue how big the disks are to decide how many asd's to put on them. 
At present you have to login to the nodes and check manually for this information.

**Comment by wimpers** [comment]
I'm a bit curious, why would you put more asds on a bigger disk? I assumed you only put more asds on a disk to improve the IOPS the disk can give (1 asd = 140k iops max).

**Comment by dejonghb** [comment]
If you have 800GB disks next to 100GB ones, there might also be a difference in the IOPS such a disk can do or maybe you'd want to create equal size ASDs? 
Also for excluding the smaller disks so that they can be used for other purposes (whatever these are) having the information visible could be a plus.

**Comment by wimpers** [comment]
Why would you want to create equal size ASDs? ALBA autobalances data between the disks so they are automagically filled equally to the same %.

Do note that adding the size of the disk to the popup of the disk is a good idea.

**Comment by dejonghb** [comment]
ALBA autobalances data between the disks so they are automagically filled equally to the same %. --> small disks will be used less so these IOPS are less used? Yes, once these disk are full they cannot be used any more either but untill then and for some benchmarking setups that don't fill up everything it might be a plus?

**Comment by wimpers** [comment]
@khenderick any idea how much work this would be?

**Comment by khenderick** [comment]
@wimpers, 1 day
