### ISSUE TITLE
Allow external redis cluster for LRU tracking

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1119]
This  ticket is an extension of  https://github.com/openvstorage/framework/issues/919  In that ticket  it was noted that the option to add an external redis cluster for LRU tracking would be wishful.

**Comment by wimpers** [comment]
To be checked if the redis client inside ALBA supports this. ( @domsj any idea)

**Comment by domsj** [comment]
As far as alba is concerned any redis you configure it with is 'external' (as in: not managed by alba).
So, yes, alba supports an 'external' redis cluster to use for the lru tracking.

**Comment by wimpers** [comment]
The user should be able to add a key in arakoon config which defines a redis endpoint. If nothing specified the default one the framework sets up is used.

**Comment by wimpers** [comment]
@khenderick @domsj  how easy would it be to make this updatable? Would ALBA have issues with an update to the redis endpoint? 

A new endpoint would of course mean that all data around fragment usage is gone.

**Comment by domsj** [comment]
Fyi there's an alba ticket for this: https://github.com/openvstorage/alba/issues/381
Might take half a day or a day or so to implement.

**Comment by domsj** [comment]
Hmm, this is about the redis cluster functionality too?
The ocaml redis client currently has no support for that, so implementing that will take some time too...

**Comment by khenderick** [comment]
@wimpers, just adding a value from configuration instead of "our own" is a very small change. Making it updatable will obviously be more work since we have to add some API (and GUI interface) to change the value.

**Comment by khenderick** [comment]
Implementation after discussions: A user can configure an external redis endpoint which can be used. The framework still decides the key (`alba_lru_<guid>`).

**Comment by khenderick** [comment]
Fixed by openvstorage/framework-alba-plugin#325
Dev package: openvstorage-backend_1.7.9-dev.1483628338.ea9af3f

**Comment by khenderick** [comment]
openvstorage-2.7.9.1

**Comment by khenderick** [comment]
openvstorage-backend-1.7.9.1
