### ISSUE TITLE
Remove swagger.json restriction

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1134]
As discussed with @khenderick , remove/lower swagger.json restrictions so it can be used from a webbrowser.

**Comment by khenderick** [comment]
Allow CORS

**Comment by khenderick** [comment]
Fixed by #1135, packaged in openvstorage-2.7.5-rev.4278.8ed7f19

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest cluster
- Configured latest cluster
- Fetched swagger via url

### Output

![selection_061](https://cloud.githubusercontent.com/assets/17570109/20395460/4f05abe6-ace3-11e6-85d2-23e60f1a5e51.png)

### Test result

Test passed.

### Packages
- openvstorage                         2.7.5-fargo.2-1                 amd64        openvStorage
- openvstorage-backend                 1.7.5-fargo.1-1                 amd64        openvStorage Backend plugin
- openvstorage-backend-core            1.7.5-fargo.1-1                 amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.5-fargo.1-1                 amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.5-fargo.2-1                 amd64        openvStorage core
- openvstorage-webapps                 2.7.5-fargo.2-1                 amd64        openvStorage Web Applications

**Comment by JeffreyDevloo** [comment]
Reopening due to a lazy test of myself. I just tested the API on not the cross-origin aspect.
Will simulate domain switch with postman.

**Comment by pploegaert** [comment]
Validation in:
https://github.com/openvstorage/integrationtests/issues/445

**Comment by JeffreyDevloo** [comment]
### Steps
 - Identical to above
 - Tested cross origin with CURL
 - Tested with swagger ui
### Output
#### CURL
```
root@ovs-node01-1604:~# curl -H "Origin: http://example.com"   -H "Access-Control-Request-Method: GET"   -H "Access-Control-Request-Headers: X-Requested-With" --verbose   https://10.100.199.181/api/swagger.json -k
*   Trying 10.100.199.181...
* Connected to 10.100.199.181 (10.100.199.181) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* error fetching CN from cert:The requested data were not available.
* 	 common name:  (does not match '10.100.199.181')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #1
* 	 subject: C=AU,ST=Some-State,O=Internet Widgits Pty Ltd
* 	 start date: Thu, 16 Mar 2017 10:52:36 GMT
* 	 expire date: Wed, 07 Mar 2018 10:52:36 GMT
* 	 issuer: C=AU,ST=Some-State,O=Internet Widgits Pty Ltd
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api/swagger.json HTTP/1.1
> Host: 10.100.199.181
> User-Agent: curl/7.47.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 200 OK
< Date: Thu, 16 Mar 2017 13:59:10 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: gunicorn/19.4.5
< Access-Control-Allow-Origin: http://example.com  # <---- MEANS THAT IT HAS ACCEPTED MY ORIGIN
< Access-Control-Allow-Headers: x-requested-with, content-type, accept, origin, authorization
< Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
< 
{
    "basePath": "/api", 
    "consumes": [
        "application/json"
    ], 
    "definitions": {
        "ABMCluster": {

```
#### Swagger UI
![selection_121](https://cloud.githubusercontent.com/assets/17570109/24001029/43501444-0a5d-11e7-8744-6d6b11904e65.png)

### Test result
Test passed.
