### ISSUE TITLE
Change logging format for Ubuntu16.04

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1145]
The logs in journalctl on Ubuntu16.04 already contain a timestamp and hostname by default. Our logging format also adds a timestamp and hostname, so this information is duplicate

```
Nov 10 09:10:00 OVS-1-193-151 celery[15446]: 2016-11-10 09:10:00 17800 +0100 - OVS-1-193-151 - 12846/140663826982656 - lib/scheduled tasks - 5940 - INFO - Updating package information
Nov 10 09:38:49 OVS-1-193-151 celery[15446]: 2016-11-10 09:38:49 50200 +0100 - OVS-1-193-151 - 15806/140663826982656 - lib/scheduled tasks - 6140 - INFO - Updating package information
Nov 10 10:10:00 OVS-1-193-151 celery[15446]: 2016-11-10 10:10:00 15000 +0100 - OVS-1-193-151 - 18710/140663826982656 - lib/scheduled tasks - 6346 - INFO - Updating package information
```

**Comment by wimpers** [comment]
What if we don't use journalctl? Is this something Ubuntu specific? @dejonghb any advice?

**Comment by dejonghb** [comment]
journalctl is the systemd way of doing logging and is not ubuntu specific.

They claim 

> Storing the log data in a binary format also means that the data can be displayed in arbitrary output formats depending on what you need at the moment.
> One of the benefits of using a binary journal for logging is the ability to view log records in UTC or local time at will. By default, systemd will display results in local time.

so they also store the timestamp. Now if the logmessage already has some timestamp (in readable text) it will be included in the log and might or might not be displayed the same as how the binary timestamp gets displayed (_journalctl --utc_ will have UTC, not localtime)

Example:

```
Nov 14 07:46:39 ftcmp02 arakoon[20706]: 2016-11-14 08:46:39 605840 +0100 - ftcmp02 - 20706/0 - arakoon - 3328434 - info - 172.22.186.32:client_service...
```

**Comment by wimpers** [comment]
So we could use journalctl and not add a timestamp?

**Comment by dejonghb** [comment]
If you want to keep the option of direct logging to a file (or make sure on other/external installs a timestamp will be logged) you could retain the info (after all, it's already there so no new code needs to be written)

**Comment by wimpers** [comment]
@kvanhijf If you want to use journalctl for viewing logs we can always use `-o cat` to remove the duplicate timestamps
