### ISSUE TITLE
Download logs (and upload) won't work in 16.04

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1146]
Download logs (and upload) won't work in 16.04. We need something to extract the logfiles from journald.

**Comment by domsj** [comment]
Either that or you need a way to configure 16.04 services to each log to a separate file.
Which would be closer to what I prefer...
Found this http://www.cyberciti.biz/faq/howto-create-cron-log-file-to-log-crontab-logs-in-ubuntu-linux/ example with a bit of googling.
So it seems like you can configure rsyslog to send messages to different files for different services.

**Comment by wimpers** [comment]
@khenderick is this for the support portal? Or also for populating the Redis queue?

**Comment by khenderick** [comment]
Not related to either the support portal, nor the Redis stuff. It's just that the `ovs collect logs` (which is also used in the "download logs" functionality in the GUI) is not working on systemd

**Comment by khenderick** [comment]
Fixed by #1207, packaged in openvstorage-2.7.6-rev.4354.5a1ad95

**Comment by khenderick** [comment]
As under Ubuntu 16.04 systemd is our service manager, we assume that journald is in charge of the console output. I've implemented some code to extract the logs in the journald buffers to a file which is then included in the log archive.

It's up to the system administrator to make sure that journald is configured to sane values to journald can handle the log outputs of all services.

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup latest cluster
- Downloaded logs

### Output
Archive with:
![selection_103](https://cloud.githubusercontent.com/assets/17570109/21387200/df28c106-c776-11e6-806f-6bd9180684a1.png)

The journald log is added twice

### Test result
Test failed. Duplicate log.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1298 --> openvstorage-2.7.9-rev.4470.263f5e9

@QA: Duplicate file has been renamed from `ovs_journald.log` to `journald.log` and should thus only be present once

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup cluster
- Downloaded logs

### Output
![screenshot from 2017-01-23 15-13-14](https://cloud.githubusercontent.com/assets/17570109/22207233/9ba8b50e-e17e-11e6-8500-f6783ea0b626.png)


### Test result
Test passed.
