### ISSUE TITLE
14.04 ovs setup fails on retrieving status for service 'rabbitmq-server

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1156]
on env with new more secure shell functionality

http://jenkins.cloudfounders.com/job/OVS_DEPLOY/857/console

**Comment by khenderick** [comment]
Fixed by #1158, packaged in openvstorage-2.7.6-rev.4297.8c20ff2

**Comment by pploegaert** [comment]
PASSED:
http://jenkins.cloudfounders.com/job/OVS_DEPLOY/869/console
