### ISSUE TITLE
Sorting disks/asds on backend makes them move every local_stack fetch

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1189]
### Problem description
See gif
![ezgif com-ee9656ad15](https://cloud.githubusercontent.com/assets/17570109/20523848/6e104a82-b0b7-11e6-8fe6-a7880a0378e1.gif)

**Comment by khenderick** [comment]
![shopped](https://cloud.githubusercontent.com/assets/1453214/20524157/5fc54368-b0b9-11e6-99b2-a7d311fc4d68.jpg)

**Comment by kinvaris** [comment]
![whatthehell](http://www.relatably.com/m/img/what-the-hell-memes/57117449.jpg)

**Comment by khenderick** [comment]
![quickly](https://cloud.githubusercontent.com/assets/1453214/20524396/af7aa352-b0ba-11e6-84de-e9ed874a5db8.jpg)

**Comment by khenderick** [comment]
Looks like some sorting is a bit off, shouldn't be too hard to fix.

**Comment by JeffreyDevloo** [comment]
https://imgflip.com/i/1em6sc

**Comment by khenderick** [comment]
Fixed by openvstorage/framework-alba-plugin#283, packaged in openvstorage-backend-1.7.6-rev.824.b6ad731
