### ISSUE TITLE
Block vdisk creation on storagerouter with failed DB disk

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1190]
### Problem description
Adding a vdisk to a storagerouter with a failed DB disk is still possible. You can select this storagerouter in the wizard but the creation will fail because the volumedriver will error.
Since we know why the storagerouter failed, it should no longer be visible in the wizard.

My steps:
- Setup cluster
- Added roles to disks
- Added backend
- Added vpools
- Extended vpools to all nodes
- Remove the roles disk on node 1
- Add a vdisk on storagerouter 1

#### Disks on node 1
![selection_070](https://cloud.githubusercontent.com/assets/17570109/20527976/a90af296-b0ca-11e6-80ae-a784c41e6746.png)
#### Gui error
![selection_069](https://cloud.githubusercontent.com/assets/17570109/20528017/cdcff2a2-b0ca-11e6-8e41-b8cdfd94b9fa.png)

#### Log
```
Nov 22 15:42:14 ovs-node-2 celery[3176]: 2016-11-22 15:42:14 54400 +0100 - ovs-node-2 - 6946/139684504037120 - lib/vdisk - 1863 - ERROR - Creating new vDisk myvdisk01 fai
led: failed to send XMLRPC request volumeCreate
Nov 22 15:42:14 ovs-node-2 celery[3176]: 2016-11-22 15:42:14 55200 +0100 - ovs-node-2 - 3176/139684504037120 - celery/celery.worker.job - 1868 - ERROR - Task ovs.vdisk.cr
eate_new[2d6ee048-9d21-434b-a3a5-568b6dac7ef3] raised unexpected: RuntimeError('failed to send XMLRPC request volumeCreate',)
Nov 22 15:42:14 ovs-node-2 celery[3176]: Traceback (most recent call last):
Nov 22 15:42:14 ovs-node-2 celery[3176]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Nov 22 15:42:14 ovs-node-2 celery[3176]:     R = retval = fun(*args, **kwargs)
Nov 22 15:42:14 ovs-node-2 celery[3176]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Nov 22 15:42:14 ovs-node-2 celery[3176]:     return self.run(*args, **kwargs)
Nov 22 15:42:14 ovs-node-2 celery[3176]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 615, in create_new
Nov 22 15:42:14 ovs-node-2 celery[3176]:     node_id=str(storagedriver.storagedriver_id))
Nov 22 15:42:14 ovs-node-2 celery[3176]: RuntimeError: failed to send XMLRPC request volumeCreate
```

Also noticed that afterward I couldn't fetch any more info about my vpool for some time (+- 2 mins)

**Comment by khenderick** [comment]
Maybe we need to extend this towards more issues that can be foreseen, and not only disk issues.

**Comment by wimpers** [comment]
To be discussed further (we have the fuse/edge way of creating disks, maybe put the storage route in maintenance?

**Comment by wimpers** [comment]
This ticket  creates a link between https://github.com/openvstorage/framework/issues/1345 and https://github.com/openvstorage/framework/issues/1342. 

Basically if we encouter a broken DB disk or write buffer disk and there is no spare, we put the host in maintenance.

Which means:
* block creation of vdisks
* move vdisks away
* shutdown DTLs and MDS

I also believe we will need https://github.com/openvstorage/volumedriver/issues/236 if we want to correctly tackle this one.

**Comment by khenderick** [comment]
It will also need some kind of monitoring as the framework at this point does not monitor itself, so there's no process that on a regular interval checks certain statussen to take the required actions. Even if the code to put nodes in maintenance, we will still have to implement something that checks everything and takes the correct actions (e.g. check the disk state every minute and if issues arise put the node in maintenance)

**Comment by wimpers** [comment]
If we have https://github.com/openvstorage/volumedriver/issues/236 we can at least make sure no new volumes can be created if the voldrv is set into maintenance.

I'm not convinced (for now) that the framework should automatically set this mode when detecting a broken DB disk.

**Comment by khenderick** [comment]
> Basically if we encouter a broken DB disk or write buffer disk and there is no spare, we put the host in maintenance.

So that means "the user should make sure he sees that the disks are broken and should then press the right button".

**Comment by wimpers** [comment]
Correct, the OPS monitoring should tell him that a disk is broken. This means that OPS monitoring should be intelligent enough so a user isn't called out of bed for a dead ASD.

**Comment by wimpers** [comment]
Closing this one as needs to be tackled in https://github.com/openvstorage/volumedriver/issues/236 an integration of that ticket
