### ISSUE TITLE
increase vrouter_migrate_timeout_ms

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1194]
In continuation of #1191, we would also increase the value `vrouter_migrate_timeout_ms`

**Comment by khenderick** [comment]
Please make a suggestion about a better "default" value.

**Comment by wimpers** [comment]
@khenderick who are you looking at for providing that value? @redlicha ? @kinvaris ?

**Comment by khenderick** [comment]
@wimpers, whoever that can give me a reasonable value.

**Comment by kinvaris** [comment]
@khenderick 60 seconds has been tested on the OVH setup

**Comment by khenderick** [comment]
Fixed by #1205, packaged in openvstorage-2.7.6-rev.4350.8f70fdc

**Comment by khenderick** [comment]
A wild ```60000``` has appeared in the code.

**Comment by kinvaris** [comment]
PASSED:
Checked the volumedriver configs on the CI environments

```
root@ovs-node01-1604:~# ovs config get /ovs/vpools/016dfe8b-ae26-4499-afa9-b7953b1ac0ad/hosts/myvpool01EYHk1VhLIHiY0H9L/config | grep vrouter_migrate_timeout_ms
        "vrouter_migrate_timeout_ms": 60000, 
```
