### ISSUE TITLE
Disable auto-migration of volumes

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#1197]
Edge clients should not be able to trigger volume migration but instead are expected to follow the volume (exception: HA events - there the edge client triggers a failover to a node from a given set). To disable auto-migration, the `vrouter_volume_{read,write}_threshold`s need to be set to 0.

**Comment by wimpers** [comment]
Instead of disabling it at vrouter level why don't we push this  `volume_{read,write}_threshold` value to the vDisk level. By default we leave the value higher than 0 so auto-stealing is supported. In case you execute the move vdisk call on on the API we set the value to 0, move the vdisk to the new voldrv, verify that the edge client is has redirected its connection to the voldrv, update the threshold to the default (higher than 0) and call the move vdisk a success.

The reason why set the  `vrouter_volume_{read,write}_threshold` to zero is now that the move succeeds but the edge connection isn't updated so it moves back.

**Comment by wimpers** [comment]
@redlicha how long does it take for an Edge to be notified that it needs to switch the connection to another voldrv? This is timebased, right?

**Comment by redlicha** [comment]
It's not notified at all. Clients poll the volume location periodically. The poll interval can be configured (via an env var), default is 30 secs at the moment.

**Comment by wimpers** [comment]
To be researched for a clear solution as we want to allow auto-migration within the same domain.

**Comment by wimpers** [comment]
@kenneth , @redlicha After a second pass in the BAM. We still want auto-migration within a datacenter but not when it is across datacenters. How do you see this to be done? The use case is where the edge moves the connection to a new voldrv due to HA but the old voldrv is still online .

**Comment by wimpers** [comment]
Use case 1: The hypervisor fails (or vmotion)
In case the hypervisor fails, the hypervisor mgmt will restart the VM on another hypervisor. The VM will talk to the edge client on the new hypervisor which will talk to the old voldrv.

Use case 2: The storage router fails
In that case the edge client will detect the voldr is down and select another voldrv which can steal the volume.

Use case 3: The network fails
In that case the edge client will detect the voldr is down and select another voldrv which can't steal the volume. In this case a gracefull handover must be possible. 

The last use case isn't covered yet I believe

**Comment by khenderick** [comment]
@redlicha, can you elaborate what we need to configure to get use case 3 to work?

**Comment by redlicha** [comment]
In the current state this use case should work with auto-migration enabled: the edge client E connects after network failure to voldrv B, and B can redirect I/O to A, and after a certain threshold is exceeded the volume is auto-migrated to B. E will still periodically check for the volume location at the same time and attempt to connect to it, which will not interfere while the network between E and A is still down. If it does come back before the threshold is exceeded, E might however decide to reconnect to A.

So to support these cases auto-migration should be left enabled by default  (contrary to the initial suggestion):
* the use case "volume follows VM deterministically" cannot be supported at the moment (due to the above race)
* the use case "evacuate a voldrv" with the migrate API call needs a disable auto-migration to prevent volumes from being moved back.

**Comment by saelbrec** [comment]
The read/write migration threshold settings on a vrouter to be taken into account, are the ones from the vrouter owning the volume or the one receiving the I/O?

**Comment by redlicha** [comment]
The one receiving the I/O from a consumer and forwarding it to the owner. IOW:
* volume V lives on voldrv B
* edge client E connects to voldrv A
=> A determines that volume is not local and forwards requests to B. On each such fwd'ed request a counter is incremented and once that reaches the threshold A will request B to transfer the ownership of V to it.

**Comment by wimpers** [comment]
Currently nothing needs to happen and we will see how it turn out? Ok for you @saelbrec

**Comment by saelbrec** [comment]
Testing HA, we encounter too much cases in which the volume owner is not deterministic because with  the current settings 2 decision making mechanisms are racing.
Therefor it was decided to leave the following volumedriver configuration parameters to their default values.
```
'volume_router/vrouter_volume_read_threshold' ,
'volume_router/vrouter_volume_write_threshold' ,
'volume_router/vrouter_file_read_threshold' and
'volume_router/vrouter_file_write_threshold'
```
Which means that for an out of the box install the automigration feature is disabled.

**Comment by kvanhijf** [comment]
master --> openvstorage-2.7.13.2
develop --> openvstorage-2.8.0-dev.1489660745.93b705f

**Comment by JeffreyDevloo** [comment]
Specified behavior is covered by https://github.com/openvstorage/integrationtests/issues/493
Stealing should not occur but IO should be redirected instead.
