### ISSUE TITLE
Rollback the setup corrupts the cluster

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1204]
Due to a SSH problem during the installation, our setup crashed and started rolling back the installation. At the end the node was available in the storagerouter list so the cluster is in inconsistent state.

**Comment by wimpers** [comment]
Can you add  more info. What was exactly available? Any issues in the logs?

**Comment by kinvaris** [comment]
Well in this case the logs of why the setup crashed is not important here because it was on purpose. The focus of this scenario was to test the rollback. In general the rollback should just remove anything that it has put in place.

**Comment by wimpers** [comment]
@kinvaris can you please add the logs so @khenderick  has an idea where to start looking what was left.

**Comment by kinvaris** [comment]
On hold until further logs

**Comment by wimpers** [comment]
@kvanhijf Decided to disable by default the rollback and provide manual command to rollback.

**Comment by kvanhijf** [comment]
Ok, manual command to a (semi|non)-working rollback shall be implemented
Another great decision

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1272 --> openvstorage-2.7.8-rev.4441.ccf8e28

**Comment by kvanhijf** [comment]
@QA: Totally unsatisfied with own implementation because its a workaround, not a fix
So test at own risk
