### ISSUE TITLE
Integrate Edge HA locality knowledge

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1209]
Integrate Edge HA locality knowledge

https://github.com/openvstorage/volumedriver/issues/179

**Comment by wimpers** [comment]
@khenderick as discussed with @saelbrec after scrum

**Comment by wimpers** [comment]
Seems to be a duplicated of https://github.com/openvstorage/framework/issues/1209

**Comment by wimpers** [comment]
Re-open if I would be mistaken

**Comment by khenderick** [comment]
@wimpers, You did link to this ticket.

**Comment by wimpers** [comment]
Right, duplicate of https://github.com/openvstorage/framework/issues/1219 of course
