### ISSUE TITLE
Integrate locality for the volumedriver

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1219]
Integration of https://github.com/openvstorage/volumedriver/issues/179

Decision was to use Domains & Recovery Domaisn for the cost. Within the same domain the cost is 0, between domain and recovery domain the cost is 10. If the voldrv nodes don't share a domain/recoverydomain then the cost is the max cost 2**32-1.

Some remarks:
* In case of multiple recovery domains, the cost will be the same between all domain-recovery domains. (cost=10). 
Hence https://github.com/openvstorage/framework/issues/1211 will not be picked up.
* A cost tree will not be implemented for now. (https://github.com/openvstorage/framework/issues/1218)

**Comment by wimpers** [comment]
Note that we currently don't want the volumedriver to move vDisks outside the same datacenter (=domain). 

Basically we also need to set `network_interface/network_max_neighbour_distance`  so it is set to 10.

**Comment by khenderick** [comment]
After some more discussions:
* Node has primary domain:
  * Peer in primary domain: cost: ```0```
  * Peer in secondairy domain: cost ```10000```
  * Else: ```20000```
* Else:
  * cost ```0```

The ```network_max_neighbour_distance``` is set to ```9999```

This leaves us some space for future enhancements, and allows a distant StorageRouter to failover by settings it's StorageDriver configurations' ```network_max_neighbour_distance``` to e.g. ```19999```. By default however, failovers will only happen within the same domain.

**Comment by wimpers** [comment]
:thumbsup:

**Comment by khenderick** [comment]
Fixed by #1228, packaged in openvstorage-2.7.7-rev.4386.67fe8ae

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/435

**Comment by JeffreyDevloo** [comment]
Opening as it has not been validated yet.

**Comment by JeffreyDevloo** [comment]
### Validation
Test: https://github.com/openvstorage/integrationtests/pull/460
### Observations
- Failover occurs within the same domain
- Configs : 
```
In [5]: for vp in VPoolList.get_vpools():
    print vp.clusterregistry_client.get_node_configs()
   ...:     print vp.name
   ...:     
[ClusterNodeConfig{vrouter_id: "myvpool02CGpT9Ki7bogllAik", message_host: "10.100.199.172", message_port: 26200, xmlrpc_host: "10.100.199.172", xmlrpc_port: 26201, failovercache_host: "10.100.199.172", failovercache_port: 26202, network_server_uri: "tcp://10.100.199.172:26203", node_distance_map: {}}]
myvpool02
[ClusterNodeConfig{vrouter_id: "myvpool0110K6gDe7HKDO0gCD", message_host: "10.100.199.173", message_port: 26200, xmlrpc_host: "10.100.199.173", xmlrpc_port: 26201, failovercache_host: "10.100.199.173", failovercache_port: 26202, network_server_uri: "tcp://10.100.199.173:26203", node_distance_map: {"myvpool01CGpT9Ki7bogllAik": 10000, "myvpool01yBvMeGvrNjkCSJLv": 10000}}, ClusterNodeConfig{vrouter_id: "myvpool01CGpT9Ki7bogllAik", message_host: "10.100.199.172", message_port: 26206, xmlrpc_host: "10.100.199.172", xmlrpc_port: 26207, failovercache_host: "10.100.199.172", failovercache_port: 26208, network_server_uri: "tcp://10.100.199.172:26209", node_distance_map: {"myvpool0110K6gDe7HKDO0gCD": 10000, "myvpool01yBvMeGvrNjkCSJLv": 10000}}, ClusterNodeConfig{vrouter_id: "myvpool01yBvMeGvrNjkCSJLv", message_host: "10.100.199.171", message_port: 26200, xmlrpc_host: "10.100.199.171", xmlrpc_port: 26201, failovercache_host: "10.100.
```

### Test result
Matches with the description of the ticket.
Test passed.
```
