### ISSUE TITLE
lsblk reports unknown column: SERIAL on ubuntu 14.04.x

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1220]
This causes sync_with_reality to fail leaving no disks modelled

```
root@e187-1:~# lsblk --pairs --bytes --noheadings --exclude 1,2,11 --output=KNAME,SIZE,MODEL,STATE,MAJ:MIN,FSTYPE,TYPE,ROTA,MOUNTPOINT,LOG-SEC,SERIAL
lsblk: unknown column: SERIAL

```

http://testrail.openvstorage.com/index.php?/plans/view/35029

**Comment by khenderick** [comment]
Fixed by #1222 and #1221, packaged in openvstorage-2.7.6-fargo.2 and openvstorage-2.7.7-rev.4367.d7725ca
