### ISSUE TITLE
Support async update migrations & feature enabling

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1224]
Support async update migrations & feature enabling.

At this moment, the framework is upgraded completely or not at all.Even while the framework can be backwards compatible with (some of) its dependencies, it currently cannot detect that one of its dependencies is identical  across the cluster.

For example, dependency X might be version 1 at nodes A and B, and version 2 on nodes C and D. It currently can't handle this correctly and might start using new features based on the version on nodes C and D. Also migrations (e.g. X's configuration format might change) should only happen when X is updated to version 2 on all nodes.

The idea here is to have some kind of migration/feature task that runs at a regular interval, and that will check the dependencies across the cluster, and take actions based on the detected versions.

**Comment by wimpers** [comment]
Would https://github.com/openvstorage/framework/issues/1118 not this issue or how are these 2 tickets related?

**Comment by khenderick** [comment]
They are duplicated, sorry.
