### ISSUE TITLE
Service file regeneration

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1225]
Service files are (mostly) part of the framework, but we do not have a way to regenerate these when changes occur to these files

Recently we had some changes to open file descriptors for certain files, runversion changes for other service files, but only changing these templates won't make changes to the actual running service files
So we need a mechanism to be able to achieve this.

Most service files contain specific information about vpoolnames, additional dependencies, proxyguids, ...
During regeneration of these files it would come in handy to have this information available in the model rather than reload/retrieve this information manually every time again

Some sort of async update could achieve this, cause our current update mechanism does not provide this functionality (and it shouldn't either)

**Comment by wimpers** [comment]
@kvanhijf why is this feature urgent? Is this something we can't release without?

**Comment by wimpers** [comment]
@khenderick maybe we can use some type of  distributed config management for this or maybe something like fleet? :stuck_out_tongue_closed_eyes:

**Comment by wimpers** [comment]
Forgot the link to fleet https://github.com/coreos/fleet

**Comment by khenderick** [comment]
We can't use fleet for that as it's completely unrelated and apart from that we just decided to remove all fleet support since it didn't work at all anyway.

This is urgent because without this feature we have a hard time updating services files during future updates. All environments shipped without this feature won't have the data and won't be able to have their service files rewritten.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1254 --> openvstorage-2.7.8-rev.4421.03dd4d6
https://github.com/openvstorage/alba-asdmanager/pull/186 --> openvstorage-sdm-1.6.8-rev.486.e2ff325
https://github.com/openvstorage/framework-alba-plugin/pull/303 --> openvstorage-backend-1.7.8-rev.863.7835ed9

**Comment by JeffreyDevloo** [comment]
PR above is used for update purposes.

Actual regeneration in case service files got messed up:
https://github.com/openvstorage/framework/pull/1348
