### ISSUE TITLE
Integrate alba return codes

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1226]
Integrate alba return codes. It's nicer than just trying to parse the output to json and handle possible exceptions

**Comment by wimpers** [comment]
@domsj  @toolslive let's first make sure ALBA gives returns the right return code. If so , please leave a  comment.

**Comment by domsj** [comment]
It should be in the next release. Relevant PR https://github.com/openvstorage/alba/pull/466.

When passing --to-json nothing changes.
Exit code 0 => there should be valid json to parse.
Exit code 1 => something went wrong earlier than expected, probably bad input was given to the cli ... there is no parse-able json outputted.

**Comment by khenderick** [comment]
After some more discussions with @domsj and @toolslive, it turned out that when the json flag is passed, everything is like it was before. However, if not passed, the behavior might be different.

So we need to take this up _before_ the mentioned PR lands in unstable.

**Comment by domsj** [comment]
Fwiw we are introducing a breaking change when --to-json is not specified.
We can do this differently: add some extra flag --error-should-result-in-non-zero-exit-code (or sth along those lines ;-)), and only change the behavior when this flag is specified.
Although the consensus seems to be that we're fixing a bug, and not that we're breaking backwards compatibility...

**Comment by wimpers** [comment]
So Gilbert will not fly? This might have some impact on existing code as we need to check everywhere we use  the error codes I assume?

**Comment by khenderick** [comment]
@wimpers, We use this only at one place; our python wrapper.

**Comment by wimpers** [comment]
So it should be a quick one and you can squeeze it into Fargo RC2 you mean?
