### ISSUE TITLE
Investigate possible solution for disk consuming syslog file when using journalctl

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1227]
As observed on a partner environment:
http://tickets.openvstorage.com/browse/OVSSUP-118

The issue has already occured a few times we should decide on how to avoid/tackle this.

- reducing logging
- investigate components excessive logging when something goes wrong
- avoid logging to syslog
- ...

**Comment by dejonghb** [comment]
As temporary workaround: make sure the filesystem that holds /var/log is large enough to cope with the amount of logging that's being saved? Guess we can estimate this by looking at systems that were up, running and used for some time and adding a safety margin. Requiring a certain amount of diskspace available for a running system is not that unusual. 
Of course trying to minimize the required diskspace should remain something to work on. The proposal is only a workaround to keep things up & running now.

**Comment by wimpers** [comment]
@pploegaert  please provide input

**Comment by kinvaris** [comment]
yesterday @jeroenmaelbrancke & @saelbrec changed some settings on a customer environment to disable syslog forwarding on journald @wimpers

**Comment by wimpers** [comment]
@jeroenmaelbrancke  please document those changes here ...

**Comment by jeroenmaelbrancke** [comment]
We changed the ForwardToSyslog setting to no in the journald config file.
The SystemMaxUse is set to 500M this means journal will limit the size on the journal files.
Turn off the rate limit with RateLimitInterval and RateLimitBurst, set this to 0.

/etc/systemd/journald.conf
```
[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
RateLimitInterval=0
RateLimitBurst=0
SystemMaxUse=500M
#SystemKeepFree=
#SystemMaxFileSize=
#SystemMaxFiles=100
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

restart journald:
systemctl restart systemd-journald.service
