### ISSUE TITLE
Regular sync of volumes on StorageDriver and in model

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1233]
For some reasons (e.g. missed events due to RabbitMQ glitches) can cause the framework's model to be out of sync with reality. It shouldn't be too hard to write a small scripts that syncs both and runs every hour or so.

**Comment by wimpers** [comment]
Who knows what is correct? What if the check runs while you are changing things? Do we really want to do this manually?

**Comment by wimpers** [comment]
We don't want this to be automatic or scheduled. This should be a support tool for OPS which they can run on demand and confirm before taking actions.

**Comment by khenderick** [comment]
@wimpers, why would we not want to do this automatically? The reality is source of truth, so we just make sure that the model is in sync with reality. It does not make sense to not add a volume to the model if it exists in reality (in volumedriver), and it does not make sense to keep a volume in the model if it doesn't exist in reality. The "check" would run locked so we don't introduce sync issues (it's not much different than processing volumedriver events), and even if somehow we got some race condition, it will be fixed at next run. Syncing the model doesn't do anything, just makes sure that the framework knows what is reality.

I don't know, but I don't think Ops would like to be called in the middle of the night to press a button manually because some volume didn't end up in the model for whatever reason while the framework could do this automatically.

**Comment by JeffreyDevloo** [comment]
I agree with @khenderick with this one. Solely based around the fact that if a user must keep his model in sync himself, that the model would be horribly out of date and thus leading to much more issues than we can anticipate now.
The framework should correct and sync itself automatically.

**Comment by jtorreke** [comment]
I too must agree with both gentlemen. If the functionality would exist in a non-automated way, one of the first things I'd do is to add a cronjob to let this run hourly/daily. I agree that there must be a way to run this task manually, but there's no reason why not to automate this.

**Comment by wimpers** [comment]
This automatic sync is basically automatically fixing of things that went wrong. It doesn't fix the root cause and even hides that there were ever issues. BAM considers this is not the right approach.

**Comment by khenderick** [comment]
@wimpers, as the volumedriver considers sending events to the framework as optional and uses rabbitmq, it might be possible that the volumedriver was sending events before the rabbitmq cluster became active which won't be processed by the framework. Or it might be possible that by a manual intervention the rabbitmq cluster was rebuild losing any events currently on the queue. Or maybe volumes were created when the framework was down for upgrades.

**Comment by kvanhijf** [comment]
BAM could not be more wrong.
Automatically fixing this should NOT hide that there were issues. This should be logged properly and monitored, so in such an event that issues have occurred, we can manually verify why something went wrong
When clicking a button to sync or issuing such command via CLI, it might already have been too late and logs might have rotated out, while with cronjob or scheduled task every hour, we can be notified of such events much faster

**Comment by khenderick** [comment]
Closing this ticket off. It was decided by BAM (https://github.com/openvstorage/framework/issues/1233#issuecomment-264857080) that we don't want to automate this in any way. So unfortunately, the only thing left to do with this ticket is closing.

**Comment by wimpers** [comment]
@khenderick I believe there is some confusion. We do want that there a way to fix things if the model and the reality are out of sync. We just don't want it to happen autoamtically

**Comment by khenderick** [comment]
After some more discussions with @wimpers, it's clear what to do:

Create an API call that checks vDisk reality vs model and get them in sync. Just like voldrv arakoon sync, mds syncs, dtl syncs, nsm and abm syncs, ... except that for this sync we should *not* run it periodically or when the code suspects something is wrong. It's monitoring that should detect when things are going wrong, and then Ops (or some tool) needs to manually trigger this API.

**Comment by khenderick** [comment]
#1425 -> openvstorage-2.7.12-dev.1486550875.6525d9f

**Comment by khenderick** [comment]
#1435 -> openvstorage-2.7.12-dev.1486715931.a80d9a3

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/448
