### ISSUE TITLE
ovs cli command to refresh the config of a voldrv

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1235]
In order to easy refresh dynamic parameters add an  ovs cli command to refresh the config of a voldrv

**Comment by khenderick** [comment]
Is a button in the GUI good as well? That's a bit easier to implement.

**Comment by wimpers** [comment]
something like `ovs volumedriver storagerouter vpool reload`

**Comment by wimpers** [comment]
@khenderick , lets keep this one for the cli, https://github.com/openvstorage/framework/issues/1239 created for a nice button.

**Comment by kvanhijf** [comment]
Button has been created in the GUI along with an API to accomplish a voldrv config reload. Question is, do we still need a way via the CLI to accomplish the same thing when we have an API call for this?

**Comment by wimpers** [comment]
Yes as now you need to leave the cli to click that  button.  @khenderick considered the button in the GUI to be the fastest way to implement this functionality.

**Comment by kvanhijf** [comment]
@wimpers : Sarcastic question: Why don't we create CLI commands to add roles to partitions, create domains, create users, link backends. create vDisks, ... ? Wouldn't that also be beneficial for the customer?

**Comment by wimpers** [comment]
The idea to do that is already living for a long time but this should hopefully roll out of  the API (based upon the swagger implmentation https://github.com/openvstorage/framework/issues/1021).

**Comment by wimpers** [comment]
There is even a ticket for it https://github.com/openvstorage/home/issues/28

**Comment by wimpers** [comment]
To be picked up when doing https://github.com/openvstorage/home/issues/28 . Re-open if we would really need it before that.
