### ISSUE TITLE
ovs remove node - first ask confirmation before throwing other errors

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1237]
### Problem description
If you execute remove node and there are would-be errors for the removal of the node, those errors are displayed first before the confirmation has been asked.

```
root@ovs-node-3:~# ovs remove node 10.100.199.151
+++++++++++++++++++++
+++  Remove node  +++
+++++++++++++++++++++
WARNING: Some of these steps may take a very long time, please check the logs for more information


Creating SSH connections to remaining master nodes
  Node with IP 10.100.199.153  successfully connected to
  Node with IP 10.100.199.151  successfully connected to
  Node with IP 10.100.199.152  successfully connected to
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++  Still vDisks attached to Storage Router ovs-node-1  +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

### Solution
Always ask if the user is sure to remove the node and then proceed to prohibit the removal because of the errors.

### Packages
- openvstorage                         2.7.7-rev.4361.7c05190-1        amd64        openvStorage
- openvstorage-backend                 1.7.7-rev.828.5e3746c-1         amd64        openvStorage Backend plugin
- openvstorage-backend-core            1.7.7-rev.828.5e3746c-1         amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.7-rev.828.5e3746c-1         amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.7-rev.4361.7c05190-1        amd64        openvStorage core
- openvstorage-hc                      1.7.7-rev.828.5e3746c-1         amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                     1.6.7-rev.455.7913d38-1         amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                 2.7.7-rev.4361.7c05190-1        amd64        openvStorage Web Applications

**Comment by wimpers** [comment]
We prefer first to execute the checks so the user can make a sane decision.
