### ISSUE TITLE
Button in GUI to refresh the config of a voldrv

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1239]
In order to easy refresh dynamic parameters add a button in the gui to refresh the config of a voldrv

Add this button under vPool details - Management actions
* icon http://fontawesome.io/icon/refresh/

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1329 --> openvstorage-2.7.10-dev.1484121862.5191274

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
Validation in:
https://github.com/openvstorage/integrationtests/issues/440

**Comment by JeffreyDevloo** [comment]
Closing it down as we are currently tackling bigger features than buttons that fetch a config.
