### ISSUE TITLE
Implement a validate removal hook

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1255]
When removing a node, we first execute some removal stuff required by the framework (shrink vPools, ...)
Then some code gets executed to remove the plugins and other stuff by the use of so-called 'hooks'.
During the execution of these 'hooks', we sometimes raise errors because some prerequisites were not met.

Instead before actually starting the removal, we should implement another 'hook' which validates all the prerequisites for a proper removal. With this in place, we shouldn't end up with a halfly removed node.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1321 --> openvstorage-2.7.9-dev.1483979402.3f4c326

**Comment by khenderick** [comment]
openvstorage-2.7.9.2
