### ISSUE TITLE
Do we need a longer retry period for service restarts?

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1256]
What is the time window the current upstart/systemd configuration will retry to restart a service.
I am here referring to the alba proxy issue in https://github.com/openvstorage/alba/issues/384 but it probably counts for others as well

**Comment by khenderick** [comment]
For most systemd services, a failed services has to wait 100ms before systemd will start it again. Some services are configured to wait 3 seconds, others 5.

However, we use systemd's default rate limit, which should be 5 times per 10 seconds. Systemd should try to restart the service _forever_, but not more than 5 times every 10 seconds. So if e.g. a service immediately fails with a backoff of 100ms, it will be restarted 5 times, and then it will have to wait 9.5 seconds before it will be started again.

**Comment by khenderick** [comment]
@wimpers, as you closed the ticket, does it mean that all configurations are OK?

**Comment by wimpers** [comment]
@khenderick systemd restarts forever  x times per 10 sec it ws ok for @saelbrec

**Comment by khenderick** [comment]
Ah, in that case it's OK. 

I was under the impression that some services would be restarted too often, or that for some services it was desired that the restarting was stopped after a given amount of time (just as it was the case with Upstart) to prevent flooding the logs with the same error over and over again, and allowing for example the HC to correctly mark the service as not running or failed (as typically a service that keeps on crashing (for whatever reason) will be in "running" a lot of the time in between crashes and restarts).

**Comment by pploegaert** [comment]
@wimpers: we were going to validate this as part of QA too
