### ISSUE TITLE
Improve speed of non-cached queries

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1259]
**Note:** We've observed the following on a customer environment. 

**Description:** The customer was creating a lot of vdisks and the API calls to fetch the vdisks became slower. After investigation we can see that the constant creation/deletion is correlated with the slowness of the api calls.

**How?** Everytime a vdisk is created/deleted the cache is invalidated. Therefor the query is re-executed.

**Solution?** Improve the speed of non-cached queries.

```
In [121]: len(VDiskList.get_vdisks())
Out[121]: 2571

In [122]: len(VDiskList.get_vdisks())
Out[122]: 2573

In [123]: len(VDiskList.get_vdisks())
Out[123]: 2570

In [124]: len(VDiskList.get_vdisks())
Out[124]: 2571

In [125]: len(VDiskList.get_vdisks())
Out[125]: 2570

In [126]: len(VDiskList.get_vdisks())
Out[126]: 2570

In [127]: len(VDiskList.get_vdisks())
Out[127]: 2570

...

In [31]: for _ in xrange(10):
    start = time.time()
    ovs.get('/storagedrivers', params={'contents': 'vpool,storagerouter,vdisks_guids'})
    print "Listed storagedrivers in %s seconds" % (time.time() - start)
   ....:     
Listed storagedrivers in 20.4501001835 seconds
Listed storagedrivers in 18.2133619785 seconds
Listed storagedrivers in 24.5917301178 seconds
Listed storagedrivers in 21.1875739098 seconds
Listed storagedrivers in 4.04006791115 seconds
Listed storagedrivers in 0.0882480144501 seconds
Listed storagedrivers in 0.102998971939 seconds
Listed storagedrivers in 0.10452914238 seconds
Listed storagedrivers in 0.0951910018921 seconds
Listed storagedrivers in 0.309687852859 seconds
```

**Comment by khenderick** [comment]
In this particular case, to resolve it, we need to add support for field indexes to the DAL. Estimate 10d

**Comment by saelbrec** [comment]
@khenderick ,
Customer did not raise this issue in previous tests with double the amount of VM's. Anything changed in the caching or invalidation behavior?

**Comment by khenderick** [comment]
No. What happens here is basically that we ask the volumedriver for a list of ```volume_id```s which we then resolve to a list of ```vDisk``` guids. This query is - like all other queries - cached between 5 and 10 minutes, unless invalidated before. In this particular case, the customer was constantly creating and deleting vDisks causing the caches to be invalidated every time. Once they stopped the test that created/deleted vDisks all the time, you could see that the call was fast (< 0.5s) for 5 to 10 minutes.

Possibilities explaining why this was not observed before:
* If they would only execute the query when vDisks were not created/deleted, they probably just hit cache all the time.
* A few versions ago, the way of fetching the vDisk guids was completely different, which would give a much slower call, but more constant in time, so then the call would take e.g. 10 seconds all the time, instead of 20s on cache miss and < 0.5s on cache hit.

**Comment by wimpers** [comment]
@khenderick please clarify 'A few versions ago'? Which changes are you talking about?

**Comment by khenderick** [comment]
The change was made based on OVS-4431, merged in on April 11 under the topic of speeding up the GUI (or make it usable on large environments) as like previously stated before that change, every single call would take e.g. 10 seconds, whilst it now takes a hit every 5-10 minutes (or when a new disk is added/removed)

**Comment by wimpers** [comment]
Just adding an index might not bring the time down from 30 s to under 1s I guess. So the index solutions might not work.

**Comment by khenderick** [comment]
If you say so, sure.

**Comment by khenderick** [comment]
Some observations on this particular environment:
* There are 4 vPools with a total of 32 StorageDrivers
* Depending on the load, a full non-cached query for the ```vdisks_guids``` for a single StorageDriver might take between 0.3 and 0.9 seconds. This is the time it takes to load data for all 2323 vDisks and filter them one by one to find those related to that StorageDriver
* Getting the cached result takes between 0.001 and 0.01 seconds

So, when all the ```vdisks_guids``` for all StorageDrivers need to be loaded, it will take (assuming there's no caching) between 9.6 (32 * 0.3) and 28.8 (32 * 0.9) seconds, excluding stuff like sorting, serialization, caching, ... Once cached, it would take between 0.03 and 0.3 seconds, excluding stuff like sorting, serialization, caching, ... These calculations match with the reported and observed measurements.

Assume a field index would be in place, I would expect a bit more overhead compared to a fully cached version, but based on the above observations, I'd expect it would take somewhere between 0.01 and 0.05 seconds.

In our above example (```vdisks_guids``` for all StorageDrivers), this would reduce the time to load the data to something between 0.32 and 1.6 seconds (none-cached but indexed), and a similar time once the data is cached.

After some more thinking and verifying my theories with observed information on this particular information, I think that adding field indexes might indeed reduce the time from 25-ish seconds to less than one second. Obviously, it's still an estimate, but it's an educated estimate.

**Comment by khenderick** [comment]
Fixed by #1344 and openvstorage/framework-alba-plugin#334
Packaged on dev:
* openvstorage-backend-1.7.10-dev.1484667310.2c3bcc1
* openvstorage-2.7.10-dev.1484667229.0ab83af

**Comment by khenderick** [comment]
Another change by #1354. Packaged on dev in openvstorage-2.7.10-dev.1484730133.01fa7e8

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/443

**Comment by JeffreyDevloo** [comment]
### Information
Relying on the unit tests to validate the indexed queries.
```
root@ovs-node01-1604:~# ovs unittest /opt/OpenvStorage/ovs/dal/tests/test_basic



#####################################################################
# Processing test-module /opt/OpenvStorage/ovs/dal/tests/test_basic #
#####################################################################

test_1_to_1 (test_basic.Basic) ... ok
test_acquired_lock_during_caching (test_basic.Basic) ... ok
test_auto_inheritance (test_basic.Basic) ... ok
test_cache_and_save_racecondition (test_basic.Basic) ... ok
test_clearedcache (test_basic.Basic) ... ok
test_copy (test_basic.Basic) ... ok
test_datalist_add (test_basic.Basic) ... ok
test_datalistactions (test_basic.Basic) ... ok
test_datapersistent (test_basic.Basic) ... ok
test_datastoreloses (test_basic.Basic) ... ok
test_datastoreraises (test_basic.Basic) ... ok
test_datastorewins (test_basic.Basic) ... ok
test_delete_abandoning (test_basic.Basic) ... ok
test_delete_during_object_load (test_basic.Basic) ... ok
test_delete_retries (test_basic.Basic) ... ok
test_descriptors (test_basic.Basic) ... ok
test_discard (test_basic.Basic) ... ok
test_dynamic_unicode_return (test_basic.Basic) ... ok
test_emptyquery (test_basic.Basic) ... ok
test_enumerator (test_basic.Basic) ... ok
test_error_during_save (test_basic.Basic) ... ok
test_extended_filter (test_basic.Basic) ... ok
test_extended_property (test_basic.Basic) ... ok
test_guid_query (test_basic.Basic) ... ok
test_index_change_racecondition (test_basic.Basic) ... ok
test_indexed_guid (test_basic.Basic) ... ok
test_indexes (test_basic.Basic) ... ok
test_instance_checks (test_basic.Basic) ... ok
test_invalidate_dynamics (test_basic.Basic) ... ok
test_invalidobject (test_basic.Basic) ... ok
test_invalidonetoone (test_basic.Basic) ... ok
test_invalidpropertyassignment (test_basic.Basic) ... ok
test_invalidqueries (test_basic.Basic) ... ok
test_itemchange_during_list_build (test_basic.Basic) ... ok
test_listcache (test_basic.Basic) ... ok
test_mandatory_fields (test_basic.Basic) ... ok
test_newobject_delete (test_basic.Basic) ... ok
test_nofilterquery (test_basic.Basic) ... ok
test_object_cleanup (test_basic.Basic) ... ok
test_object_comparison_on_different_level (test_basic.Basic) ... ok
test_object_save_reverseindex_build (test_basic.Basic) ... ok
test_outdated_listobjects (test_basic.Basic) ... ok
test_ownrelations (test_basic.Basic) ... ok
test_persistency (test_basic.Basic) ... ok
test_pop_and_remove_from_datalist (test_basic.Basic) ... ok
test_preinit (test_basic.Basic) ... ok
test_queries (test_basic.Basic) ... ok
test_querydynamic (test_basic.Basic) ... ok
test_racecondition_datalist_multiget (test_basic.Basic) ... ok
test_racecondition_for_reverseindex (test_basic.Basic) ... ok
test_readonlyproperty (test_basic.Basic) ... ok
test_recursive (test_basic.Basic) ... ok
test_relation_inheritance (test_basic.Basic) ... ok
test_relation_set_build (test_basic.Basic) ... ok
test_relationcache (test_basic.Basic) ... ok
test_save_deleted (test_basic.Basic) ... ok
test_save_nonexisting_relation (test_basic.Basic) ... ok
test_serialization (test_basic.Basic) ... ok
test_shuffle_object_list (test_basic.Basic) ... ok
test_silentdatarefresh (test_basic.Basic) ... ok
test_typesafety (test_basic.Basic) ... ok
test_unique_constraint (test_basic.Basic) ... ok
test_updateproperty (test_basic.Basic) ... ok
test_versioning (test_basic.Basic) ... ok
test_volatiemutex (test_basic.Basic) ... ok
test_volatile_objects (test_basic.Basic) ... ok
test_volatileproperty (test_basic.Basic) ... ok

----------------------------------------------------------------------
Ran 67 tests in 0.488s

OK



############
# OVERVIEW #
############

  - TestModule: /opt/OpenvStorage/ovs/dal/tests/test_basic  (67 tests)
    - DURATION: < 1 second
    - SUCCESS: 67

```
