### ISSUE TITLE
Metadata API - limit amount of metadata gets loaded into memory

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1266]
Allow to set the amount of metadata for cache per volume

**Comment by wimpers** [comment]
What should be done if not enough space is available in mem? Should we block the creation of volumes if not enough RAM is available.

**Comment by wimpers** [comment]
Is there a way we can prevent the OOM killer to kill voldrv processes?

**Comment by khenderick** [comment]
What exactly is expected?

**Comment by wimpers** [comment]
See https://github.com/openvstorage/framework/issues/884

currently the amount of metadata pages for a volume are fixed:
```
metadata_page_capacity = 256
cluster_size = 4096  # by default, can be configured on vpool
num_pages = disk_size / (metadata_page_capcity * cluster_size)
```

We need an API so we can change the number of pages for a volume. The APi should expect a nr between 0 and  100 where 100 means all pages are in mem. if set to 10, 10% of the pages are in mem.

**Comment by wimpers** [comment]
For QA, please do test the scenario of the shrinking the size while a volume is in use.

**Comment by khenderick** [comment]
@redlicha, is there an issue with shrinking the size?

**Comment by wimpers** [comment]
This needs to be done on vdisk level. When you create a vdisk you set a percentage and if needed you can update later on (volume restart).

**Comment by khenderick** [comment]
After a lot of discussions and questions:
* The create disk API should get an optional parameter to set the amount of metadata that should be cached (float percent, e.g. 0.5 for 50%)
* A new API must be created to update this value for a given disk (also in percent, so 0.1 for 10%)
* If not specified, 100% is cached
* Increasing and decreasing is supported
* Regardless of requested percentage, the amount of pages cannot be larger as a 100% cached 2TiB volume.

**Comment by wimpers** [comment]
No need to keep the old absolute value. as that didn't work as expected.

**Comment by khenderick** [comment]
Fixed by #1313 
Dev package: openvstorage-2.7.9-dev.1483712466.c647c26

**Comment by khenderick** [comment]
openvstorage-2.7.9.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/437
