### ISSUE TITLE
Configure scrub proxies to cache-on-write if it has been configured for the vPool

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1281]
Configure scrub proxies to cache-on-write if it has been configured for the vPool

**Comment by domsj** [comment]
Also have a look at https://github.com/openvstorage/framework/issues/964
(This ticket could just be a comment there?)

**Comment by khenderick** [comment]
Not sure, I had the impression that this ticket was quite urgent, while #964 is marked as ```roadmap```.

**Comment by khenderick** [comment]
After some more discussion with @domsj, this ticket is a subset of #964 and moreover - since the scrubber has no partial reads - boils down to a duplicate of that ticket.

**Comment by khenderick** [comment]
Close as duplicate
