### ISSUE TITLE
Removing a storage node with disks/asds in error should clean up everything

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1283]
Noticed on OVH when several storage nodes were taken offline
The recycle bin icon on the right should not be enabled in this case according to @khenderick 
As we will now simply remove the node from the model, while we should in fact remove all asds/disks first.

![screen shot 2016-12-19 at 09 35 06](https://cloud.githubusercontent.com/assets/8393135/21344607/e163d65c-c69c-11e6-9fff-cd2195b333c1.png)

**Comment by khenderick** [comment]
openvstorage-2.7.9.1

**Comment by pploegaert** [comment]
@khenderick: I tried validating this on 10.100.187.32 (3 node setup of which node 1 was powered off)
But I still see the recycle bin enabled:
https://10.100.187.32/#full/ovs-backend/053b67c7-e539-41d5-9f16-373a00047ae6

Which code change would have fixed this?

**Comment by khenderick** [comment]
I think that one has been closed by mistake as there's indeed no PR, nor a dev package. Sorry.

**Comment by pploegaert** [comment]
Np, env link above is available for non-destructive investigation ;) ... note node1 is kept offline, so only 2 out of 3 nodes are running.

**Comment by khenderick** [comment]
To fix this issue correctly we need to keep state on the side of the asd-manager. We're making too much educated guesses at this moment, and it's hitting the limit.
