### ISSUE TITLE
Extending vPool with accelerated backend B but finishes successfully with accelerated backend A

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1288]
On a customer environment we observed the following:
* vPool is extended to node X with accelerated backend A --> successfully deployed with accelerated backend A
* vPool is removed from node X
* vPool is extended to node X with accelerated backend B --> successfully reported vpool_creation but with accelerated backend A

We are unable to change the accelerated backend on node X, even when clearing the cache with @khenderick .

Workaround: delete the whole vPool and recreate it with the same name

**Comment by khenderick** [comment]
Fixed by #1360, packaged on dev in openvstorage-2.7.10-dev.1484837266.35ad485

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/441
