### ISSUE TITLE
Vpool unusable after extending with wrong params using API

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1289]
### Problem description
Linked ticket: https://github.com/openvstorage/framework/issues/790
When using the API and sending the wrong data (or missed some requirements eg. DB role)
You are unable to manage this vpool and you lose the write cache because of the unusable vpool.

This only occurs when extending using the API itself and supplying the wrong information. The vpool immediately starts to setup/extend but the checks come to late and the vpool cannot recover.
![screenshot from 2016-12-21 11-56-10](https://cloud.githubusercontent.com/assets/17570109/21389416/e7e993e6-c781-11e6-855b-530ec250a9da.png)
![selection_104](https://cloud.githubusercontent.com/assets/17570109/21389428/f8c8dd16-c781-11e6-88c5-f6a7a4f682d2.png)

### Packages
```
ii  openvstorage                                        2.7.9-rev.4463.0761b63-1       amd64                          openvStorage
ii  openvstorage-backend                                1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin
ii  openvstorage-backend-core                           1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin core
ii  openvstorage-backend-webapps                        1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin Web Applications
ii  openvstorage-core                                   2.7.9-rev.4463.0761b63-1       amd64                          openvStorage core
ii  openvstorage-hc                                     1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                                    1.6.9-rev.508.9903a29-1        amd64                          Open vStorage Backend ASD Manager
ii  openvstorage-webapps                                2.7.9-rev.4463.0761b63-1       amd64                          openvStorage Web Applications

```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1318 -- > openvstorage-2.7.9-dev.1483975363.540a29b

**Comment by khenderick** [comment]
openvstorage-2.7.9.1
