### ISSUE TITLE
Sorting issue with storage nodes on backends

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1291]
### Problem description
Context: occurred when I removed a disk from my virtual machine, restarted the virtual machine and automatically got back to backend page
![gifrecord_2016-12-21_150719](https://cloud.githubusercontent.com/assets/17570109/21392296/7f43feea-c78f-11e6-9908-fb6ac4aaeb19.gif)

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework-alba-plugin/issues/326

**Comment by JeffreyDevloo** [comment]
Did not encounter this annoying bug anymore on the affected environment.
