### ISSUE TITLE
More file descriptors for alba arakoons(abm + nsm)

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1295]
Since we implemented https://github.com/openvstorage/framework/issues/1274 there are way more client connections going into the abm and nsm clusters which leads to the necessity to configure higher number of allowed filedescriptors.
2 vpools over 5 nodes with each 8 proxies for example will open 800 client connections into the abm arakoon. Lets set the new limit to 8192(same as alba proxies).

**Comment by khenderick** [comment]
Let's not forget the migration code.
