### ISSUE TITLE
Open file descriptor inconsistencies

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1296]
Our alba-maintenance and alba-proxy service templates have an open file descriptor limit configured, but for systemd this limit is set at 8192, while for upstart its set to 4096

Systemd
```LimitNOFILE=8192```

Upstart
```limit nofile 4096 4096```

The 2 numbers in the upstart config file indicate a hard and a soft limit and the number of open file descriptors is not the sum of the 2 numbers as falsely assumed

```
A hard limit can only be raised by root (any process can lower it). So it is useful for security: a non-root process cannot overstep a hard limit. But it's inconvenient in that a non-root process can't have a lower limit than its children.

A soft limit can be changed by the process at any time. So it's convenient as long as processes cooperate, but no good for security.
```

PS: When fixing, take migration code into account

**Comment by kvanhijf** [comment]
Fixed by #1308 
ALBA maintenance and ASD processes are fixed using the post-update code executed via the post-installation scripts of the openvstorage-SDM package

Arakoon is fixed by the migration code for the extensions
ALBA proxies are fixed by the migration code for the multiple proxies. Those services are replaced by new services and thus recreated from the new templates (using 8192)

**Comment by khenderick** [comment]
openvstorage-2.7.9.1

**Comment by pploegaert** [comment]
VALIDATED OK on Fargo RC4:
root@e187-1:~# cat /proc/1472/limits
Limit                     Soft Limit           Hard Limit           Units     
...
Max open files            8192                 8192                 files     
...
