### ISSUE TITLE
Update to ovs setup reorder the questions asked and breaks the interactive setup

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1304]
This changes the order of the interactive setup ... pls move the question for the public IP after the cluster_name, as we now can ask to create a new cluster, get a question for the ip and then the question for the cluster_name

This breaks the interactive setup and requires an update of the documentation too ...

**Comment by wimpers** [comment]
@pploegaert @kvanhijf  I believe this one can be closed as we will keep the changes in the framework and update the documentation and integration test?

**Comment by kvanhijf** [comment]
If @pploegaert also agrees: yes

**Comment by pploegaert** [comment]
Issue moved to [openvstorage/integrationtests #394](https://github.com/openvstorage/integrationtests/issues/394) via [**ZenHub**](https://www.zenhub.com/)
