### ISSUE TITLE
asd-manager puts all nvmes under one node

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1305]
### Problem description
We found the following case on a gig environment:
![selection_110](https://cloud.githubusercontent.com/assets/17570109/21522492/4287160a-cd06-11e6-8eb8-872a6c2938a2.png)
This is the first node that has a nvme drive and it appears that all of the other nodes nvmes are put on this node on the backend page

Node 12-17 have 2 nvmes each and node 17-20 have 1 each. So a total of 14 nvmes are found for the storagebackend (solely asd-manager running).

**Comment by wimpers** [comment]
Duplicate of https://github.com/openvstorage/framework/issues/1231 ?

**Comment by JeffreyDevloo** [comment]
Duplicate indeed, should have checked. Also wrong repo...
