### ISSUE TITLE
DTL deployment possible enhancements

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1307]
Currently we are implementing the multiple StorageDrivers feature. While doing this, the question arose whether to also deploy multiple DTL services on each node.
In our current setup, we deploy max 1 DTL service on a host and this DTL can be used by any and all vPools

Questions that pop up:
1) Will performance be impacted when a lot more StorageDriver processes make use of a single DTL?
2) Shouldn't a DTL process be directly linked to a vPool? Should StorageDriver processes belonging to vPool A be able to access the DTL deployed by vPool B?

**Comment by khenderick** [comment]
The DTL isn't shared between vPools, and we deploy one DTL per SD. I assume this bug is invalid, @kvanhijf?

**Comment by kvanhijf** [comment]
Point 2) in the description is invalid indeed, but we could still verify whether to deploy 1 DTL per voldrv instance per node per vpool OR 1 DTL per node per vpool regardless of the amount of voldrv instances

In the current code, the 2nd is implemented

**Comment by wimpers** [comment]
We want 1DTL per storage driver. So a 1 to 1 relation for storage drivers and DTLs.

@kvanhijf anything that needs to happen in that case.

**Comment by kvanhijf** [comment]
Nope, no changes needed for a 1-to-1 relation
