### ISSUE TITLE
Integrate new rora

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1309]
Integrate new rora. From now on, the voldrv needs to use rora if:

no local fragment cache

**Comment by khenderick** [comment]
See openvstorage/alba#545

**Comment by domsj** [comment]
Now is still the time to come up with something more elaborate?

Enabling rora is actually only useful when the preset that is used for the backend from which the partial reads are supposed to be done (the fragment cache backend if any, or just the backend if no fragment cache was specified) does not use compression.
and does not use encryption. (once https://github.com/openvstorage/alba/issues/447 has been fixed it would be ok if CTR mode encryption was used.)

The downside to enabling rora in these situations is some extra overhead (memory & cpu).

Maybe the best solution would be some mechanism in the proxy client that detects whether doing any of the rora related caching/processing actually makes sense? Then you could just always enable it...

**Comment by khenderick** [comment]
> Maybe the best solution would be some mechanism in the proxy client that detects whether doing any of the rora related caching/processing actually makes sense? Then you could just always enable it...

That does make a lot of sense; in the future it could even start to "learn" what gives the best performance by giving all options a try and see what's best.

**Comment by khenderick** [comment]
After discussion with @domsj and @wimpers, it was decided that Alba will figure out whether to use rora or not based on the parameters it can detect. The framework will enable it by default.

**Comment by khenderick** [comment]
Fixed in #1311 
Dev package: openvstorage-2.7.9-dev.1483628517.b61d45a

**Comment by khenderick** [comment]
openvstorage-2.7.9.1
