### ISSUE TITLE
delete vdisk from detail page redirects to wrong page

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework#1314]
vpools -> choose vpool -> choose vdisk -> delete vdisk
redirect goes to vdisks page instead of going back to vpool detail page

**Comment by wimpers** [comment]
Too much work for RC3.

**Comment by khenderick** [comment]
#1423 -> openvstorage-2.7.12-dev.1486484498.34f2b88
openvstorage/framework-alba-plugin#358 -> openvstorage-backend-1.7.12-dev.1486484573.dd1a9ac

**Comment by khenderick** [comment]
openvstorage-2.7.12.1
openvstorage-backend-1.7.12.1

**Comment by pploegaert** [comment]
VALIDATION OK
