### ISSUE TITLE
Redis is only listening on 127.0.0.1

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1320]
Redis is only listening on 127.0.0.1 iso the public ip address. Do we want to reconfigure it to listen to the public ip address so it can actually be used for Alba's LRU?

**Comment by wimpers** [comment]
Yes, please

**Comment by khenderick** [comment]
Fixed by #1322 
Dev package: openvstorage-2.7.9-dev.1483979756.f1e6532

**Comment by khenderick** [comment]
openvstorage-2.7.9.2

**Comment by pploegaert** [comment]
VALIDATED OK:
root@ub1604:~# cat /etc/redis/redis.conf  | grep -v ^# | grep bind
bind 10.100.131.43
