### ISSUE TITLE
Remove Etcd

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1323]
We are currently still supporting Etcd to be used for our configuration management, but currently the setup is even broken when using Etcd. Framework doesn't get enough time to implement changes and test both with Etcd and Arakoon, resulting in a broken installation (and most likely a lot more issues).
So we should either make sure that all paths involving Etcd are properly tested or remove Etcd entirely. Or continue making a fool out of ourselves stating Etcd is supported while it isn't, similar to CentOS.

Failure witnessed while extending the cluster with a 2nd node
```
root@OVS-2-193-152:~# ovs setup
+++++++++++++++++++++++++++++
+++  Open vStorage Setup  +++
+++++++++++++++++++++++++++++

+++ Setting up connections +++


+++ Collecting cluster information +++


+++ Preparing node +++

Exchanging SSH keys and updating hosts files

+++ Adding extra node +++

Extending Etcd cluster
ERROR: Failed to setup extra node
ERROR: Connection to etcd failed due to MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=2379): Max retries exceeded with url: /v2/keys/ovs/framework/hosts/N7W0KZ8Qu2q4b3hs/services/etcd-config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91d00ab710>: Failed to establish a new connection: [Errno 111] Connection refused',))",)


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++  An unexpected error occurred:                                                  +++
+++  Connection to etcd failed due to                                               +++
+++  MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=2379): Max retries    +++
+++  exceeded with url:                                                             +++
+++  /v2/keys/ovs/framework/hosts/N7W0KZ8Qu2q4b3hs/services/etcd-config (Caused by  +++
+++  NewConnectionError('<urllib3.connection.HTTPConnection object at               +++
+++  0x7f91d00ab710>: Failed to establish a new connection: [Errno 111] Connection  +++
+++  refused',))",)                                                                 +++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
root@OVS-2-193-152:~#
```

**Comment by wimpers** [comment]
To be discussed with stakeholders

**Comment by wimpers** [comment]
After discussion with stakeholders: can be removed.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1340 --> openvstorage-2.7.10-dev.1484653038.84fddbd
https://github.com/openvstorage/alba-asdmanager/pull/206 --> openvstorage-sdm-1.6.10-dev.1484653188.cc593cb
https://github.com/openvstorage/framework-alba-plugin/pull/333 --> openvstorage-backend-1.7.10-dev.1484653119.dadeb6d

**Comment by kvanhijf** [comment]
@QA: 
* Deleted /opt/OpenvStorage/config/templates/systemd/ovs-etcd-proxy.service 
* Deleted /opt/OpenvStorage/config/templates/systemd/ovs-etcd.service
* Deleted /opt/OpenvStorage/config/templates/upstart/ovs-etcd-proxy.service 
* Deleted /opt/OpenvStorage/config/templates/upstart/ovs-etcd.service
* Deleted /opt/asd-manager/source/tools/configuration/etcd_config.py
* Recursively deleted /opt/OpenvStorage/ovs/extensions/db/etcd/
* /opt/OpenvStorage/config/preconfig.json no longer allows the 'config_mgmt_type' key
* /opt/asd-manager/config/preconfig.json no longer allows the 'store' key
* Interactive ovs setup no longer asks: "Select the configuration management system"
* Interactive asd-manager setup no longer asks: "Select the configuration management system"
* 'etcd' and 'python-etcd' are no longer dependencies of openvstorage package and openvstorage-sdm package

@openvstorage/qa : openvstorage-2.7.10.1

**Comment by JeffreyDevloo** [comment]
Ever since Arakoon was the default configuration management we never really cared about ETCD anymore.
Like kvanhijf says: even the setup was broken...
Not worth validating the removal of files...
