### ISSUE TITLE
VPool with global write buffer < 2GB is unusable

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1332]
# Problem

In continuation of https://github.com/openvstorage/volumedriver/issues/228, the framework allows you to create a vPool with global write buffer smaller than the given `backoff_gap` of 2GB.
```
    "scocache": {
        "trigger_gap": "1GB", 
        "backoff_gap": "2GB", 
        "scocache_mount_points": [
            {
                "path": "/mnt/hdd1/integrationtests-vpool_write_sco_1", 
                "size": "1024000KiB"
            }
        ]
    }, 
```

2GB `backoff_gap` is set by default as seen here: https://github.com/openvstorage/framework/blob/68577ee755207a8a4ead758c50c8debc995cd1e4/ovs/lib/storagerouter.py#L762

This results in the vPool being unusable and the volumedriver throws the following errors:
```
Jan 11 10:39:42 ovs-node01-1604 volumedriver_fs.sh[31303]: 2017-01-11 10:39:42 635873 +0100 - ovs-node01-1604 - 31303/0x00007f26277fa700 - volumedriverfs/LockedArakoon - 00000000000004fb - info - run_sequence: unregister volume succeeded after 1 attempt(s)
Jan 11 10:39:42 ovs-node01-1604 volumedriver_fs.sh[31303]: 2017-01-11 10:39:42 635947 +0100 - ovs-node01-1604 - 31303/0x00007f26277fa700 - volumedriverfs/VFSLocalNode - 00000000000004fc - error - create_volume_: 84f3c4e9-0f04-4baf-90a8-341fed5192fe: failed to create volume: cache size is not large enough
Jan 11 10:39:42 ovs-node01-1604 volumedriver_fs.sh[31303]: 2017-01-11 10:39:42 635993 +0100 - ovs-node01-1604 - 31303/0x00007f26277fa700 - volumedriverfs/FileSystem - 00000000000004fd - error - do_mknod: Failed to create object Volume-84f3c4e9-0f04-4baf-90a8-341fed5192fe @ "/test.raw", mode 0644, uid 0, gid 0: cache size is not large enough
Jan 11 10:39:42 ovs-node01-1604 volumedriver_fs.sh[31303]: 2017-01-11 10:39:42 636049 +0100 - ovs-node01-1604 - 31303/0x00007f26277fa700 - volumedriverfs/FuseInterface - 00000000000004fe - error - convert_exceptions: "/test.raw": caught fungi::IOException: cache size is not large enough , code 0
```

# Possible solution
Anticipate the `backoff_gap` size vs. the `scocache_mountpoint_size` (aka the global write buffer) or block smaller global write buffers than 2GB.

**Comment by wimpers** [comment]
Minimal write buffer should be bigger than trigger_gap and backkoff_gap.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Implementation has become the following
Default backoff_gap size has become 2GiB io 2GB
Default trigger_gap size has become 1GiB io 1GB

Scenario:
Partition1 with WRITE role of 1GiB
Partition2 with WRITE role of 99GiB
User wants to use 50GiB out of 100GiB available
Partition1 is 1% of total space --> 1% of 50GiB will be assigned to this partition == 0.5GiB
Partition2 is 99% of total space --> 99% of 50GiB will be assigned to this partition == 49.5GiB
Smallest is 0.5GiB which is smaller than the 2GiB default and thus will backoff_gap be 0.5GiB and trigger_gap is always half of backoff_gap being 0.25GiB

If smallest is larger than 2GiB, the backoff_gap and trigger_gap will have the default values

https://github.com/openvstorage/framework/pull/1485 --> openvstorage-2.7.13-dev.1488356835.93d0d6d

**Comment by khenderick** [comment]
@kvanhijf, can you double check above linked ticket to see whether all is covered by this change?

**Comment by kvanhijf** [comment]
Above ticket is not fully covered by this fix

**Comment by khenderick** [comment]
openvstorage-2.7.13.1
