### ISSUE TITLE
Block allowing to set a cloned volume as template

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1333]
Block allowing to set a cloned volume as template as this caused https://github.com/openvstorage/volumedriver/issues/229 to appear.

* Block this in the API
* Don't allow it in the GUI by disabling the set as template button

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1338 --> openvstorage-2.7.10-dev.1484656223.e74fe20
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by kvanhijf** [comment]
unstable: openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
VALIDATION OK:
- covered in unit-test
- manual validation via GUI: OK
