### ISSUE TITLE
Update durandal

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1341]
There is a newer version of Durandal out (2.1) with more functionality and bug fixes. Let's update the current version we have.

While at it we should also fix https://github.com/openvstorage/framework/issues/1077 .

**Comment by JeffreyDevloo** [comment]
Updating Durandal also caused Knockout to be updated.

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/framework/pull/1842
Packaged in: openvstorage_2.11.0-dev.1508425646.3f58fa3-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
