### ISSUE TITLE
Removing a vpool while mountpoint is busy just removes vpool from dal

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1352]
### Problem description
When removing a vpool whilest the mountpoint is busy (by being in there in the kernel) results in the vpool being removed from the DAL and killing the vpool.
The vpool however comes back up and can still run.

@todo need to put further proof here.

**Comment by wimpers** [comment]
We should first try to remove from the voldrv and only when that works remove from the DAL?

**Comment by kvanhijf** [comment]
Issue can be closed since removing a vPool while the mountpoint is kept busy is no longer possible
Has been fixed by https://github.com/openvstorage/framework/issues/1339

**Comment by wimpers** [comment]
@pploegaert fyi maybe good to write a  test for this.
