### ISSUE TITLE
RDMA capable is set to False but still able to create vpool with RDMA

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1357]
When the flag RDMA capable is set to false it is still possible to create a vpool with RDMA. Extending is not possible. 

Had this on a GIG environment. The nodes were not RDMA capable but the integration_test from @openvstorage/qa was able to create a vpool but was unable to extend it. 

It has to be impossible to create a RDMA vpool when the nodes are not RDMA capable.

**Comment by kvanhijf** [comment]
The 'dtl_transport' entry in the 'config_params' should be validated whether it can be set on the vPool.
When 'dtl_transport' != 'TCP' and rdma_capable flag on the StorageRouter is False, we could potentially first refresh the Storagerouter's hardware. If after this check, the rdma_capable flag is still False, setting up / extending the vPool should raise.

**Comment by wimpers** [comment]
Lets fix this in the API.

**Comment by kvanhijf** [comment]
@wimpers : Should be blocked in GUI too

**Comment by khenderick** [comment]
After some discussion with @matthiasdeblock and based on a quick test, the GUI is already covered. Only the API allows RDMA transport while the node is not capable of RDMA.

**Comment by khenderick** [comment]
Fixed by #1407, packaged on dev in openvstorage-2.7.12-dev.1486374024.de8e760

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/454
