### ISSUE TITLE
Configure the DTL over RDMA

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1375]
In case there is RDMA hardware, allow to specify that the DTL can run on  RDMA.

**Comment by wimpers** [comment]
@khenderick , I saw you can already select transport mode under DTL. So this one is covered. Does it do more then setting the transport for the DTL f.e. transport to the ASDs/Edge? The edge transport type gets set on the edge side by `openvstorage+<protocol>:<ip of the performance node>:<vPool port>/<vDisk name>` where the protocol is RDMA.

**Comment by wimpers** [comment]
![addvpool](https://cloud.githubusercontent.com/assets/8392927/22298881/65102450-e322-11e6-821a-5c3a7bbaaa79.jpg)

**Comment by saelbrec** [comment]
@wimpers ,
This DTL selectable transport mode is currently not having any effect as it is configuring the 'distributed_transaction_log' section in the volumedriver config which is overruled via command line options in the systemd service.
So it can indeed be re-purposed to configure the selected protocol for the DTL service being deployed.

@khenderick  ,
Any concerns/questions about this?

**Comment by khenderick** [comment]
Assuming that this ticket is only about whether the DTL should or should not use RDMA, I can't see anything that we might be missing as long as the DTL settings is shared on vPool level.

**Comment by wimpers** [comment]
Correct. All DTLs need to be on RDMA for a vPool.

**Comment by khenderick** [comment]
On a side note, shouldn't we also put some effort in getting rid of the "global RDMA flag" then, and just allow the user to between RDMA and TCP for ASDs and Edge as well? Can be a separate ticket, but isn't much work anyway. This global flag never actually worked as we never got a user that needed all-or-nothing.

**Comment by saelbrec** [comment]
Initially we were specifically asked to implement the all or nothing approach, but your suggestion is what it should have been.
As there are use cases where this flexibility in configuration is required. Will be tackled in different issue.

**Comment by khenderick** [comment]
Fixed by #1380, packaged on dev in openvstorage-2.7.11-dev.1485505077.b6988cb

The DTL RDMA setting will reflect in the DTL server configuration. The global RDMA flag will be ignored.

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/454
