### ISSUE TITLE
Improve edge HA node selection

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1376]
In case of a HA scenario the Edge doesn't take into account node which are down (marked offline) or in maintenance (https://github.com/openvstorage/volumedriver/issues/236).

The framework should set the distance to max cost 2**32-1 if a node is set to offline.

**Comment by wimpers** [comment]
To be discussed for Gilbert.
How much time would it take?

**Comment by khenderick** [comment]
We would need to keep track of whether a StorageDriver is marked offline or not. Either by a fixed property that we set/clear on the API call, or (preferably) a dynamic property so we can ask the StorageDriver whether it's online or offline (@arne, can we somewhere see if a given StorageDriver is marked offline?). Then we can indeed set the distance to max between the offlined StorageDriver and the others. Should take a day or two.

However, I'm not sure whether it's a good idea to re-introduce the Framework as a dependency on making HA work as expected. I think it makes a lot more sense to provide this as metadata to the Edge so the Edge client knows about offline StorageDrivers. The framework will always be slower than reality, so in case of issues, it's still possible that some Edge clients will already be redirected to an offline node before the framework could reconfigure all StorageDrivers.

**Comment by wimpers** [comment]
After discussion with @saelbrec the decision was not to abuse the framework and have the voldrv do it the right way as part of https://github.com/openvstorage/volumedriver/issues/236 .
