### ISSUE TITLE
Children vdisks of vtemplate is 0 but in reality its >= 1

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1384]
I was in the process of expanding the vtemplate testing. When I hit a strange issue; the amount of children that was displayed on a certain vtemplate was 0 but in reality (and in model) it was 1.

Looking further at the issue with @khenderick, there was a front-end issue.

**Comment by khenderick** [comment]
Fixed by #1392, packaged on dev in openvstorage-2.7.11-dev.1485936521.c25e423

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation OK
