### ISSUE TITLE
API to restart a volume

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1389]
API to restart a volume

**Comment by kvanhijf** [comment]
In which cases would we require this?  Shouldn't this type of action be attempted by some sort of monitoring? And raise an alert for OPS in case of failure
Or do we have other scenarios in which we can end up with a bunch of halted volumes?

**Comment by khenderick** [comment]
@kvanhijf, it's most likely to be used as a workaround where the volumedriver doesn't keep trying to start it's volumes e.g. after a reboot. It's possible that the backend starts up slower and that the backend is not yet available when the volumedriver process starts.

So most likely, somebody will have to write a tool that checks for volumes that are down, validate whether they should or should not be down, and start them if required.

**Comment by kvanhijf** [comment]
@khenderick : aka monitoring?

**Comment by khenderick** [comment]
Most likely indeed.

**Comment by wimpers** [comment]
@kvanhijf yes, we now have customer monitoring going into the Framework internals to restart a disk.  Would make more sense to offer them an API

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework/issues/1351

https://github.com/openvstorage/framework/pull/1394  --> openvstorage-2.7.11-dev.1485960176.10850d4
https://github.com/openvstorage/framework-alba-plugin/pull/352 --> openvstorage-backend-1.7.11-dev.1485960239.26b33e6

**Comment by khenderick** [comment]
openvstorage-2.7.11.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/450
