### ISSUE TITLE
Configurable MDS safety per vPool

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1397]
Currently the MDS safety is a global config parameter set to 3. This makes sense for geoscale vPools  but might not be desirable for vPools which are completely local. 

This ticket tackles that:
* Move the MDS safety config to a vPool level. 
* Extend the create vPool API with an option to configure the MDS safety.
* In case there is a recovery domain set in the GUI, the amount of mds_safety is 3 otherwise 2.

This ticket should be tackled together with https://github.com/openvstorage/framework/issues/1212 .

**Comment by kvanhijf** [comment]
@wimpers : Changing the mds safety behind the scenes isn't a good solution imo. Instead i'd make it configurable in the GUI with a default of 3
Once we start implementing the 'Advanced configurations' for a vPool, this should go into that section. For now it'll be in the current configuration section where SCO cache and such can be configured

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1763 --> openvstorage-2.10.0-dev.1505202385.ca2d1eb

**Comment by kvanhijf** [comment]
MDS Safety can now be configured via GUI and API (default safety is 3)
GUI: In configuration page, on the bottom the MDS safety can be set
API: An additional dict can be passed (its optional), eg: 'mds_config_params': {'mds_safety': 3}

Through the GUI its not possible to overrule the MDS safety when extending a vPool
Through the API it is possible to overrule the MDS safety when extending a vPool
