### ISSUE TITLE
Display number of proxies on the vpool detail page

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1399]
### Problem description
Currently you can select the amount of proxies in the GUI but after the creation you can no longer fetch it using the GUI.

**Comment by wimpers** [comment]
Add the amount of proxies under  vPool > Configuration. (please remove the s while we are at it)

**Comment by khenderick** [comment]
@wimpers, that doesn't make much sense, as the amount of proxies might be different on every node.

**Comment by khenderick** [comment]
Fixed by #1421, packaged on dev in openvstorage-2.7.12-dev.1486475525.bed673f

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by JeffreyDevloo** [comment]
### Test result
Pretty picture and a peek to the future! oh wait, I'm just late...
![selection_133](https://cloud.githubusercontent.com/assets/17570109/25535417/438fa46e-2c37-11e7-9667-bce0f5257178.png)
