### ISSUE TITLE
Don't start framework services if framework update wasn't successful

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1401]
If the framework services are restarted if the framework update wasn't completely successful, code might start to run using mixed old-and-new code. This will cause various issues to be introduced in e.g. the model, preventing future updates to succeed.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
If any of the following goes wrong, the framework services will not be started again:
* openvstorage package fails to install
* openvstorage-backend package fails to install
* Extensions migration code fails to execute successfully
* DAL migration code fails to execute successfully

IMPORTANT:
In any of the above circumstances its import to first FIGURE OUT exactly WHAT WENT WRONG (and try to fix it) BEFORE STARTING the framework SERVICES again
Scenario to apply in above circumstances:
* Investigate issue
* Fix issue
* Start memcaches (if not running)
* Execute 'ovs update framework'
* Follow the logging and cross fingers for a successful update
* Check GUI again and update whatever still needs to be updated

https://github.com/openvstorage/framework/pull/1418 --> openvstorage-2.7.12-dev.1486462862.1a65dc7
https://github.com/openvstorage/alba-asdmanager/pull/220 --> openvstorage-sdm-1.6.12-dev.1486463014.a549aab
https://github.com/openvstorage/framework-alba-plugin/pull/357 --> openvstorage-backend-1.7.12-dev.1486462938.eabfc67

**Comment by khenderick** [comment]
openvstorage-2.7.12.1
openvstorage-backend-1.7.12.1
openvstorage-sdm-1.6.12.1
