### ISSUE TITLE
set/delete on arakoon for ovs-watcher

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1412]
There are quite a lot of set/delete actions on the ovsb arakoon which hammer the (root) filesystem with sync taking rather long (> 30ms/call)... (/opt/OpenvStorage/db/arakoon/ovsdb/tlogs)

Excerpt from the tlog:
```
2030020:(Vc ([Set            ;"ovs-watcher-5c3895f4-56d6-47cd-92cb-1fb9e2c69139";15;"...";],false)
2030021:(Vc ([Delete         ;"ovs-watcher-5c3895f4-56d6-47cd-92cb-1fb9e2c69139";],false)
2030022:(Vc ([Set            ;"ovs-watcher-0f1756bf-7aea-43ab-900d-4b2f58988e52";15;"...";],false)
2030023:(Vc ([Delete         ;"ovs-watcher-0f1756bf-7aea-43ab-900d-4b2f58988e52";],false)
2030024:(Vc ([Set            ;"ovs-watcher-865bdf1f-1358-4a6d-994c-2448218b6f81";15;"...";],false)
2030025:(Vc ([Delete         ;"ovs-watcher-865bdf1f-1358-4a6d-994c-2448218b6f81";],false)
```

```
# /usr/share/bcc/tools/ext4slower -j -p 20537
ENDTIME_us,TASK,PID,TYPE,BYTES,OFFSET_b,LATENCY_us,FILE
883408907920,arakoon,20537,S,0,0,31487,406.tlog
883408941372,arakoon,20537,S,0,0,32515,406.tlog
883409008107,arakoon,20537,S,0,0,37304,406.tlog
883409041504,arakoon,20537,S,0,0,32041,406.tlog
883409575015,arakoon,20537,S,0,0,35048,406.tlog
883409608473,arakoon,20537,S,0,0,33187,406.tlog
883410942137,arakoon,20537,S,0,0,26973,406.tlog
883410997902,arakoon,20537,S,0,0,49916,406.tlog
883414001269,arakoon,20537,S,0,0,34253,406.tlog
883414042995,arakoon,20537,S,0,0,40705,406.tlog
883414109780,arakoon,20537,S,0,0,37218,406.tlog
883414151507,arakoon,20537,S,0,0,40488,406.tlog
883414610041,arakoon,20537,S,0,0,34541,406.tlog
883414643489,arakoon,20537,S,0,0,33148,406.tlog
883416069082,arakoon,20537,S,0,0,36541,406.tlog
883416110896,arakoon,20537,S,0,0,40460,406.tlog
```
3x set/get/delete = 9 calls every 5 seconds...

**Comment by khenderick** [comment]
If we can't do these calls to check our arakoons, we need to move the responsibility of starting/stopping all services to the customer. Imo, if the root filesystem can't cope "hammering" it with about 2 iops, I think we should foremost get rid of all logging which most likely does a lot more iops.

**Comment by dejonghb** [comment]
It's the sync that's the hammer and arakoon needs to do that to ensure all data is persistent. Setting and direct deleting of a key gets you 2 sync calls to achieve nothing... There should be another way to check if arakoon is still ok, setting/deleting stuff and having this persisted all over the cluster every 5 seconds, really?

**Comment by khenderick** [comment]
We can switch to only executing a nop instead of a set/get/delete. 

Still, I'm not sure whether 2 iops is such a drama for a root filesystem. If somebody actually uses the product, the amount of set/get/deletes on the system might burst to a few hundreds per second. If the root filesystem can't handle the 2 iops, I think we'd be screwed under load.

**Comment by khenderick** [comment]
#1429 -> openvstorage-2.7.12-dev.1486635440.ff20425

**Comment by khenderick** [comment]
openvstorage-2.7.12.1
