### ISSUE TITLE
vPool with 1 storagedriver can configure DTL but it shouldn't

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1417]
During one of our autotests in https://github.com/openvstorage/integrationtests/issues/426 we noticed that the following test failed: `Configuring a DTL with only 1 storagedriver to a non existing location`

Steps to reproduce:
- We've setup domains
- Added a vpool on 1 node with storagedriver A
- Created a vdisk
- vdisk DTL went into `to be configured` as expected
- We changed the DTL to Sync and added a target domain (but it doesn't exists)
- We expect this to failed but it doesn't
- When looking into the vdisk object the DTL is actually set to a DTL of another vpool

**Comment by wimpers** [comment]
@kinvaris why do you consider this as critical?

**Comment by khenderick** [comment]
@wimpers, it's not expected and e.g. the DTL checkup can't cope with it nor correct it. Most likely there's some odd codepath that can cause this scenario and we can't revert it.

**Comment by kinvaris** [comment]
@wimpers because the DTL of a vdisk on vPool A is configured on vPool B, this equals guarantee dataloss when a failure would occur. I've currently only tested it with 1 storagedriver but its very plausible that it can occur with multiple storagedrivers

**Comment by khenderick** [comment]
Not sure how you get to dataloss @kinvaris.

**Comment by kinvaris** [comment]
@khenderick: well currently I've only tested it with 1 storagedriver, but its plausible that this scenario could occur with multiple storagedrivers. If you have a volume its target domain configured where there are no storagedrivers (for that vpool) and a error would occur on that hardware node, you would lose all undisposable SCO's because its somewhere managed by a foreign DTL. This scenario could very likely result in internal corruption of the volume

**Comment by khenderick** [comment]
Turns out we don't validate whether the selected target can actually be used at all. You ask Roubaix, we configure roubaix. Let's add some checking and validations.

**Comment by khenderick** [comment]
Fixed by #1419, packaged on dev in openvstorage-2.7.12-dev.1486455798.ec37992

**Comment by khenderick** [comment]
openvstorage-2.7.12.1
