### ISSUE TITLE
Integrate new FileSystem API of voldrv

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1431]
Integrate new FileSystem API:
* The sync logic should use it to update the devicename
* FileRename events should be reintroduced to catch devicename changes

**Comment by khenderick** [comment]
See: https://github.com/openvstorage/volumedriver/issues/252

**Comment by khenderick** [comment]
#1435 -> openvstorage-2.7.12-dev.1486715931.a80d9a3

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
concerns directory renames
unit test example:
https://github.com/openvstorage/framework/blob/develop/ovs/lib/tests/vdisk_tests/test_events.py#L202
