### ISSUE TITLE
Bad MDS configuration

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1433]
Scratch_directory and db_directory should not be the same:

```
 "metadata_server": {
        "mds_nodes": [
            {
                "host": "10.101.2.11", 
                "scratch_directory": "/mnt/ssd1/data01_db_mds_1", 
                "port": 26301, 
                "db_directory": "/mnt/ssd1/data01_db_mds_1"
            }
        ]
    },
```

[17:37:31] Arne Redlich: the db directory contains the actual rocksdb database, whereas the scratch directory is a temp directory that the MDS considers as its playground
[17:37:52] Arne Redlich: it could remove it / recreate it... don't know at the moment if it does

**Comment by khenderick** [comment]
I guess it works quite fine as it has always been configured like that. Nevertheless it's a small change.

**Comment by khenderick** [comment]
#1436 -> openvstorage-2.7.12-dev.1486728872.31c4445

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by pploegaert** [comment]
validated ok on fresh install, update will not change settings as volumes need to be restarted
