### ISSUE TITLE
Integrate HPRM

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1449]

**Comment by kvanhijf** [comment]
@khenderick : Please provide input on what needs to be done for this

**Comment by khenderick** [comment]
HPRM is the same as PRACC.
Current requirements:
* New package that has dependency towards alba package
* Provide systemd service that has the systemd templating, so a customer can enable the service via `systemctl enable pracc@some_vpool` which will setup the service
* In the framework, a pracc config file should be downloadable int he StorageDriver overview.

Framework part might be a pracc-specific plugin.

Assigned to @wimpers as `state_question` as there are still a few questionmarks.

**Comment by wimpers** [comment]
Open question(s) to be answered by @saelbrec , @redlicha and @cnanakos :
* How can we provide statistics from the edge (read, write, latency counters) to the framework.  We rather not have the framework go directly to the edge.
* How will the edge know to which pracc it needs to connect. (the current idea is that the edge akss teh voldrv for the vpoolname and with that name connects to the right socket)

**Comment by khenderick** [comment]
Naming:
* Repo name: `hprm-manager`
* Package name: `hprm-manager`
* Service name: `hprm@vpool_name`
* Folder: `/etc/hprm/...`

**Comment by kvanhijf** [comment]
Note to self:
https://github.com/openvstorage/alba_ee/pull/5/files#diff-b53421daab15a979ab25d71014c66f62
For information about pracc config

**Comment by kvanhijf** [comment]
@openvstorage/qa : Once the volumedriver team delivers a pracc'able package, you can test the following:
* Create a (or more) vPool(s)
* On vPool detail page --> mgmt tab, click the middle button (Generate HPRM config files)
* Follow the guidelines in the wizard (Copy the .tgz file to the node running qemu)
* Once the pracc service is up and running, ask the volumedriver what to do next :)

PS: Nice thing to test: Make changes in Arakoon cluster (extend/shrink) used for HPRM and see if changes are reflected in the arakoon config files on filesystem on the HPRM node
/etc/hprm/<vpool_name>/arakoon.ini
/etc/hprm/<vpool_name>/accelerated_arakoon.ini

##  IMPORTANT: PRs have not been merged in yet

**Comment by khenderick** [comment]
openvstorage-2.8.1
