### ISSUE TITLE
Master and slave tables for a volume in different MDS'es of the same volumedriver instance

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#1452]
```
In [2]: mds_clients = [ src.MDSClient(src.MDSNodeConfig("10.107.3.43", p)) for p in xrange(26300, 26303) ]

In [3]: vol = "dade6343-aa16-4d8a-9ee8-d4858de70c3e"

In [4]: [ vol in c.list_namespaces() for c in mds_clients ]
Out[4]: [True, True, False]

In [6]: [ c.get_role(vol) for c in mds_clients[:-1] ]
Out[6]: 
[volumedriver.storagerouter.storagerouterclient.Role.Master,
 volumedriver.storagerouter.storagerouterclient.Role.Slave]
```

```
In [8]: !dpkg -l openvstorage
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-==================================================================================================
ii  openvstorage                                   2.7.10.1-1                   amd64                        openvStorage
```

Since there were recently fixes regarding the MDS balancing this might be fixed already?

**Comment by saelbrec** [comment]
@khenderick , @kvanhijf ,
Do we have a unit test that can tell us if the MDS placement algorithm prevents this from happening?
If so, could this be an old MDS slave ?

**Comment by khenderick** [comment]
@saelbrec, we have indeed unittests in place that check all possible MDS movements. However, based on @redlicha's snippets, the master and slave role are each configured to a different MDS server (albeit it is served by the same volumedriver instance). This is something that is according to our logic (and tests) a perfectly possible (yet suboptimal) state that will typically occur during the rebalancing of volumes across all different MDS services where a slave is added to a new location which will eventually replace the current master once catched up.

While logging of the framework would be interesting, but I think that this would be a temporarily situation during rebalancing.

**Comment by redlicha** [comment]
@khenderick: if you want to take a look at logs: this was observed on g8-3 / stor-03, "vmstor" vpool.

**Comment by khenderick** [comment]
@redlicha, is there actually an issue with the observed (apart from the fact that it is obviously not an optimal configuration - it should get better after 4-8 hours)?

**Comment by redlicha** [comment]
There is no "issue" in the sense that voldrv could not deal with this setup; it's that this setup does not offer the expected redundancy: with 3 MDSes configured for a volume, the expectation would be that 2 nodes can go down without affecting the volume. However, due to the way the DTL works we currently cannot deal transparently with the loss of 2 *arbitrary* nodes anyway, so if the MDS balancing makes sure that there are at least 2 different nodes configured it's indeed only a cosmetic problem, but in general the MDS balancing should of course not rely on this.

**Comment by redlicha** [comment]
FWIW, the config has indeed changed in the meantime:
```
In [13]: [ (c.address(), c.port()) for c in client.info_volume(vol).metadata_backend_config.node_configs() ]
Out[13]: [('10.107.3.43', 26300), ('10.107.3.41', 26301), ('10.107.3.44', 26302)]
```

**Comment by khenderick** [comment]
Hmm, we have a [test](https://github.com/openvstorage/framework/blob/master/ovs/lib/tests/mdsservice_tests/test_mdsservice.py#L458) that validates whether a 4th slave will be added when we are rebalancing so that the configured safety of X *nodes* is always met. So that makes me wonder whether we still have some path where this doesn't happen and you're left with only 3 instances on 2 nodes.

I'll look into it further/

**Comment by khenderick** [comment]
After manually double checking all code & unit tests, I can't find anything that would indicate an issue in MDS placements. This means that either load or domains might cause the (temporary) state of reduced safety as we don't actively overload MDS servers. As observed above, these scenarios will eventually be automatically resolved as more MDS servers are deployed and rebalancing happens.

Anyway, during this manual verification, I've added some more docstrings in the tests: #1469
