### ISSUE TITLE
Recent update of python-crypto breaks ovs setup

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1456]
A new version of python-crypto breaks our ovs setup:

new: 2.6.1-6ubuntu0.16.04.1
previous: 2.6.1-6build1

```
+++ Preparing node +++

Setting up and exchanging SSH keys
No handlers could be found for logger "paramiko.transport"


++++++++++++++++++++++++++++++++++++++++++++++++++
+++  An unexpected error occurred:             +++
+++  CTR mode needs counter parameter, not IV  +++
++++++++++++++++++++++++++++++++++++++++++++++++++
```

Workaround: downgrade to previous version:

```
apt-get install -y --allow-downgrades python-crypto=2.6.1-6build1
```

**Comment by khenderick** [comment]
Upstream: https://bugs.launchpad.net/ubuntu/+source/paramiko/+bug/1665565

**Comment by khenderick** [comment]
A workaround for all fresh installs is to run `apt-get install -y python-crypto=2.6.1-6build1` before the usual openvstorage packages installation.

**Comment by khenderick** [comment]
Upstream PR in paramiko repo: paramiko/paramiko#714

**Comment by khenderick** [comment]
New upstream package `python-crypto 2.6.1-6ubuntu0.16.04.2` prints a warning instead of raising an error. 

This is no longer a blocking issue, but since there's still a warning being printed, I'd either wait for a final fix on `python-paramiko`, or suppress the warning during setup and create a ticket to remove the suppression once a fix is released.

**Comment by khenderick** [comment]
New paramiko is on the way

**Comment by wimpers** [comment]
Please keep an eye out for the new package

**Comment by khenderick** [comment]
No need for a milestone. We don't have to do any changes, and the issue affects all releases anyway.

**Comment by wimpers** [comment]
Please validate once new package is out

**Comment by khenderick** [comment]
Will be fixed in paramiko 1.17.4 and 1.18.2. Now it's waiting to be included in the ubuntu repos.

**Comment by khenderick** [comment]
USN-3199-2: https://www.ubuntu.com/usn/usn-3199-2/

**Comment by khenderick** [comment]
I don't think that they'll ship a newer version anytime soon, so let's suppress the warning.
#1483 -> openvstorage-2.7.13-dev.1488283533.76cf794

**Comment by kvanhijf** [comment]
@openvstorage/qa : Previous fix introduced DeprecatedWarnings elsewhere
Below fix should both not show the Crypto warning, nor the DeprecatedWarnings

https://github.com/openvstorage/framework/pull/1493 --> openvstorage-2.7.13-dev.1488441582.ddfb5fd

**Comment by khenderick** [comment]
openvstorage-2.7.13.1

**Comment by JeffreyDevloo** [comment]
### Validation
Attended setups are currently all passing since this change.
We have recently removed the downgrade to validate: https://github.com/openvstorage/setups/commit/52949ab6a25c13df28e496edeb761547addd34d3

### Test result
Test passed.
