### ISSUE TITLE
moving vdisk via GUI reports failure but ownership reported does change

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1480]
tried to move yavm10 from ftcmp02 to ftcmp04 via GUI reported failure, yet the ownership shown does get changed
![owner](https://cloud.githubusercontent.com/assets/15377625/23301541/b563f556-fa8a-11e6-9d5d-b24b29d332da.png)

**Comment by dejonghb** [comment]
before:
![be4](https://cloud.githubusercontent.com/assets/15377625/23302597/9608fda0-fa8f-11e6-9ed4-63dff4256eda.png)
after:
![after](https://cloud.githubusercontent.com/assets/15377625/23302604/9f703d36-fa8f-11e6-8785-57fe196d6e3d.png)

**Comment by khenderick** [comment]
Do you have any logging or something like a message that might indicate what went wrong?

**Comment by wimpers** [comment]
@dejonghb  see question above

**Comment by dejonghb** [comment]
No logging captured; just got the fast disappearing red toast it didn't work.... Someone who knows what to look for in the logs might get an idea of what's going on/wrong by retesting this on tenv186 (10.100.186.32) -- moving to ftcmp04 fails there. Could this be DTL related where trying to move to a node where the sync DTL is bivouacing fails?

**Comment by khenderick** [comment]
Logs are already gone. I'll try to reproduce.

**Comment by khenderick** [comment]
Can't reproduce. On my env, I can move disks around without issues or errors.

**Comment by dejonghb** [comment]
Also cannot reproduce it any more... no clue what could have changed (nothing updated)

**Comment by wimpers** [comment]
Please re-open if we can reproduce or have shiny logs
