### ISSUE TITLE
Ensure single decorator enhancement

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1487]
Eg: 3 tasks shortly after eachother launched (inline), so executed by 3 workers
Task 1 starts processing, task 2 is put on the queue, task 3 is discarded
However task 3 relies on the changes task 1 or task 2 should do, but since its discarded, it returns immediately
So the fix includes waiting for task 1 & task 2 in case its an inline task

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Ensure single decorator has been merged into the ovs_task decorator
`from ovs.lib.helpers.decorators import ovs_task`
To be able to make use of the ensure_single decorator, you have to add 'ensure_single_info'
```
@ovs_task(name='my_custom_task', ensure_single_info={'mode': 'DEFAULT'})
def my_custom_test():
```

Additionally a callback function pointer can be specified. This function will be executed in case other similar functions are in progress. Important, this function pointer must be a function defined in another module.


https://github.com/openvstorage/framework/pull/1479 --> openvstorage-2.7.13-dev.1488464044.88ca9e5
https://github.com/openvstorage/framework-alba-plugin/pull/374 --> openvstorage-backend-1.7.13-dev.1488464387.a84fedc

**Comment by khenderick** [comment]
openvstorage-2.7.13.1
openvstorage-backend-1.7.13.1
