### ISSUE TITLE
Ensure single with an optional callback

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1488]
### Feature description
The ensure single decorator should be able to take a callback function
Use cases:
- Reporting whether is task is being run an another node
- Extra control as a callback could also return a value for nested functions

```
def busy():
 print 'Im busy'

@ensure_single(callback=busy)
def update():
 print 'Updating'
 time.sleep(30)
```
- Update scheduled on 2 nodes
- Node 1 start to update
- Node 2 queues update -> update being run on Node 1 -> node 2 will execute callback
Node 1 output:
```
Updating
```
Node 2 output:
```
Im busy
```

**Comment by kvanhijf** [comment]
Issue fixed by https://github.com/openvstorage/framework/issues/1487
