### ISSUE TITLE
Reduce number of mgmt calls during snapshot creation

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#1507]
Observed on an env where automatic snapshots are taken each hour:
```
root@ovs03:~# ssh ovs02 'for i in $(seq 11 13); do journalctl -u ovs-volumedriver_vpool01.service -S "2017-03-09 ${i}:00" -U "2017-03-09 ${i}:05" | grep XMLRPC | grep Arguments | wc -l; done'
29078
28547
27245
```
"arbitrary" sample outside this interval:
```
root@ovs03:~# ssh ovs02 'for i in $(seq 11 13); do journalctl -u ovs-volumedriver_vpool01.service -S "2017-03-09 ${i}:10" -U "2017-03-09 ${i}:15" | grep XMLRPC | grep Arguments | wc -l; done'
1576
1410
1888
```

Zooming in yields the following distribution of mgmt calls during the former of the above two intervals:
```
Out[15]: 
{'ListClientConnections': 10,
 'isVolumeSyncedUpToSnapshot': 76,
 'snapshotCreate': 76,
 'snapshotInfo': 27014,
 'snapshotsList': 76,
 'volumeDriverPerformanceCountersV3': 10,
 'volumeInfo': 1116,
 'volumePerformanceCountersV3': 690,
 'volumesList': 10}
```

Since querying snapshot info involves acquiring a snapshot mgmt mutex per volume that impacts the data path and the lookup is expensive, the number of these calls should be reduced.

**Comment by khenderick** [comment]
After discussions with @redlicha, it was made clear to me that the list of `list_snapshots` is ordered by an internal incrementing per-volume snapshot counter. So we can rely on the `list_snapshots` output immediately.

I guess it will only need a day or so to fix this.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Only places for which there was room for optimizations were:
* VDiskController.create_snapshots
* VDiskController.delete_snapshots
A long running environment should have a lot less of the snapshotInfo calls in the logging after applying this fix.

https://github.com/openvstorage/framework/pull/1545 --> openvstorage-2.8.0-dev.1490098833.9bf7619

**Comment by khenderick** [comment]
openvstorage-2.8.0
