### ISSUE TITLE
Incorrect SCO cache calculation when no fragment caching is used

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1516]
We always take 88% of the requested SCO cache size on the WRITE partition on which the fragment caching is configured. But when no fragment caching is used, we should take the usual 98%. So without fragment caching, we currently have a decreased amount of expected SCO cache size.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
To easily verify this, have 1 WRITE role, create a vPool and choose 'No Caching' for the fragment cache
Choose all available Global Write Buffer size.
Once vpool has been created, check the volumedriver logfile and search for the "scocache" section.
Verify whether the configured "size" in that section is 98% of the requested Global Write Buffer size

https://github.com/openvstorage/framework/pull/1515 --> openvstorage-2.8.0-dev.1489153416.c3efa9d

**Comment by khenderick** [comment]
openvstorage-2.8.0
