### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1521]
Since we cannot predict what exact versions of other components will be installed, we should have some feature detection. 

Example for volumedriver:
* `features` property on storagedriver (does instance X has feature Y)
* `features` property on vpool (do all storagedrivers of vPool X have feature Y)

New code (and oob migration) can then query these features.

**Comment by khenderick** [comment]
Fixed by #1587, packaged in openvstorage-2.8.2-dev.1491990304.58cff50

Implemented as a `features` dynamic property on `StorageRouter`. Upstream code can use these to make decisions.

Example outputs:

`{'alba': {'edition': 'enterprise', 'features': ['cache-quota']}}`

`{'alba': {'edition': 'community', 'features': []}}`

**Comment by JeffreyDevloo** [comment]
### Information
We are currently relying on this features dynamic to be able to determine what ovs version we're working with.
We would see it if you would make some changes to this and thus have it covered!
Implementation: https://github.com/openvstorage/automation-lib/pull/40/
