### ISSUE TITLE
Additional plugin information ignored by the ArakoonInstaller

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1522]
The framework makes use of 'run' files to validate the running version vs the installed version for certain binaries. One of these examples is the Arakoon binary, which also depends on the ALBA binary. When an Arakoon cluster is created / extended, we provide additional plugin information, in order to know these running binary versions at any given moment. But in the current implementation, this information is ignored and thus the update will not function as expected

**Comment by kvanhijf** [comment]
@openvstorage/qa :
Should be verified in 2 ways after creating an ALBA Backend:
* Check /opt/OpenvStorage/run/arakoon-<backendname>-abm.version contains information about arakoon + alba
* ovs config get /ovs/framework/hosts/<host_id>/services/arakoon-<backendname>-abm should have an entry in the 'EXTRA_VERSION_CMD'

This should be the case after extending and shrinking the cluster on the relevant nodes


https://github.com/openvstorage/framework/pull/1523 --> openvstorage-2.8.0-dev.1489485194.6d2e401
https://github.com/openvstorage/framework-alba-plugin/pull/384 --> openvstorage-backend-1.8.0-dev.1489485828.921df96

**Comment by khenderick** [comment]
openvstorage-2.8.0
