### ISSUE TITLE
add storagerouter IP to vdisk edge client info

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1524]
If possible it would be nice to also display the storage router IP (+ port?) used by the edge client to connect to a vdisk.
At present only the IP of the client itself is displayed. Normally the connection should go via the storage router hosting the vdisk, but if this is not the case (eg. failover/HA) it is very useful to have this info available/visible.

**Comment by pploegaert** [comment]
During maintenance on node A this is very useful information as we're able to verify the volume is not only moved to node B but all edge clients also connect to node B.
Note that a manual dtl_checkup will still be needed to move the MDS master away from node A too.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
vDisk detail page now displays both server and client IPs + port
vDisk overview page also has edge information (tooltip on edge client column), but here we still kept the client info only

https://github.com/openvstorage/framework/pull/1578 --> openvstorage-2.8.2-dev.1491312226.16a8369

**Comment by JeffreyDevloo** [comment]
### Information
These changes are purely cosmetic:
On the vdisk detail page: the server info has been added:
![selection_001](https://cloud.githubusercontent.com/assets/17570109/26670159/de1ae1f4-46b0-11e7-9541-0c9d8b3b281f.jpg)
On the popover on the vdisks page, nothing has changed:
![screenshot from 2017-06-01 09-54-50](https://cloud.githubusercontent.com/assets/17570109/26670188/07682f1c-46b1-11e7-87de-2fddd43f5260.png)
