### ISSUE TITLE
Multi-snapshot-deletion support for /api/vpools/<vpool_guid>/remove_snapshots/

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1534]
Request to support the deletion of multiple snapshots for a vdisk in 1 call.
The mandatory param in other words becomes:
`snapshot_mapping`: A dict where the key is a vDisk guid and the value is a list of snapshot_id's to be deleted.

**Comment by khenderick** [comment]
#1537 -> openvstorage-2.7.14
#1538 -> openvstorage-2.8.0-dev.1490021732.46a050c
