### ISSUE TITLE
Set default values for vpool trigger and backoff gaps according to configured global buffer size

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1539]
Currently these gap settings don't scale upwards. Vpools with large(r) write buffers should get better protection against running full by being triggered to clean up earlier and more agressive.
To accomplish this we could use a % of the configured global writebuffer with upper boundaries:
* `trigger_gap`: 8%
* `backoff_gap`: 10%
* where the `upper_boundaries` is the % equivalent of a 500GB global writebuffer.

**Comment by khenderick** [comment]
#1540 -> openvstorage-2.7.14
#1541 -> openvstorage-2.8.0-dev.1490025857.b17e3de
