### ISSUE TITLE
Config abm cluster authentication failed , worng parameter.

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework#1554]
Hi all.
I config cluster ABM use guide https://openvstorage.gitbooks.io/administration/content/Installation/geoscalegettingstarted.html#creating-cluster-abm-optional
My ipython command.

> from ovs.extensions.db.arakoon.ArakoonInstaller import ArakoonInstaller
> from subprocess import check_output
> 
> cluster_name = "arakoon_performance_cluster"
> ip = "10.3.105.132"
> base_dir = "/opt/OpenvStorage/db"
> 
> ArakoonInstaller.create_cluster(cluster_name, 'ABM', ip, base_dir, ['albamgr_plugin'], locked=False, internal=False)

If i run ipython ovs by root user.

> /opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.pyc in create_cluster(cluster_name, cluster_type, ip, base_dir, plugins, locked, internal, filesystem, ports)
    326             raise ValueError('Cluster type {0} is not supported. Please choose from {1}'.format(cluster_type, ', '.join(ServiceType.ARAKOON_CLUSTER_TYPES)))
    327         print("ip :" + ip + "ArakoonInstaller.SSHCLIENT_USER: " + ArakoonInstaller.SSHCLIENT_USER)
--> 328         client = SSHClient(ip, username=ArakoonInstaller.SSHCLIENT_USER)
    329         if filesystem is True:
    330             exists = client.file_exists(ArakoonClusterConfig.CONFIG_FILE.format(cluster_name))

> /opt/OpenvStorage/ovs/extensions/generic/sshclient.py in __init__(self, endpoint, username, password, cached)
>     167                     SSHClient.client_cache[key] = client
>     168                 self._client = client
> --> 169         self._connect()
>     170 
>     171     def __del__(self):
> 
> /opt/OpenvStorage/ovs/extensions/generic/sshclient.py in _connect(self)
>     204             raise
>     205         except AuthenticationException:
> --> 206             raise NotAuthenticatedException('Authentication failed')
>     207 
>     208     def _disconnect(self):
> 
> NotAuthenticatedException: Authentication failed

If i run by user ovs 

> /opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.pyc in create_cluster(cluster_name, cluster_type, ip, base_dir, plugins, locked, internal, filesystem, ports)
>     350             if ports is None:
>     351                 ports = ArakoonInstaller._get_free_ports(client)
> --> 352             config = ArakoonClusterConfig(cluster_name, filesystem, plugins.keys() if plugins is not None else None)
>     353             config.nodes.append(ArakoonNodeConfig(name=node_name,
>     354                                                   ip=ip,
> 
> AttributeError: 'list' object has no attribute 'keys'

Thanks.

**Comment by kvanhijf** [comment]
Hi,

First of all 'plugins' should be a dictionary instead of a list, so it
should become {'albamgr_plugin': ''}
The value in the dictionary is useless for you, its something we require
for ourselves internally

And secondly, the fact that the code manages to be executed by 'ovs' user
and not by 'root', suggest that the SSH keys for the root user, have not
been exchanged properly?

Hope this helps

**Comment by hoannv46** [comment]
Hi @kvanhijf 
I sure ssh key added to /opt/OpenvStorage/.ssh/authorized_keys in each server.
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYdBDt0BDFw3Z8C8DdC4Gj0aPa1ThCiLYBbpWTfMmdqw== ovs@ovs-performance-1

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDjjifZDUu4gExToMy4EUxhaszzxUSkitgGgI1j1BbClM== root@ovs-performance-1
> 
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDB/9mQsL7GwM+0OWOLoeOfHx7QCjlnp7EBjlSazivLA== ovs@ovs-1
> 
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpKBlBAN/Tky9T+CTroHwbBCQgEkTFqFFjKsGXSRzxx5== root@ovs-1
> 
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDShVSulKUZ0pFYnqTMzLETgMx9h5Eh4It38oXb6jgBVJ6== ovs@ovs-1-peformance-2
> 
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDj5xnvOjdkNgZMHmcMC9Aki3Cd7kwdWy7Ln89Su== root@ovs-1-peformance-2
>

(I removed some text because it too long)

**Comment by hoannv46** [comment]
I recheck. It is my mistake, i recreate keygen.
This command is running.
Thanks @kvanhijf .
