### ISSUE TITLE
DTL status is not correct

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1555]
There is a problem with the dtl_status.
The DTL status on different components are differents.

volumedriver status:
```
In [3]: vd.name
Out[3]: u'nvmecor3-disk6'

In [4]: vd.info
Out[4]: 
{'cluster_cache_handle': {},
 'cluster_cache_limit': None,
 'cluster_multiplier': 8,
 'failover_ip': '',
 'failover_mode': 'OK_STANDALONE',
```

framework status:
```
In [5]: vd.dtl_status
Out[5]: 'disabled'
```
while healthcheck reported checkup_required (same method as above)
VDisk nvmecor3-disk6s DTL has an unknown status: checkup_required

GUI status:
```
<div class="tooltip-inner">DTL should be configured</div>
```

**Comment by kvanhijf** [comment]
@openvstorage/qa : No idea how to reproduce this specific scenario, but we did make changes to DTL allocation
DTL allocation rules:
* First priority to StorageRouters located in the vDisk's StorageRouter's Recovery Domain
* Second priority to StorageRouters located in the vDisk's StorageRouter's Regular Domain
* If Domains configured, but no StorageRouters are found matching any of the Domains on the vDisk's StorageRouter, a random SR in the same vPool is chosen
* If no Domains configured on the vDisk StorageRouter, any other StorageRouter on which the vPool has been extended is chosen


https://github.com/openvstorage/framework/pull/1634 --> openvstorage-2.9.3-dev.1494405832.d3fd1fc
https://github.com/openvstorage/alba-asdmanager/pull/249 --> openvstorage-sdm-1.9.0-dev.1494406013.e355601
https://github.com/openvstorage/framework-alba-plugin/pull/406 --> openvstorage-backend-1.9.0-dev.1494405928.789193e
