### ISSUE TITLE
Update can't handle EE package names

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1560]
Update can't handle EE package names

**Comment by khenderick** [comment]
Related change to be implemented: The framework packages should not ship the release name, shifting the responsibility of naming a release up the chain.

**Comment by khenderick** [comment]
#1561 -> openvstorage-2.8.1-dev.1490864871.094dd12
openvstorage/framework-alba-plugin#390 -> openvstorage-backend-1.8.1-dev.1490864954.3893e93
openvstorage/alba-asdmanager#237 -> openvstorage-sdm-1.7.1-dev.1490865036.92b2713

**Comment by khenderick** [comment]
@openvstorage/qa The release name as displayed in `Administration -> Support` is fetched from the package sources. If the repo is called `foo`, the displayed release name will be `Foo`. It can be manually changed by creating the file `/opt/OpenvStorage/config/release_name`. If it exists, its content will be used instead.

**Comment by khenderick** [comment]
It is not possible to automatically install e.g. an available `volumedriver-ee-server` if `volumedriver-no-dedup-server` is installed. The framework's updater won't "see" that update.

**Comment by khenderick** [comment]
openvstorage-2.8.1
openvstorage-backend-1.8.1
openvstorage-sdm-1.7.1

**Comment by JeffreyDevloo** [comment]
Updating our EE environments has been succeeded for a while now.
