### ISSUE TITLE
Watcher do not restart workers after failure

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1568]
As reported by @dejonghb, we saw an environment where none of the RMQ nodes were available from one node. The watcher detected that and stopped all framework services. After a while, one of the RMQ nodes came back, and the watcher started again. However, it seems it did not start the workers again (but it did start all other services).

**Comment by khenderick** [comment]
Also saw this but with ovs-webapp-api. Maybe systemd doesn't always do the restart dependencies?

**Comment by wimpers** [comment]
Might this be because only 1 came back?  QA team can you try to reproduce?

**Comment by dejonghb** [comment]
same problem as in #1709
