### ISSUE TITLE
Provide an optional tools pkg useful for debugging environments

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1576]
Placeholder for further discussion, not necessarily part of the fwk itself.

Possible solution: create new openvstorage-tools pkg with dependencies on:

- gdb
- vim
- smartmontools
- htop
- iotop
- lsscsi
- iperf
- sysstat

**Comment by redlicha** [comment]
* perf: comes with the linux-tools-* packages (common + matching one for the kernel)

**Comment by wimpers** [comment]
@jeroenmaelbrancke @jtorreke  @matthiasdeblock  aren't some  already part of the https://github.com/openvstorage/support-tools package or isn't that a package? Maybe take this request up there?

**Comment by jtorreke** [comment]
Most of those packages are included in the ansible install tools used for production environments. One of the first steps is to install these and then continue with the install of OVS.

**Comment by wimpers** [comment]
Currently getting installed 

```
   - bmon
    - cpio
    - dnsutils
    - ethtool
    - fping
    - git
    - gzip
    - hdparm
    - htop
    - ifstat
    - iftop
    - iotop
    - iperf
    - iputils-arping
    - irqbalance
    - kpartx
    - lshw
    - lsof
    - lsscsi
    - memtest86+
    - memtester
    - mtr-tiny
    - nicstat
    - nload
    - nmap
    - nmon
    - ntfs-3g
    - ntp
    - ntpdate
    - parted
    - pciutils
    - procps
    - rsync
    - screen
    - smartmontools
    - strace
    - sysstat
    - tcpdump
    - tcptraceroute
    - telnet
    - traceroute
    - vim
    - vnstat
    - xfsprogs
    - systemd-coredump
```

**Comment by wimpers** [comment]
To be added:
   - gdb

**Comment by wimpers** [comment]
@matthiasdeblock  @jtorreke  can you add gdb to ansible if needed and close this ticket?

**Comment by jtorreke** [comment]
The other packages in the list might be useful for having on our servers by default. But installing gdb everywhere is a bit overkill. I'd suggest to install gdb when needed. If apt isn't working, there's no need to install gdb as you'll have other fish to fry first.

**Comment by wimpers** [comment]
After discussion with @jtorreke set to closed. Re-open if you would disagree and provide a reason.
