### ISSUE TITLE
vDisk cache management

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1579]
Currently the fragment cache and cache settings (cache on write, read, write/read) are set per storage router. With this ticket we want to allow to set the cache settings per vdisk and define the amount/% of fragment cache a vDisk can occupy.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Important!!!!!  This is not yet final, integration in framework has been completed, but integration with ALBA has NOT BEEN DONE yet

TODO: Add unittest for the monitoring part

Things to know:
* DAL changes:
  * vdisk.cache_quota is a new property, which is default None. When manually overriding the quota for this vDisk (using set_config_params), the property will be set (in Bytes)
* MONITORING changes:
  * New OVS_WARNING log messages introduced. As soon as at least 70% ALBA Backend space is allocated for vDisk caching purposes, an hourly warning will be logged ( @openvstorage/operations to monitor this)
* BLL changes:
  * StorageRouterController.add_vpool now takes 'cache_quota' as parameter. When not specified, the vPool will not have a default value. When specified, each vDisk will have the vPool's default cache quota (which can be overruled using set_config_params)
  * VDiskController.clone now takes 'cache_quota' as parameter (default None). When cloning a vDisk, the caching quota will be taken over from the parent vDisk, unless 'cache_quota' is passed in to the clone call
  * VDiskController.create_from_template now takes 'cache_quota' as parameter (default None). When creating a vDisk from a template, the caching quota will be taken over from the template vDisk, unless 'cache_quota' is passed in to the create_from_template call
  * VDiskController.create_new now takes 'cache_quota' as parameter (default None). When creating a new vDisk, the caching quota will be None, unless 'cache_quota' is passed in to the create_new call
  * VDiskController.get_config_params now returns the 'cache_quota' for the vDisk
  * VDiskController.set_config_params now allows to set the 'cache_quota' for the vDisk (must be specified in Bytes)

https://github.com/openvstorage/framework/pull/1588 --> openvstorage-2.8.2-dev.1492591068.7d6addd

**Comment by wimpers** [comment]
The vDisk cache quota is only integrated in the Open vStorage Enterprise Edition (EE). feature detection should detect if it is an EE or OSE version. In case it is an OSE version leave the fields in the GUI greyed out so people can see there is something but they can't use it.

Add a (?) Only  available in the Open vStorage Enterprise  Edition.

**Comment by wimpers** [comment]
How does this relate to https://github.com/openvstorage/framework/issues/1603 ?

The block cache can be on a different ALBA backend (or even a directory).  Since the framework configures the block cache and the fragment cache on the same  backend and namespace. Does the vDisk quota than sets a limit on both the fragment + block cache together? Is there a way to set the quota on  block and fragment cache level individually? CLI based?

**Comment by wimpers** [comment]
After discussion with @domsj @saelbrec @toolslive 

please allow to set a quota for block cache and for the fragment cache. This should be tackled with https://github.com/openvstorage/framework/issues/1619

**Comment by khenderick** [comment]
Fixed by #1637, packaged in openvstorage-2.9.3-dev.1494846888.b15c594
