### ISSUE TITLE
Url redirection not correct in GUI from vpool to backend

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1583]
On OVH the redirection to the backend is on the storage ip instead of the public ip.
![url](https://cloud.githubusercontent.com/assets/2900612/24802969/06b7c1fe-1baa-11e7-84de-6d08cec1a716.png)

**Comment by khenderick** [comment]
Is this a duplicate of #1416?

**Comment by jeroenmaelbrancke** [comment]
Yep, closing ticket.
