### ISSUE TITLE
Add timeout parameter to the SSHClient

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1590]
Can you add a timeout parameter in SSHClient?
We use the SShClient run command to verify some stuff for the external arakoons but if one node is down we receive a timeout error.

It takes 248 sec before the timeout error appears.
```
externalArakoons : Install config Arakoons ---------------------------- 248.39s
```

```
2017-04-19 16:50:14 95700 +0200 - ovs-node01-1604 - 710/140621697152768 - arakoon_client/pyrakoon - 0 - ERROR - timed out: Unable to connect to ('10.100.199.182', 26400)\r
Traceback (most recent call last):\r
  File \"/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py\", line 1262, in connect\r
    self._socket = socket.create_connection(self._address, self._timeout)\r
  File \"/usr/lib/python2.7/socket.py\", line 575, in create_connection\r
    raise err\r
timeout: timed out\r
2017-04-19 16:51:14 97000 +0200 - ovs-node01-1604 - 710/140621697152768 - arakoon_client/pyrakoon - 1 - ERROR - timed out: Unable to connect to ('10.100.199.182', 26400)\r
Traceback (most recent call last):\r
  File \"/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py\", line 1262, in connect\r
    self._socket = socket.create_connection(self._address, self._timeout)\r
  File \"/usr/lib/python2.7/socket.py\", line 575, in create_connection\r
    raise err\r
timeout: timed out\r
```

**Comment by kvanhijf** [comment]
Important remark:  Endpoint specified is an IP and not a StorageRouter

**Comment by khenderick** [comment]
Already available. Added by #1476 for openvstorage/alba-asdmanager#224 and packaged from openvstorage 2.7.13.

```def run(self, command, debug=False, suppress_logging=False, allow_nonzero=False, allow_insecure=False, return_stderr=False, timeout=None)```

**Comment by jeroenmaelbrancke** [comment]
It's not the run method that timed out but the creation of the SSHClient.

```
client = SSHClient(ip, username='root')
```

**Comment by khenderick** [comment]
Sorry, I misunderstood the ticket.

**Comment by JeffreyDevloo** [comment]
The timeout has gone up to 9 minutes in certain tests. 
Specifying the timeout can now be done with:
```
client = SSHClient(ip, username, timeout=60)
```
Fixed by: https://github.com/openvstorage/framework/pull/1655
Packaged in: 2.9.6-dev.1496754516.bafd730-1

**Comment by JeffreyDevloo** [comment]
Packaged in openvstorage_2.9.6-1_amd64.deb
