### ISSUE TITLE
Integrate block cache (quick integration)

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1601]
Urgent integration of block cache.

Assumptions that have to be made:
* Only be used with Enterprise Edition
* Backwards incompatible API
* No too much testing

We should ASAP make a better integration!

**Comment by khenderick** [comment]
openvstorage-2.9.0

**Comment by JeffreyDevloo** [comment]
### Information
Block cache integrations has been added to our testing environments and is being deployed every night.
Pull request: https://github.com/openvstorage/automation-lib/pull/33
The integration part of the framework is therefore tested however the block cache feature itself is not.
Ticket for the block cache feature: https://github.com/openvstorage/integrationtests/issues/511

As we incorporate the frameworks integration of the block cache, I'm closing both of the tickets.
