### ISSUE TITLE
Integrate block cache (full integration)

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1603]
Continuation of #1601. Now completely integrated.

**Comment by khenderick** [comment]
Is codecomplete in the mean time.

**Comment by khenderick** [comment]
Was merged back by #1602, packaged in 2.9.4

**Comment by JeffreyDevloo** [comment]
### Information
Block cache integrations has been added to our testing environments and is being deployed every night.
Pull request: https://github.com/openvstorage/automation-lib/pull/33
The integration part of the framework is therefore tested however the block cache feature itself is not.
Ticket for the block cache feature: https://github.com/openvstorage/integrationtests/issues/511

As we incorporate the frameworks integration of the block cache, I'm closing both of the tickets.
