### ISSUE TITLE
Possibility to have the sshclient return the command's exit code

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#1613]
The framework's sshclient does currently not return the exit code of the executed command. sshclient.run() accepts allow_nonzero=False, but there is no way to fetch the exit code when you set allow_nonzero to True. As the method itself has the exit code internally, should be fairly easy to return it in the results as well.

**Comment by wimpers** [comment]
@khenderick how feasible is this request?

**Comment by khenderick** [comment]
Very

**Comment by kvanhijf** [comment]
This ticket can be closed as it was a very small fix, which has already
been done

**Comment by kvanhijf** [comment]
Nvm me, was confused with `return_stderr` which is already possible

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/framework-extensions/pull/47
Packaged in: openvstorage-extensions_0.3.0-dev.1508940072.3fe3325-1_amd64

Added a `return_exit_code` param for SSHClient.run

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/framework-extensions#66
