### ISSUE TITLE
Extend arakoonInstaller functionality with preferred_master capability

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1615]
In a setup where multi-dc vpools with global backends are used, it is for 1 dc fail safety recommended to spread your metadata server cluster across these datacenters as well.
But in most cases you still want 1 of these datacenter to be your primary one where as a consequence you want your arakoon master to be located.

**Comment by kvanhijf** [comment]
@openvstorage/qa : 

Rename:
* /opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py --> /opt/OpenvStorage/ovs/extensions/db/arakoon/arakooninstaller.py

ArakoonNodeConfig class
* Initialization of an ArakoonNodeConfig instance has been extended with
  * fsync
  * log_level
  * tlog_compression
  * preferred_master

ArakoonClusterConfig class
* method `read_config`
  * param `contents` is now optional
  * param `ip` is new and optional (Required for filesystem Arakoons
* method `export` has been renamed to `export_dict`
* method `import_config` has been introduced
  * This method can be used to update the configuration of a running arakoon cluster
  * Example:
```
config = ArakoonClusterConfig('my_arakoon_cluster')
my_config = config.export_dict()
my_config['global']['preferred_masters'] = 'node1'
config.import_config(my_config)
config.write_config()
ArakoonInstaller.restart_cluster('my_arakoon_cluster')
```

ArakoonInstaller class
* method `create_cluster`
  * Introduced `preferred_master` parameter (bool), this will cause the node on which you are creating the cluster, to become a preferred master node
* method `extend_cluster`
  * Introduced `preferred_master` parameter (bool), this will cause the node on which you are extending the cluster, to become a preferred master node
* method `shrink_cluster`
  * `ip` has been renamed to `removal_ip`
  * `remaining_ip` has been renamed to `ip` and is only required for filesystem Arakoons
* method `restart_cluster` has been introduced
* method `restart_cluster_add` has been renamed to `restart_cluster_after_extending`
  * param `current_ips` has been removed
  * param `ip` has been introduced and required for filesystem Arakoons only
* method `restart_cluster_after_shrinking` has been introduced (MUST be called after a `shrink_cluster` has been executed)


https://github.com/openvstorage/framework/pull/1618 --> openvstorage-2.9.2-dev.1493800277.9147cba
https://github.com/openvstorage/alba-asdmanager/pull/248 --> openvstorage-sdm-1.9.0-dev.1493800370.72ae5e5
https://github.com/openvstorage/framework-alba-plugin/pull/405 --> openvstorage-backend-1.9.0-dev.1493800734.54d33bd
