### ISSUE TITLE
Use a different namespace for fragment cache and block cache

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1619]
Use a different namespace for fragment cache and block cache even if you select the same backend for both.

**Comment by khenderick** [comment]
@domsj, we don't set a namespace for any of these. Is this something we have to change?

**Comment by domsj** [comment]
namespace name is based on the prefix. the fwk chooses the same prefix for both block & fragment cache, which results in the same namespace being used for both.

**Comment by khenderick** [comment]
Fixed in #1621, packaged in openvstorage-2.9.1 and openvstorage-2.9.2-dev.1493729927.7055282

**Comment by khenderick** [comment]
openvstorage-2.9.2-dev.1493729927.7055282
