### ISSUE TITLE
Move vdisks in bulk using API

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1646]
### Feature description
Relocate multiple vdisks at once using the api. Currently only one vdisk can be scheduled to be moved.

### Realistic use cases
- Volumedriver update requires all vdisks to be migrated to another volumedriver
- Maintenance requires a node to go down which has vdisks on it and those should be moved to another node

**Comment by wimpers** [comment]
@JeffreyDevloo how do you define where to move to? Randomly? A list of storage drivers? You might want to have more control over this. 

We have played with the idea before when thinking about https://github.com/openvstorage/framework/issues/1342 .

**Comment by kvanhijf** [comment]
Could be a list of storagedrivers. If none selected, divide all disks over
possible storagedrivers. Otherwise distribute over selected storagedrivers

**Comment by wimpers** [comment]
Ok, let's say you define a list of SD. Maybe you want to take the amount of vDisks already being served into account or the amount of free write buffer.


Currently I'm more tending towards a list of vDisks and a single Storage Driver as to keep the flexibility.

**Comment by kvanhijf** [comment]
True, but isn't a good implementation always for 'later' ?

**Comment by JeffreyDevloo** [comment]
I was not leaning on any implementation as of yet. I was just requesting the possibility of such a call :)

**Comment by wimpers** [comment]
The current OPS move script has as input a list of vdisks and moves these towards an MDS slave is living (preferrable the one in the same domain). See https://github.com/openvstorage/operations/blob/master/scripts/move_vdisk_advanced.py

In case no mds slave ... randomly move the vdisk to a SR in the same domain/Vpool.

**Comment by JeffreyDevloo** [comment]
That is not really the point of this api.
This api should make it possible to give a list of guids as arguments to move to a certain storagerouter. (It would not care about mds location, similar to the current move)

**Comment by wimpers** [comment]
There are 2 ways you could see this API
* move_to: post with list of vdisk executed on Storage Driver guid where to move to (your use case)
* move_away: post with list of vdisk executed on Storage Driver guid where the disks need to be moved away from  (my use case f.e. when doing maintenance)

Do you have a use case in mind where you want to move a list of vDisks (from different Storage Routers?) to a certain Storage Router?

**Comment by JeffreyDevloo** [comment]
Yes, the move vdisk advanced current implementation for example. Instead of every volume one by one, you could supply the list to move to that particular storagedriver. (We would use a similar call internally so we might as well expose it)

**Comment by sjovdnbos** [comment]
Fixed by #1917 
Package information: openvstorage-2.11.1-dev.1514908145.ef56594

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
