### ISSUE TITLE
API call /api/messages/6138427831... took 56.80 sec

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1649]
On the Nuvolat setup with  nodes the call https://172.17.16.22/api/messages/6138427831/wait/?message_id=6154&timestamp=1495627923608 took 56.80 sec

![dev_tools](https://cloud.githubusercontent.com/assets/2900612/26402755/d3f986f6-408b-11e7-900b-e3cd7223b9c1.png)

**Comment by khenderick** [comment]
That's long polling and takes between 0 and 60 seconds, that's perfectly normal.
