### ISSUE TITLE
5 minutes to load the backend page

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1650]
On Nuvolat it takes 5 minutes to load one backend (asd/presets).

Please have a look at 172.17.16.22.

**Comment by wimpers** [comment]
When did you first notice this? # backends? # ASDs?

**Comment by jeroenmaelbrancke** [comment]
On the nuvolat setup with +500 asds spread around 8 backends.

**Comment by khenderick** [comment]
The issue is more about the 60+ storagenodes in combination with near real-time status fields.

**Comment by khenderick** [comment]
Fixed by
* #1652, packaged in openvstorage-2.9.5
* openvstorage/framework-alba-plugin#412, packaged in openvstorage-backend-1.9.1

**Comment by khenderick** [comment]
Let's leave it on milestone `H` anyway, I have no idea when this "urgent" fix has to be released.
