### ISSUE TITLE
Scrubber should be able to work with 2 scrub disks

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1654]
This is a continuation from https://github.com/openvstorage/framework/issues/1624

In a setup where dedicated scrub nodes are used and can run multiple scrub jobs simultaneously it would make sense that we can use multiple devices(read: allow for multiple roles to be assigned and used).

**Comment by khenderick** [comment]
Currently:
* Per storagerouter/disk there's one proxy and multiple threads scrubbing using the same proxy.

Do we want:
* Per scrubdisk a separate proxy and multiple scrubbing threads per proxy
* Per storagerouter one proxy and then multiple scrubbing threads that use all different disks but the same proxy

**Comment by khenderick** [comment]
After discussions with @wimpers and @saelbrec: One proxy per stack. A stack is a combination of storagerouter/disk/vpool. In that stack, we have up to 20 threads.

**Comment by khenderick** [comment]
Fixed by #1695, packaged in openvstorage-2.9.6-dev.1498830540.4e84e0d

**Comment by JeffreyDevloo** [comment]
Packaged in openvstorage_2.9.6-1_amd64.deb
