### ISSUE TITLE
Wrong config for "alba_connection_rora_manifest_cache_capacity" in volumedriver json

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1666]
This value is currently set to '17179869184', which seems to be the manifest_cache_capacity found in ovs/lib/storagerouter.py that is used for the 'fragment_cache and block_cache manifest_cache_capacity' as well as the 'alba_connection_rora_manifest_cache_capacity'

But there is a difference:
in the proxy, it's a size in bytes (sum of the sizes of the serialized entries), while in the C++ client, it's in number of entries (as the manifests are kept inflated and not serialized).

Which currently leads to the volumedriver using too much memory.

Yet to be seen what the most correct value is.

**Comment by saelbrec** [comment]
Keeping the memory consumption under control gets precedence over the amount of data referenced by cached manifests.
In other words, the number of cached entries will be kept fixed when the SCO size or other parameters change.

The FWK can always configure:
'alba_connection_rora_manifest_cache_capacity' = 5000

**Comment by khenderick** [comment]
Fixed by #1691, packaged in openvstorage-2.9.6-dev.1498634424.750c160

**Comment by JeffreyDevloo** [comment]
Packaged in openvstorage_2.9.6-1_amd64.deb
