### ISSUE TITLE
ovs-workers/support-agent/scheduled-tasks standard/default log level is debug

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1684]
Why are the loglevels of the ovs-workers/support-agent/scheduled-tasks debug?
Can you please change this to info when you release the package?

**Comment by khenderick** [comment]
Fixed by #1689, packaged in openvstorage-2.9.6-dev.1498565550.85b0437

**Comment by khenderick** [comment]
You can add a `"level": "INFO"` entry to the json contents of `/ovs/framework/logging`. If you change the value, you need to restart the services for the new level to take effect.

**Comment by khenderick** [comment]
The default is still debug; it's still handy to have debug statements available from our perspective. If you disagree, feel free to update the value on installation.

**Comment by wimpers** [comment]
I think the default way should be what we want to use in production (I'm pretty sure this isn't debug) is set as default. I believe we have had this conversation before (see https://github.com/openvstorage/framework/issues/1234  https://github.com/openvstorage/framework/issues/1260 ) where the framework had to overwrite defaults of other teams.

**Comment by khenderick** [comment]
In that case, let's set it to `info`.

**Comment by khenderick** [comment]
Default level now at `INFO` via #1690, packaged in openvstorage-2.9.6-dev.1498572165.4f6709f

As a remark; if creating a ticket and providing logs, please include debug statements.

**Comment by JeffreyDevloo** [comment]
Packaged in: openvstorage_2.9.6-1_amd64.deb
