### ISSUE TITLE
make it easy to change the loglevel for ovs-workers/support-agent/scheduled-tasks

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1685]
Can you make it easier to change the loglevel of all the ovs-workers/support-agent/scheduled-tasks with one config?
Some key in the config arakoon?

At this moment we need to change manually the level in /opt/OpenvStorage/ovs/log/log_handler.py.

**Comment by khenderick** [comment]
Resolved via #1684.

**Comment by JeffreyDevloo** [comment]
Packaged in: openvstorage_2.9.6-1_amd64.deb
