### ISSUE TITLE
arakoon: prefer copy-db-to-head over (local-)collapse when possible

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework#1688]
@dejonghb noticed on his environment that local collapse (scheduled at 10 past every even hour) results in a temporary performance drop. Doing copy-db-to-head instead however appears to have much less performance impact.

This can actually be expected: copy-db-to-head will make 1 copy of the database, and then throw away a bunch of tlogs. local-collapse on the other hand will make a copy of the database, then replay the tlogs, and finally also throw away no longer need tlogs.
From this it's clear that copy-db-to-head is more efficient and thus preferred.

Copy-db-to-head can however only be done on slave nodes. So for single node clusters you'll still need to collapse, while for multi node clusters you can first execute copy-db-to-head on the slaves, then do a drop master so you can do the copy-db-to-head on the (former) master of the cluster too.

**Comment by toolslive** [comment]
You can also consider to do an `optimize` before you do the `copy-db-to-head`. This `optimize` can be called with a different frequency (as it's not always that useful)

**Comment by wimpers** [comment]
See operations script as doing it for nsm isn't always  a good thing so only do it for abm|config|voldrv|ovsdb .

**Comment by wimpers** [comment]
Closing this one down as won't fix as once we have Arakoon on RocksDB. copy-db-to-head no longer makes any sense.
