### ISSUE TITLE
Add filter in the GUI

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1700]
On the nuvolat setup it is quite hard to search (through the GUI) for a vdisk as there are +1000 vdisks already on that environment.

It can come in handy to create sort of filter on the vdisks tab. Examples:
* search on guid
* search on volume id
* search on name
* list of vdisks on certain storagerouter and vpool

**Comment by wimpers** [comment]
@khenderick might  be able to give some pointers as he worked upon this long time ago see http://jira.cloudfounders.com/browse/OVS-4313

One item which might be worthwhile to pick up is to introduce the sorting on more fields see http://jira.cloudfounders.com/browse/OVS-4317

**Comment by khenderick** [comment]
@wimpers, sorting is already supported for a long time and it's just a matter of defining on which field we do want to allow users to sort (e.g. sorting on a dynamic property is quite costly and we'd rather not do that). So far, we just never got to making a decision on that.

Searching was never implemented so that's something we need to build from scratch.

**Comment by wimpers** [comment]
Also requested by GIG

**Comment by wimpers** [comment]
To be discussed:
What do we want exactly?
server client?
Timing?

**Comment by wimpers** [comment]
https://docs.google.com/document/d/11xzRi239QdhlpEwamGEAknYyMgRPro4VL-GtuhswNmg

**Comment by JeffreyDevloo** [comment]
### Changes
API side changes:
https://github.com/openvstorage/framework/pull/1882

### Phase 2
- Enable filtering on properties of a relation
- Enable filtering on a subset of a dict property (like iops)
- Enable conversion of MiB and GiB to numeric values

**Comment by wimpers** [comment]
Phase 2 will be covered in https://github.com/openvstorage/framework/issues/1883

**Comment by wimpers** [comment]
@JeffreyDevloo can you investigate the performance impact of the implementation on the DAL

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
