### ISSUE TITLE
cannot do anything after initialize disk

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework#1703]
Hi all.

After i create backend, router for performance nodes.
I add disk to capacity nodes, after initialize i cannot claim disk or remove disk.

![selection_068](https://user-images.githubusercontent.com/5550425/28050135-f2c8e652-6625-11e7-83d6-8215b51cc2fc.png)

This all my backend.
![selection_069](https://user-images.githubusercontent.com/5550425/28050164-2c27a442-6626-11e7-8714-77bba6583d60.png)

what i wrong?

Thanks.
Hoan

**Comment by wimpers** [comment]
Hi @hoanhdo 

is this still an issue? Can you click the icon next to that green one?
is this a fresh install?

**Comment by hoannv46** [comment]
@wimpers 
I must remove other backends. After that backend configure is right ( disk  init, not claim)
No, i can't click this icon.
This is fresh install.

I think ít happen when i execute claim all disk simultaneously.

**Comment by wimpers** [comment]
@hoanhdo

I believe the status of the ASD is `Unknown/external`. Can you check the logs to see if the initialize went ok? Is the ASD mounted?

**Comment by JeffreyDevloo** [comment]
Hi Hoanhdo

I suspect that there was an error while initializing your disks. 
Do you still have the logs on these nodes? I would check the asd-manager log (journalctl -u asd-manager) on your asd-nodes (being 10.5.8.24, 30, 31, 36) and also the workers logs (journalctl -u ovs-workers) on your storage nodes

**Comment by hoannv46** [comment]
@JeffreyDevloo 

I reinstall this cluster this is my cluster.

I have an backend error by these step.

- create 2 backend dc-1-performance and dc-2-performance.

On dc-1-performance  backend.
- initialize all disk on ovs-r1-performance-1 and ovs-r1-performance-2
- claim all disk on ovs-r1-performance-1 and ovs-r1-performance-2.

On dc-2-performance  backend.
- initialize all disk on ovs-r2-performance-2 .
- I cann't claim disk but it display (seem it claimed)

![selection_077](https://user-images.githubusercontent.com/5550425/30257619-9ccaedf2-96dd-11e7-88bf-53befe4688fa.png)

This is log 3 server  ovs-r1-performance-1, ovs-r1-performance-2 ,ovs-r2-performance-2
[ovs_log.zip](https://github.com/openvstorage/framework/files/1291282/ovs_log.zip)

Thanks.

Hoan

**Comment by JeffreyDevloo** [comment]
Hi Hoan
I suspect that the node, that is facing the issues, has issues with multicasting.
You could verify this by manually starting the maintenance on ovs-r2-performance2.
Starting the maintenance manually can be done like so:
- Fetch the maintenance from another storagerouter (ps -aux | grep maintenance)
![image](https://user-images.githubusercontent.com/17570109/30273379-0a1806a4-96f9-11e7-998f-2b9e3712fa03.png)
- Copy the process settings (in the picture above this will be: /usr/bin/alba maintenance --config arakoon://config/ovs/alba/backends/7a44aaa0-c160-466f-9fdf-85a81fb248e2/maintenance/config?ini=%2Fopt%2Fasd-manager%2Fconfig%2Farakoon_cacc.ini
- Run maintenance on ovs-r2-performance (simply paste the command into the terminal)

If you can't claim them after a couple of minutes, something else is up.

**Comment by hoannv46** [comment]
@JeffreyDevloo 
I compared alba process in 3 node, 
![selection_079](https://user-images.githubusercontent.com/5550425/30305049-fc36062e-979a-11e7-8101-52160f54678a.png)
![selection_080](https://user-images.githubusercontent.com/5550425/30305050-fc3aeeb4-979a-11e7-840e-ebacbb24c64c.png)
![selection_082](https://user-images.githubusercontent.com/5550425/30305051-fc3ceafc-979a-11e7-9d36-a5ade3838c7f.png)

Then i run alba process on ovs-r1-performance-2 and ovs-r2-performance-2. 
It result.

![selection_083](https://user-images.githubusercontent.com/5550425/30305170-94e833a6-979b-11e7-9a7e-033838be3929.png)
![selection_084](https://user-images.githubusercontent.com/5550425/30305172-94e98d50-979b-11e7-8468-8642e5b662af.png)
![selection_085](https://user-images.githubusercontent.com/5550425/30305171-94e98918-979b-11e7-9323-253b6bb02b29.png)

Them same maintenance process on 3 node.
GUI:
![selection_086](https://user-images.githubusercontent.com/5550425/30305208-d4622d34-979b-11e7-8d18-a01b4a0c97a7.png)

It works. So cool.

How i can run process on backgroup like other maintenance process.?
Is this a bug or my wrong operation.

Thanks.

**Comment by JeffreyDevloo** [comment]
The framework will deploy a maintenance agent once a backend has been made on a node. Afterwards, each time an asd has been claimed, a maintenance will be running on that node.
Now that you have claimed the asds on ovs-r2-performance-2, the maintenance agent will be running there and you do not need manually intervene anymore.

It is not a bug, it more of an issue with our multi casting decision. (Will be removed in a future release).

**Comment by JeffreyDevloo** [comment]
Closing as the ticket was resolved.
