### ISSUE TITLE
Make it possible to assign externally managed Arakoon clusters to dedicated Backend

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1711]
Our NSM checkup currently claims any Arakoon cluster which has the 'in_use' flag set to False when a Backend needs more NSM clusters.
This behavior is not optimal and should be improved

Possible solutions:
1) We could add a flag in the Arakoon cluster's metadata called: 'backend_name'. This flag could then be used to check for which backend the cluster was created. Our NSM checkup should then check on the name flag and act accordingly.
This could prevent that certain unused arakoon clusters, which have been deployed on 5 nodes, are registered to an ABM cluster only deployed on 3 nodes.
2) Do nothing at all when NSM checkup notices all NSM clusters being overloaded, just log a warning for monitoring to react upon.

Downsides for 1st option:
* What to do when no 'name' flag is provided? Always claim or log warning?
* What to do when unknown backend name is provided?

Downsides for 2nd option:
* We need for every NSM cluster a service in our model. This would have to become a scheduled task to keep these services in sync.

**Comment by JeffreyDevloo** [comment]
Shouldn't we just start moving away from internal and external arakoons and just leave it up to customer where he wants his arakoons?

**Comment by kvanhijf** [comment]
Yes we definitely should, but that would be a whole lot more work
This is an enhancement which shouldn't take too much time and allows our OPS boys to have more control

PS: created a ticket (FR) for it: see https://github.com/openvstorage/framework/issues/1712

**Comment by wimpers** [comment]
* Implement option 2.
* extend https://github.com/openvstorage/framework-alba-plugin/issues/284  so it also registers the services in the model.

**Comment by kvanhijf** [comment]
This issue was moved to openvstorage/framework-alba-plugin#490

**Comment by kvanhijf** [comment]
Reopened issue because the fix also includes changes in this repo

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1797 --> openvstorage-2.11.0-dev.1506520895.af0293a
https://github.com/openvstorage/framework-alba-plugin/pull/491 --> openvstorage-backend-1.11.0-dev.1506522259.f180102

**Comment by kvanhijf** [comment]
Version bump of the API from 9 to 10 was necessary for this. Because 'amount' in 'expand_nsm_clusters' ('alba/backends') was obsoleted

**Comment by kvanhijf** [comment]
Included in release https://github.com/openvstorage/framework/releases/tag/2.10.1
