### ISSUE TITLE
Arakoon deployment configurable via GUI/framework

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1712]
The use of external Arakoons has cost OPS and framework team a lot of work and has lots of disadvantages
The user (customer / OPS / ...) should be able to determine where each and every Arakoon cluster should be deployed by using the GUI and/or the API calls delivered by the framework team

**Comment by wimpers** [comment]
@saelbrec please discuss with Kevin

@kvanhijf  why is this critical?

**Comment by wimpers** [comment]
We are moving away to external arakoons.
