### ISSUE TITLE
Add ability to search for a vdisk based on the name and vpool

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#1715]
Currently we only have a limited number of ways to search for vdisks. An awesome, additional way would be to be able to search with the name and vpool of a vdisk. Now we have to loop over all vdisks and compare the name to find the matching disk.

**Comment by JeffreyDevloo** [comment]
We can introduce such a call but the vdisk name is not guaranteed to be unique. You can have multiple vdisks called test whereas one test is located in /mnt/myvpool/test.raw and the other in /mnt/myvpool/testdir/test.raw
The new call would return all found entries with their device names and leave it up to the user to further query (same query you can do at the moment)?

**Comment by wimpers** [comment]
I believe this duplicates https://github.com/openvstorage/framework/issues/1700 hence closing. If I would be mistaken, please re-open.

**Comment by JeffreyDevloo** [comment]
Not a duplicate really. I think it was ment more for the vdisklist itself.

**Comment by wimpers** [comment]
@JeffreyDevloo  which vdisklist command are you exactly talking about? The one in the DAL I assume as it isn't the GUI/API one?
