### ISSUE TITLE
Fix framework logging

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1719]
The logging module for python is completely misconfigured in the framework
Normal workflow should be that each process instantiates its own logger. Then the process itself should be responsible to add a handler to it (Which in most cases should be our LogHandler module) and then it can log. Depending on the handler and the configurations of the handler, it then logs to console, file or redis

A good example of bad configuration is present in our extensions. eg file_mutex
This extension creates a logger instance ( `logging.getLogger(__name__)` ), but it doesn't add a handler, so python does not know where to put the logs and falls back to the default

Our entire framework and related repos should be cleaned up and optimize the logging behavior

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/framework/pull/1718

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1737 --> openvstorage-2.10.0-dev.1504526476.8d0cc72
https://github.com/openvstorage/iscsi-manager/pull/20 --> iscsi-manager-0.2.0-dev.1504522775.23bcb15
https://github.com/openvstorage/alba-asdmanager/pull/273 --> openvstorage-sdm-1.10.0-dev.1504523753.9071916
https://github.com/openvstorage/framework-extensions/pull/21 --> openvstorage-extensions-0.2.0-dev.1504523843.ec3d7d6
https://github.com/openvstorage/framework-iscsi-plugin/pull/15 --> openvstorage-iscsi-plugin-0.2.0-dev.1504523809.5dd1d3c
https://github.com/openvstorage/framework-alba-plugin/pull/455 --> openvstorage-backend-1.10.0-dev.1504527208.d19daf1
