### ISSUE TITLE
cannot start ovs-watcher-volumedriver after start

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework#1720]
Hi all.

My dc lost power, all server shutdown.
I start all server but some service cannot start.
this is log ovs-watcher-volumedriver process.
> Aug 14 11:12:54 ovs-r1-controller python[10122]: 2017-08-14 11:12:54 37000 +0700 - ovs-r1-controller - 10122/140423074846464 - arakoon_client/pyrakoon - 164 - ERROR - [Errno 111] Connection refused: Unable to connect to ('192.168.54.23', 26428)
Aug 14 11:12:54 ovs-r1-controller python[10122]: Traceback (most recent call last):
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1262, in connect
Aug 14 11:12:54 ovs-r1-controller python[10122]:     self._socket = socket.create_connection(self._address, self._timeout)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
Aug 14 11:12:54 ovs-r1-controller python[10122]:     raise err
Aug 14 11:12:54 ovs-r1-controller python[10122]: error: [Errno 111] Connection refused
Aug 14 11:12:54 ovs-r1-controller python[10122]: 2017-08-14 11:12:54 37000 +0700 - ovs-r1-controller - 10122/140423074846464 - arakoon_client/pyrakoon - 165 - ERROR - [Errno 111] Connection refused: Unable to connect to ('192.168.54.23', 26428)
Aug 14 11:12:54 ovs-r1-controller python[10122]: Traceback (most recent call last):
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1262, in connect
Aug 14 11:12:54 ovs-r1-controller python[10122]:     self._socket = socket.create_connection(self._address, self._timeout)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
Aug 14 11:12:54 ovs-r1-controller python[10122]:     raise err
Aug 14 11:12:54 ovs-r1-controller python[10122]: error: [Errno 111] Connection refused
Aug 14 11:12:54 ovs-r1-controller python[10122]: 2017-08-14 11:12:54 37100 +0700 - ovs-r1-controller - 10122/140423074846464 - arakoon_client/pyrakoon - 166 - ERROR - No connection available to node at '192.168.54.23:26428' : Message exchange with node oKRzbz2bGb3OaGQr failed
Aug 14 11:12:54 ovs-r1-controller python[10122]: Traceback (most recent call last):
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1138, in _send_message
Aug 14 11:12:54 ovs-r1-controller python[10122]:     connection.send(data)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1303, in send
Aug 14 11:12:54 ovs-r1-controller python[10122]:     raise ArakoonNotConnected(self._address)
Aug 14 11:12:54 ovs-r1-controller python[10122]: ArakoonNotConnected: No connection available to node at '192.168.54.23:26428'
Aug 14 11:12:54 ovs-r1-controller python[10122]: 2017-08-14 11:12:54 37100 +0700 - ovs-r1-controller - 10122/140423074846464 - arakoon_client/pyrakoon - 167 - ERROR - No connection available to node at '192.168.54.23:26428': Unable to query node "oKRzbz2bGb3OaGQr" to look up master
Aug 14 11:12:54 ovs-r1-controller python[10122]: Traceback (most recent call last):
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1179, in determine_master
Aug 14 11:12:54 ovs-r1-controller python[10122]:     self.master_id = self._get_master_id_from_node(node)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1207, in _get_master_id_from_node
Aug 14 11:12:54 ovs-r1-controller python[10122]:     connection = self._send_message(node_id, data)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1138, in _send_message
Aug 14 11:12:54 ovs-r1-controller python[10122]:     connection.send(data)
Aug 14 11:12:54 ovs-r1-controller python[10122]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1303, in send
Aug 14 11:12:54 ovs-r1-controller python[10122]:     raise ArakoonNotConnected(self._address)
Aug 14 11:12:54 ovs-r1-controller python[10122]: ArakoonNotConnected: No connection available to node at '192.168.54.23:26428'
Aug 14 11:12:54 ovs-r1-controller python[10122]: 2017-08-14 11:12:54 37100 +0700 - ovs-r1-controller - 10122/140423074846464 - arakoon_client/pyrakoon - 168 - ERROR - Unable to determine master node

I see port 26408 is arakoon of volumedriver.
This is log start volume driver arakkon (ovs-arakoon-voldrv)

> controller - 24227/0000 - arakoon - 0 - info - --- NODE STARTED ---
controller - 24227/0000 - arakoon - 1 - info - git_revision: tags/1.9.17-0-g1a5da78
controller - 24227/0000 - arakoon - 2 - info - compile_time: 20/04/2017 12:45:12 UTC
controller - 24227/0000 - arakoon - 3 - info - version: 1.9.17
controller - 24227/0000 - arakoon - 4 - info - NOFILE: 8192
controller - 24227/0000 - arakoon - 5 - info - cluster_cfg={ cfgs = [{ node_name = "MgilN7oBbksHsEkE"; ips = ["192.168.54.21"]; client_port = 26428; messaging_port = 26429; home = "/mn
ue; node_tls = None; collapse_slowdown = None; head_copy_throttling = 0. }]; log_cfgs = []; batched_transaction_cfgs = []; _master = Elected; _lease_period = 10; cluster_id = "voldrv";
controller - 24227/0000 - arakoon - 6 - info - Batched_store.max_entries = 100
controller - 24227/0000 - arakoon - 7 - info - Batched_store.max_size = 100000
controller - 24227/0000 - arakoon - 8 - info - autofix:true
controller - 24227/0000 - arakoon - 9 - info - Cluster not part of nursery.
controller - 24227/0000 - arakoon - 10 - info - cfg = { node_name = "MgilN7oBbksHsEkE"; ips = ["192.168.54.21"]; client_port = 26428; messaging_port = 26429; home = "/mnt/hdd2/arakoon/
controller - 24227/0000 - arakoon - 11 - info - other: oKRzbz2bGb3OaGQr
controller - 24227/0000 - arakoon - 12 - info - other: 0vsJSdtnXhwwaa53
controller - 24227/0000 - arakoon - 13 - info - quorum_function gives 2 for 3
controller - 24227/0000 - arakoon - 14 - info - DAEMONIZATION=false
controller - 24227/0000 - arakoon - 15 - info - open_tlog_collection_and_store ~autofix:true
controller - 24227/0000 - arakoon - 16 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/db/touch-24227"
controller - 24227/0000 - arakoon - 17 - info - Unlink of "/mnt/hdd2/arakoon/voldrv/db/touch-24227" failed with ENOENT
controller - 24227/0000 - arakoon - 18 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/db/touch-24227"
controller - 24227/0000 - arakoon - 19 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227"
controller - 24227/0000 - arakoon - 20 - info - Unlink of "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227" failed with ENOENT
controller - 24227/0000 - arakoon - 21 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227"
controller - 24227/0000 - arakoon - 22 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227"
controller - 24227/0000 - arakoon - 23 - info - Unlink of "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227" failed with ENOENT
controller - 24227/0000 - arakoon - 24 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227"
controller - 24227/0000 - arakoon - 25 - info - Unlinking "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227"
controller - 24227/0000 - arakoon - 26 - info - Unlink of "/mnt/hdd2/arakoon/voldrv/tlogs/touch-24227" failed with ENOENT

Thanks.

**Comment by JeffreyDevloo** [comment]
Hello Hoanhdo

Could you log the output of ovs monitor services? I have the suspicion that certain arakoon nodes are unable to restart.

**Comment by hoannv46** [comment]
@JeffreyDevloo 

This is my ovs monitor services

> OVS running processes
> =====================
> 
> ovs-albaproxy_vpool-global-capacity_0       active  6052
> ovs-albaproxy_vpool-global-capacity_1       active  6043
> ovs-albaproxy_vpool-global-perf_0           active  6014
> ovs-albaproxy_vpool-global-perf_1           active  6030
> ovs-albaproxy_vpool-local-capa-1_0          active  6031
> ovs-albaproxy_vpool-local-capa-1_1          active  6048
> ovs-albaproxy_vpool-local-perf-1_0          active  6029
> ovs-albaproxy_vpool-local-perf-1_1          active  6046
> ovs-arakoon-config                          active  4973
> ovs-arakoon-ovsdb                           active  26928
> ovs-scheduled-tasks                         active  2636
> ovs-support-agent                           active  3236
> ovs-volumerouter-consumer                   active  13699
> ovs-watcher-config                          active  6232
> ovs-watcher-framework                       active  2620
> ovs-webapp-api                              active  2633
> ovs-workers                                 active  2844


> OVS non-running processes
> =========================
> 
> ovs-arakoon-global-multi-dc-abm             inactive
> ovs-arakoon-global-multi-dc-capacity-abm    inactive
> ovs-arakoon-global-multi-dc-capacity-nsm_0  inactive
> ovs-arakoon-global-multi-dc-nsm_0           inactive
> ovs-arakoon-local-dc-1-capacity-abm         inactive
> ovs-arakoon-local-dc-1-capacity-nsm_0       inactive
> ovs-arakoon-local-dc-1-perf-abm             inactive
> ovs-arakoon-local-dc-1-perf-nsm_0           inactive
> ovs-arakoon-local-dc-2-capa-abm             inactive
> ovs-arakoon-local-dc-2-capa-nsm_0           inactive
> ovs-arakoon-local-dc-2-perf-abm             inactive
> ovs-arakoon-local-dc-2-perf-nsm_0           inactive
> ovs-arakoon-voldrv                          activating
> ovs-dtl_vpool-global-capacity               inactive
> ovs-dtl_vpool-global-perf                   inactive
> ovs-dtl_vpool-local-capa-1                  inactive
> ovs-dtl_vpool-local-perf-1                  inactive
> ovs-volumedriver_vpool-global-capacity      inactive
> ovs-volumedriver_vpool-global-perf          inactive
> ovs-volumedriver_vpool-local-capa-1         inactive
> ovs-volumedriver_vpool-local-perf-1         inactive
> ovs-watcher-volumedriver                    activating
>

**Comment by JeffreyDevloo** [comment]
The volumedriver needs the information which is stored within the Arakoons. 

Now we should figure out why these Arakoons refuse to start. Could you provide me with some logging from these Arakoons that are unactive?

**Comment by hoannv46** [comment]
@JeffreyDevloo 

this is my log when run start arakoon manually.
https://github.com/openvstorage/arakoon/issues/196

**Comment by wimpers** [comment]
Nothing to be fixed on the framework side as Arakoon needs to be up.
