### ISSUE TITLE
backend install loop , cannot create more backend

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework#1721]
Hi all.

I install openstorage on 2 dc.

I create many backends, sometime i cannot create more backend because one backend installing loop.
![selection_074](https://user-images.githubusercontent.com/5550425/29306805-615ec280-81c9-11e7-94c5-ef2a9b887924.png)

backend global-capacity in installing state. But it  not in ovs monitor services  in openvstorage master node.

![selection_075](https://user-images.githubusercontent.com/5550425/29306888-ae9117ec-81c9-11e7-856c-7a52d95d3ebe.png)

Now, i cannot create more backend.

Thanks.

**Comment by hoannv46** [comment]
I find in ovs-r1-controller node still some config exist 

root@ovs-r1-controller:/# find -name '*global-capacity*'
./sys/fs/cgroup/devices/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./sys/fs/cgroup/devices/system.slice/ovs-arakoon-global-capacity-abm.service
./sys/fs/cgroup/memory/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./sys/fs/cgroup/memory/system.slice/ovs-arakoon-global-capacity-abm.service
./sys/fs/cgroup/cpu,cpuacct/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./sys/fs/cgroup/cpu,cpuacct/system.slice/ovs-arakoon-global-capacity-abm.service
./sys/fs/cgroup/pids/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./sys/fs/cgroup/pids/system.slice/ovs-arakoon-global-capacity-abm.service
./sys/fs/cgroup/blkio/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./sys/fs/cgroup/blkio/system.slice/ovs-arakoon-global-capacity-abm.service
./mnt/hdd1/arakoon/global-capacity-abm
./mnt/hdd1/arakoon/global-capacity-nsm_0
./mnt/vpool-global-capacity
./var/lib/lxcfs/cgroup/devices/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./var/lib/lxcfs/cgroup/devices/system.slice/ovs-arakoon-global-capacity-abm.service
./var/lib/lxcfs/cgroup/memory/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./var/lib/lxcfs/cgroup/memory/system.slice/ovs-arakoon-global-capacity-abm.service
./var/lib/lxcfs/cgroup/cpu,cpuacct/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./var/lib/lxcfs/cgroup/cpu,cpuacct/system.slice/ovs-arakoon-global-capacity-abm.service
./var/lib/lxcfs/cgroup/pids/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./var/lib/lxcfs/cgroup/pids/system.slice/ovs-arakoon-global-capacity-abm.service
./var/lib/lxcfs/cgroup/blkio/system.slice/ovs-arakoon-global-capacity-nsm_0.service
./var/lib/lxcfs/cgroup/blkio/system.slice/ovs-arakoon-global-capacity-abm.service

**Comment by kvanhijf** [comment]
Can you look through the 'ovs-workers.service' log and search for 'global-capacity' and see if you can find anything related please. The logging regarding this specific backend can occur on any node in your cluster running the 'ovs-workers.service'

**Comment by kvanhijf** [comment]
Another thing i just thought of. Did you create these backends simultaneously? Cause in older versions this is not supported.
And which version are you using?

**Comment by hoannv46** [comment]
@kvanhijf 

I installed lastest stable version : fargo. I think because i don't clear 2 disk DB,TL,Srub, and Cache .
My cluster was reinstalled without clear OS.

Thanks
