### ISSUE TITLE
Update should not be able to downgrade

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1727]
Our update code is not smart enough when it comes down to comparing versions
It is possible to have it update from version 1.9 --> version 1.8 for example.
We should prevent this from happening

**Comment by wimpers** [comment]
@kvanhijf 

how can you get in this scenario? apt-get only allows to install higher package nrs (unless you force)?

**Comment by kvanhijf** [comment]
@wimpers : Its was a cosmetic matter. We sometimes witnessed this when updating from develop to experimental when not all packages had been synced to experimental yet. Then the GUI mentioned an update was available for eg: arakoon from 1.9.8 --> 1.9.3

Has been fixed anyway by https://github.com/openvstorage/framework/issues/1756
