### ISSUE TITLE
Opening remote tunnel should always be possible

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1735]
Opening remote tunnel should always be possible even in case Arakoon or RabbitMQ or the GUI is down.

As a last resort having to run a manual command or a set of command is acceptable.  In that case these need to be documented clearly.

**Comment by JeffreyDevloo** [comment]
### Changes to the support agent:
The support agent is able to run in all failure cases (Arakoon, DAL failures, RabbitMQ) and has a minimal amount of dependencies on other Framework code.

When Arakoon/DAL would be down, all user made setting can no longer be fetched and will revert to defaults. These defaults enable everything by default so support from OVS would be possible.

The only case in which the tunnel could not be opened is when the monitoring server is no longer accessible. It is still possible to open a tunnel by placing the configs manually (these would be provided by our ops) and running the SupportAgent.open_tunnel()

**Comment by wimpers** [comment]
@saelbrec 

> When Arakoon/DAL would be down, all user made setting can no longer be fetched and will revert to defaults. These defaults enable everything by default so support from OVS would be possible.

I believe this will lead to issues with compliance. Can we think of something so the default is no support and a user needs to do `something` to enable it?

**Comment by JeffreyDevloo** [comment]
Changes surrounding the support agent can be found here:
https://github.com/openvstorage/framework/blob/develop/docs/support_agent.md
Fixed by: https://github.com/openvstorage/framework/pull/1862
Packaged in: openvstorage-2.11.1-dev.1510307398.e5a5235

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
