### ISSUE TITLE
Delete snapshot(s) should wait longer when retrieving the snapshots from volumedriver

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1747]
When invalidating the 'snapshot_ids' on a vDisk, we only wait 2 seconds for the volumedriver to return
If this timeout is reached we assume the vDisk not having any snapshots. This then results in an errormessage saying 'Snapshot <id> does not belong to vDisk', which is incorrect since we just dont wait long enough

```
    def _snapshot_ids(self):
        """
        Fetches the snapshot IDs for this vDisk
        """
        if not self.volume_id or not self.vpool:
            return []

        volume_id = str(self.volume_id)
        try:
            try:
                return self.storagedriver_client.list_snapshots(volume_id, req_timeout_secs=2)
            except VolumeRestartInProgressException:
                time.sleep(0.5)
                return self.storagedriver_client.list_snapshots(volume_id, req_timeout_secs=2)
        except:
            return []
```
Above is piece of code being executed when invalidating the `snapshot_ids`

```
                    vdisk.invalidate_dynamics(['snapshot_ids'])
                    if snapshot_id not in vdisk.snapshot_ids:
                        raise RuntimeError('Snapshot {0} does not belong to vDisk {1}'.format(snapshot_id, vdisk.name))
```
Above is piece of code raising the error in case the snapshot_id is not found (in time)

**Comment by wimpers** [comment]
Can we check the logs in Nuvolat to see what the average and max values for list snapshots are?

**Comment by redlicha** [comment]
Can you please also check how many snapshots there are for these volumes by running `list_snapshots` with a bigger / no timeout.

**Comment by kvanhijf** [comment]
@wimpers : The logs have been rotated in the meantime
i tried the following, but no results
```
root@NY1SRV0024:/mnt/monitoring/rsyslog/client_logs# grep "snapshotsList took" */volumedriver_fs.sh.log | grep -v 'e-' | grep -v 'took 0.'
root@NY1SRV0024:/mnt/monitoring/rsyslog/client_logs# 
```

**Comment by kvanhijf** [comment]
@redlicha 
```
snap_amount = {}
for vd in VDiskList.get_vdisks():
    snap_amount[vd.volume_id] = len(vd.storagedriver_client.list_snapshots(str(vd.volume_id)))
max(snap_amount.values())  --> 66
```
So a maximum of 66 snapshots for a single vDisk, thats reasonable i guess

**Comment by kvanhijf** [comment]
* Timeout to retrieve snapshots has been increased from 2 to 10 seconds
* If retrieving the snapshots fails for whatever reason (timeout, ...), the error message returned by delete_snapshots will be the one the volumedriver itself throws. 

https://github.com/openvstorage/framework/pull/1790 --> openvstorage-2.10.0-dev.1506329589.863e663
