### ISSUE TITLE
GUI should not show green status and 0 size storage use if it has no clue

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1751]
The GUI incorrectly shows green status for 2 vdisks and 0 bytes of stored data:
![gui](https://user-images.githubusercontent.com/15377625/30057939-1c6d77b8-9239-11e7-9b4b-d5598ceb94e1.png)

In this case yad1 does not start (due to backward compat problem) and both disk do have stored data as can be seen once things are correct again:
![gui2](https://user-images.githubusercontent.com/15377625/30057993-567a6510-9239-11e7-8970-4766f0751715.png)

The incorrect info was displayed for quite a long time; very misleading.

**Comment by wimpers** [comment]
Status should be Unknown and Stored Data should be ´-´

**Comment by JeffreyDevloo** [comment]
Related to https://github.com/openvstorage/framework/issues/1850

**Comment by JeffreyDevloo** [comment]
Will be fixed by https://github.com/openvstorage/framework/pull/1922

**Comment by sjovdnbos** [comment]
Since #1922 is fixed, this may be fixed as well, @JeffreyDevloo ?

**Comment by JeffreyDevloo** [comment]
Fixed by #1922

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
