### ISSUE TITLE
Alba implementations are in the alba plugin but the alba proxies is hardcoded within this repo

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1758]
### Problem description
All of our effort to make the alba package optional for potentially other backends in the future are actually useless as setting up a vpool always requires alba to be there as we set up the alba proxies there and not in the alba plugin

**Comment by wimpers** [comment]
This is indeed not clean. We will tackle this when we come to the point when adding more backends. For now ALBA is mandotary.

**Comment by wimpers** [comment]
This is indeed not clean. We will tackle this when we come to the point when adding more backends. For now ALBA is mandotary.
