### ISSUE TITLE
create vpool failed on GeoScale cluster 

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework#1765]
Hi all.

ovs version : 
ii  openvstorage                         2.9.5-1                            amd64        openvStorage
ii  openvstorage-backend                 1.9.1-1                            amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.9.1-1                            amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.9.1-1                            amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.9.5-1                            amd64        openvStorage core
ii  openvstorage-webapps                 2.9.5-1                            amd64        openvStorage Web Applications
This is my cluster.

![selection_087](https://user-images.githubusercontent.com/5550425/30307226-d3ab58f6-97a6-11e7-9108-896dbf8f833e.png)

I create 3 backend  
![selection_088](https://user-images.githubusercontent.com/5550425/30307401-22a14302-97a8-11e7-85e7-fb032b264b5d.png)

I create vpool failed
![selection_089](https://user-images.githubusercontent.com/5550425/30307494-bb41a192-97a8-11e7-9b2b-3ef4eee782cb.png)

This is log openvstorage on  ovs-r1-controller 

> 2017-09-12 05:49:52 686444 +0200 - ovs-r1-controller - 17560/0x00007f6aa3efa700 - LoggerToolCut/Cluster - 000000000000004b - info - Cluster: Cluster ID voldrv, proto version 0
> 2017-09-12 05:49:52 686477 +0200 - ovs-r1-controller - 17560/0x00007f6aa3efa700 - LoggerToolCut/Cluster - 000000000000004c - info - add_node_: voldrv: adding arakoon node 0vsJSdtnXhwwaa53, host 192.168.57.21, service 26416
> 2017-09-12 05:49:52 686557 +0200 - ovs-r1-controller - 17560/0x00007f6aa3efa700 - LoggerToolCut/Cluster - 000000000000004d - info - add_node_: voldrv: adding arakoon node MgilN7oBbksHsEkE, host 192.168.54.21, service 26416
> 2017-09-12 05:49:52 686623 +0200 - ovs-r1-controller - 17560/0x00007f6aa3efa700 - LoggerToolCut/Cluster - 000000000000004e - info - add_node_: voldrv: adding arakoon node oKRzbz2bGb3OaGQr, host 192.168.54.23, service 26416
> 2017-09-12 05:49:52 688788 +0200 - ovs-r1-controller - 17560/0x00007f6aa3efa700 - LoggerToolCut/LockedArakoon - 000000000000004f - info - connect_: Arakoon configured
> 
> ==> /var/log/ovs/extensions.log <==
> 2017-09-12 10:50:02 79400 +0700 - ovs-r1-controller - 27728/139687385044736 - extensions/heartbeat - 0 - ERROR - Error clearing ARP cache
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r2-controller'' returned non-zero exit status 255
> 

This is log openvstorage on  ovs-r2-controller 
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r1-performance-1'' returned non-zero exit status
>  255
> 2017-09-12 10:49:02 53700 +0700 - ovs-r2-controller - 3934/140409339483904 - extensions/heartbeat -
>  0 - ERROR - Error clearing ARP cache
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r1-performance-1'' returned non-zero exit status
>  255
> 2017-09-12 10:49:02 55200 +0700 - ovs-r2-controller - 3934/140409339483904 - extensions/heartbeat -
>  1 - ERROR - Error clearing ARP cache
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r1-controller'' returned non-zero exit status 25
> 5
> 2017-09-12 10:50:02 67400 +0700 - ovs-r2-controller - 8759/140235641239296 - extensions/heartbeat -
>  0 - ERROR - Error clearing ARP cache
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r1-controller'' returned non-zero exit status 25
> 5
> 2017-09-12 10:50:02 69000 +0700 - ovs-r2-controller - 8759/140235641239296 - extensions/heartbeat -
>  1 - ERROR - Error clearing ARP cache
> Traceback (most recent call last):
>   File "/opt/OpenvStorage/ovs/extensions/generic/heartbeat.py", line 62, in pulse
>     check_output("/usr/sbin/arp -d '{0}'".format(node.name.replace(r"'", r"'\''")), shell=True)
>   File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> CalledProcessError: Command '/usr/sbin/arp -d 'ovs-r1-performance-2'' returned non-zero exit status
>  255
> 

I can ssh without password from one node to other nodes.

Thanks

**Comment by JeffreyDevloo** [comment]
Hi Hoanhdo

Could you provide us the workers logs from all three nodes so we can deduce what went wrong here? The ARP command could be in it but it could also be misleading us.
You can fetch the logs by doing: journalctl -u ovs-workers.service and look for the add_vpool job

**Comment by hoannv46** [comment]
Hi JeffreyDevloo 

 This is log woker on  ovs-r1-controller  node add_vpool job
[log_worker.zip](https://github.com/openvstorage/framework/files/1295164/log_worker.zip)

This is log ovs-r1-controller'
[log_ovs_worker_ovs-r1-controller.zip](https://github.com/openvstorage/framework/files/1295196/log_ovs_worker_ovs-r1-controller.zip)

This is log ovs-r2-controller'
[log_ovs_worker_ovs-r2-controller.zip](https://github.com/openvstorage/framework/files/1295197/log_ovs_worker_ovs-r2-controller.zip)

**Comment by JeffreyDevloo** [comment]
Hi Hoanhdo

Your loggin shows a lot of entries containing `Waiting for the StorageDriver to start up for vPool test-vpool-1 on StorageRouter ovs-r1-controller ...`
This could mean that the service can not be started.
Could you run ovs-monitor services on all those nodes? This will show the services that are not running.

If there are services that are non-running, please provide me with some logs so I can assist you further

**Comment by hoannv46** [comment]
Hi JeffreyDevloo.

My cluster has 3 master nodes.
ovs monitor services : ovs-r1-controller

OVS running processes
=====================

> ovs-albaproxy_test-vpool-1_0          active  8610
> ovs-albaproxy_test-vpool-1_1          active  8838
> ovs-albaproxy_test-vpool-dc-1_0       active  9711
> ovs-albaproxy_test-vpool-dc-1_1       active  9891
> ovs-albaproxy_vpool-dc-1_0            active  8511
> ovs-albaproxy_vpool-dc-1_1            active  8973
> ovs-albaproxy_vpool-global_0          active  9273
> ovs-albaproxy_vpool-global_1          active  9715
> ovs-arakoon-config                    active  7580
> ovs-arakoon-dc-1-performance-abm      active  5722
> ovs-arakoon-dc-1-performance-nsm_0    active  5798
> ovs-arakoon-dc-2-performance-abm      active  5939
> ovs-arakoon-dc-2-performance-nsm_0    active  6014
> ovs-arakoon-global-performance-abm    active  6164
> ovs-arakoon-global-performance-nsm_0  active  6342
> ovs-arakoon-ovsdb                     active  7878
> ovs-arakoon-voldrv                    active  8213
> ovs-dtl_test-vpool-1                  active  8323
> ovs-dtl_test-vpool-dc-1               active  9551
> ovs-dtl_vpool-dc-1                    active  19964
> ovs-dtl_vpool-global                  active  12401
> ovs-scheduled-tasks                   active  17512
> ovs-support-agent                     active  8306
> ovs-volumedriver_test-vpool-1         active  8995
> ovs-volumedriver_test-vpool-dc-1      active  10109
> ovs-volumedriver_vpool-dc-1           active  20602
> ovs-volumedriver_vpool-global         active  12929
> ovs-volumerouter-consumer             active  25450
> ovs-watcher-config                    active  6815
> ovs-watcher-framework                 active  17508
> ovs-watcher-volumedriver              active  12248
> ovs-webapp-api                        active  17510
> ovs-workers                           active  23104
> 
> 
> OVS non-running processes
> =========================
> 
> 

ovs monitor services : ovs-r2-controller

> OVS running processes
> =====================
> 
> ovs-albaproxy_test-vpool-2_0          active  31236
> ovs-albaproxy_test-vpool-2_1          active  31391
> ovs-albaproxy_test-vpool-3_0          active  8847
> ovs-albaproxy_test-vpool-3_1          active  8587
> ovs-albaproxy_vpool-dc-2_0            active  13537
> ovs-albaproxy_vpool-dc-2_1            active  13366
> ovs-arakoon-config                    active  3268
> ovs-arakoon-dc-1-performance-abm      active  1569
> ovs-arakoon-dc-1-performance-nsm_0    active  1635
> ovs-arakoon-dc-2-performance-abm      active  1736
> ovs-arakoon-dc-2-performance-nsm_0    active  1841
> ovs-arakoon-global-performance-abm    active  1916
> ovs-arakoon-global-performance-nsm_0  active  2033
> ovs-arakoon-ovsdb                     active  3476
> ovs-arakoon-voldrv                    active  3729
> ovs-dtl_test-vpool-2                  active  31045
> ovs-dtl_test-vpool-3                  active  8382
> ovs-dtl_vpool-dc-2                    active  13154
> ovs-scheduled-tasks                   active  16777
> ovs-support-agent                     active  3835
> ovs-volumedriver_test-vpool-2         active  31606
> ovs-volumedriver_test-vpool-3         active  9068
> ovs-volumedriver_vpool-dc-2           active  13684
> ovs-volumerouter-consumer             active  16779
> ovs-watcher-config                    active  28527
> ovs-watcher-framework                 active  16774
> ovs-watcher-volumedriver              active  12975
> ovs-webapp-api                        active  16781
> ovs-workers                           active  22423
> 
> 
> OVS non-running processes
> =========================
> 
> 

ovs monitor services : ovs-r1-performance-1

> OVS running processes
> =====================
> 
> ovs-arakoon-config                    active  5399
> ovs-arakoon-dc-1-performance-abm      active  3642
> ovs-arakoon-dc-1-performance-nsm_0    active  3754
> ovs-arakoon-dc-2-performance-abm      active  3825
> ovs-arakoon-dc-2-performance-nsm_0    active  3939
> ovs-arakoon-global-performance-abm    active  4005
> ovs-arakoon-global-performance-nsm_0  active  4159
> ovs-arakoon-ovsdb                     active  5623
> ovs-arakoon-voldrv                    active  5852
> ovs-scheduled-tasks                   active  26231
> ovs-support-agent                     active  5967
> ovs-volumerouter-consumer             active  21645
> ovs-watcher-config                    active  20637
> ovs-watcher-framework                 active  26226
> ovs-webapp-api                        active  26233
> ovs-workers                           active  31543
> 
> 
> OVS non-running processes
> =========================
> 
> 

all service running.
But vpool service can't run on all master nodes.

Thanks.

**Comment by hoannv46** [comment]
Version of openvtorage component not newest
I reinstall my cluster, it work.
Seem my cluster has some conflicts.

Thanks
