### ISSUE TITLE
ASDs which don't belong to the backend should not be labelled green but grey

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1782]
ASDs which don't belong to the backend should not be labelled green but grey.

![2017-09-21_15-56-42](https://user-images.githubusercontent.com/8392927/30699744-d83d78fe-9ee5-11e7-8c81-1cdf781e9cab.jpg)

**Comment by JeffreyDevloo** [comment]
The gray color is used for marking osds that we know nothing about (unable to query to information)
Should we still mark it as gray?
Also this is for the current development build, not yet released so we should tackle this quite quickly

**Comment by wimpers** [comment]
Yes, please as having them being green should only be used for disks which belong to that backend

**Comment by kvanhijf** [comment]
We should be able to distinguish the difference between grey disks
belonging to the current Backend (for whatever reaons they are grye) and
grey disks belonging to another Backend, no?

**Comment by wimpers** [comment]
It would be best if we can make the distinction  (2 types of gray, also do it it on the node detail if you expand).

Before starting with this best solution, can we estimate the simple solution (just adding the ASDs which don't belong to the backend to grey/unknown) and the best solution?

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/framework-alba-plugin#545
