### ISSUE TITLE
unreachable repo lets check for updates hang without timeout

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1786]
with apt-ee being unavailable, the check for updates remains hanging around and prevents newer checks (even when the repo is available again). 

There should be some timeout to make sure these tasks are removed from the queue (now had to restart the workers service to force it to forget)

**Comment by sjovdnbos** [comment]
Fixed by https://github.com/openvstorage/framework-extensions/pull/62
Packaging information: openvstorage-extensions-0.3.0-dev.1516272162.011d502

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/framework-extensions#65
