### ISSUE TITLE
Implement new ClusterNotReachableException by VolumeDriver

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1789]
A new exeption has been introduced by the volumedriver in case a storagedriver client request times out: ClusterNotReachableException
Currently this new exception has not been released yet (on dev branch)

We should implement this and act accordingly in many parts of our codebase
Most importantly the ensure_safety in the MDSServiceController

Related ticket https://github.com/openvstorage/volumedriver/issues/349

**Comment by wimpers** [comment]
@kvanhijf  Which are the use cases and  please specify the 'in many parts'  in a bit more detail so we can asses where this will have impact and add a time estimate. Is this a  day work, a week, a month?

**Comment by JeffreyDevloo** [comment]
We would have review all parts of code on which we call volumedriver calls. The current RuntimeError we'd catch might not be enough.
I estimate it to be a day

**Comment by wimpers** [comment]
To be taken up in this ticket use the ClusterNotReachableException in  the ensure_safety in the MDSServiceController. All other items can be picked up later.

**Comment by sjovdnbos** [comment]
MDSServiceController is fixed by:
https://github.com/openvstorage/framework/pull/2139
openvstorage-2.13.0-dev.1533718330.c309893

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
