### ISSUE TITLE
Free/Used space on Active Drive backend detail page incorrect

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1795]
A new backend consisting out of 96 8TB drives with only a little data written to it shows 50% used/free space!?

See following screenshot
![screen shot 2017-09-25 at 16 42 18](https://user-images.githubusercontent.com/12733895/30814455-8c9bfd2a-a210-11e7-91df-2f38444c882e.png)

**Comment by wimpers** [comment]
@JeffreyDevloo  this should be fixed since you are no longer using asd-statistics. Can you 
confirm and close?

**Comment by toolslive** [comment]
it's alba that lists it as 50%. Framework's not to blame (anymore)

**Comment by JeffreyDevloo** [comment]
As mentioned by @toolslive 
The statistics alba reported are currently hard-coded so the framework will show these hard-coded ones
