### ISSUE TITLE
Updating with plugins could crash the update

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1805]
### Problem descriptions
Plugins which shoot tasks within celery can break our update if they are not updated at the same time.
Given the nature of plugins, they will always be a few steps behind and could cause issues when updating

### Proposed solution
Plugins should be given their own directory on which we can check if they are valid with the current code. If not, the plugin should not be allowed to registers its own tasks

**Comment by wimpers** [comment]
@JeffreyDevloo 
is this a hypothetical issue or did you run into this during testing? Can you add a time  estimate of how much this would be to fix.

**Comment by JeffreyDevloo** [comment]
@wimpers 
This is a realistic case. The statsmonkey was known for breaking the update.
I estimate it to be 3 days of work to fix this

**Comment by wimpers** [comment]
Framework maintains every plugin so no longer an issue and @JeffreyDevloo was a crybaby.
