### ISSUE TITLE
Updater doesn't 'see' updates anymore when services need a restart

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1833]
We have a run version file for many of our services
eg: /opt/OpenvStorage/run/ovs-albaproxy_vpool1.version

This file contains the version of the binary which is used by this service. During migration code we sometimes edit the service file and then we add a '-reboot' entry in the version file indicating this service needs a restart. The 'Refresh Package Information' should pick this up, so so-called updates are available, but this is not the case anymore

**Comment by kvanhijf** [comment]
Merging in the code closed the ticket

**Comment by kvanhijf** [comment]
openvstorage-2.10.3-dev.1507883754.892ffa8

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
