### ISSUE TITLE
API should allow for generic calls

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1835]
Our current implementation does not allow to add generic calls which can be used for an entire cluster for example. Eg: client.get('get_cluster_status')

This is currently impossible, because we require a DAL object to be passed in the API, like this
client.get('storagerouters/' + storagerouter.guid + '/get_cluster_status')

This is a very sub-awesome implementation for an API

**Comment by JeffreyDevloo** [comment]
Taking this up as I need for another ticket.

**Comment by JeffreyDevloo** [comment]
This would require a update from the Django-rest-framework. 
http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-methods-for-routing or we could test https://github.com/chibisov/drf-extensions which does the same for older Django versions.
I'd opt for an update

**Comment by wimpers** [comment]
@JeffreyDevloo  what is the status of this ticket? Did you  pick it up? Why is this urgent?

**Comment by JeffreyDevloo** [comment]
This is still pending, to be picked up. I did not require it so far (as the reconfigure storagedriver was put on hold for reviewing)

**Comment by wimpers** [comment]
@JeffreyDevloo so you need it for finishing the reconfigure storagedriver ticket?

**Comment by JeffreyDevloo** [comment]
Not really, but it would mean that an api call to retrieve cluster-wide information is bound to a parameterized api.
Example: get_all_statistics, ideally it would be placed on vpool so /api/vpools/get_all_statistics
However, the current implementation does not allow this and one would need to provide an id: /api/vpool/<vpool_guid>/get_all_statistics
Placing it on a call with a <vpool_guid> makes it look like that the call is only for that instance, while it would actually retrieve all statistics from every vpool

**Comment by wimpers** [comment]
Removed Urgent label

**Comment by JeffreyDevloo** [comment]
Tackling as the iscsi-ha changes require even more generic calls

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2039
Packaged in openvstorage-core_2.12.0-dev.1525420669.4a3f34e-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
