### ISSUE TITLE
Implement 'scrub_all_vdisks' API call

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1836]

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1837 --> openvstorage-2.10.3 (unstable)
https://github.com/openvstorage/framework/pull/1838 --> openvstorage-2.10.4-dev.1508145746.3739fed (fwk-develop)

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
