### ISSUE TITLE
Vdisk should have an unknown state

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1850]
### Problem description
When an XMLRPC error is raised, the info property will return RUNNING for live status. This is sub awesome and might lead to more issues

**Comment by wimpers** [comment]
@JeffreyDevloo 

what are the current possible states? Why UNKNOWN and not ERROR ? If we receive that XMLRPC error  are there cases where the vDisk is actually running or is it always stopped? What do you as a user need to do next ?

**Comment by JeffreyDevloo** [comment]
Current statusses: 'HALTED', 'NON_RUNNING', 'RUNNING'

The reason behind the unknown is that management calls could be blocked and no information can be fetched from the volumedriver while the volume is still running.
 There is no current ERROR state (should be different query to see if a volume could not be started or sth)

**Comment by sjovdnbos** [comment]
Fixed in #1903 
Package information: openvstorage-2.11.1-dev.1514987645.47f352b

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
