### ISSUE TITLE
Block multiple db roles in one storagerouter

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1852]
after configuring a first partition in a disk with write, scrub, DB, DTL functionality, i quickly started a second wizard to assign a second partition with DB role.

- n>1 partitions with DB (and DTL) role should not be allowed

- i still could not create a backend, (error warning: need at least one partition with db role), despite having 2 disks with DB role assigned visually

**Comment by wimpers** [comment]
Since https://github.com/openvstorage/framework/issues/954 is closed, we should limit the amount of DB roles that can be set to 1.

**Comment by JeffreyDevloo** [comment]
That is indeed the reason for this ticket

**Comment by wimpers** [comment]
BAM assumes this is a small one to fix, revert if not the case.

**Comment by sjovdnbos** [comment]
Fixed by #1938 
Package information: openvstorage-core_2.11.1-dev.1516777937.04bca97-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
