### ISSUE TITLE
integration of edition in config management

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1853]

**Comment by wimpers** [comment]
@simonOpenV  please elaborate what this issue exactly does. Is this a bug , feature, improvement?

**Comment by sjovdnbos** [comment]
https://github.com/openvstorage/iscsi-manager/pull/40 --> iscsi-manager-0.3.0-dev.1509380867.4db9b09
https://github.com/openvstorage/framework/pull/1851 --> openvstorage-2.11.1-dev.1509380766.6af120a
https://github.com/openvstorage/alba-asdmanager/pull/297 --> openvstorage-sdm-1.11.0-dev.1509380829.b18bda9

**Comment by kvanhijf** [comment]
Issue was created by me as an example for Simon
This issue was required to make life easier in the healthcheck and will also prove useful in the framework's package manager

**Comment by wimpers** [comment]
What is the content of the change? You now store the edition (OSE or EE) in the config mgmt Arakoon?

**Comment by JeffreyDevloo** [comment]
Yes

**Comment by wimpers** [comment]
@simonOpenV  @JeffreyDevloo will this version also be displayed on the https://ip/#full/support page?

**Comment by JeffreyDevloo** [comment]
@wimpers That is currently not the case but could be added

**Comment by wimpers** [comment]
Please add. Otherwise the version might be different depending on where you look.

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
