### ISSUE TITLE
Update broken on fwk-develop

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1856]
Since the introduction of the /ovs/framework/edition configuration key, the update is broken.
For the moment we cannot test the migration code and other update paths

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1873
https://github.com/openvstorage/alba-asdmanager/pull/304
https://github.com/openvstorage/framework-alba-plugin/pull/529
https://github.com/openvstorage/framework-iscsi-plugin/pull/32
https://github.com/openvstorage/framework-extensions/pull/53
https://github.com/openvstorage/iscsi-manager/pull/41

**Comment by wimpers** [comment]
Assigning to @JeffreyDevloo as Kevin is no longer with us.

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
