### ISSUE TITLE
DB role persists after removal of all vpools

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1865]
When trying to revert an installation, the DB role persists, crashing the revert. 
This is due to the voldrv arakoon that is not removed after deletion of all vpools.

**Comment by JeffreyDevloo** [comment]
@simonOpenV 
https://github.com/openvstorage/framework/issues/1867 is related. The cleanup of that role should be done.
Can the DB role be removed now?

**Comment by sjovdnbos** [comment]
@JeffreyDevloo Double checked and this problem does not pop up anymore.

Fixed as #1867 was fixed
Package information: package openvstorage-2.11.1-dev.1510675299.e88a327

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
