### ISSUE TITLE
DB role refresh bug in gui

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1866]
after creation of first partition with all roles, i tried to create a backend. An error message was visible that a DB role should be available on a partition.
After refreshing the page, the DB role was recognized, the error message did not appear and the backend could be created.

**Comment by wimpers** [comment]
We don't want autoamtically start refreshing pages/wizards.

**Comment by JeffreyDevloo** [comment]
This is a small and effortless change. It is the only wizard that does not refresh its current info atm

**Comment by wimpers** [comment]
@JeffreyDevloo so all other wizards auto refresh every x secs?

**Comment by JeffreyDevloo** [comment]
Those that require a specific field to be X or Y do

**Comment by wimpers** [comment]
Re-opened as this is something @JeffreyDevloo  would like to fix and requires minimal effort.
