### ISSUE TITLE
Arakoon cleanup after last vpool removal

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1867]
Removal of the last vpool does not remove the arakoon voldrv cluster.
If the storagerouter no longer has linked storagedrivers, the watcher-volumedriver is not removed.

**Comment by sjovdnbos** [comment]
package openvstorage-2.11.1-dev.1510675299.e88a327

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
