### ISSUE TITLE
Allow unittests to be filtered by prefix

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1871]
### Feature description
Allow ovs unittest --prefix 'test_alba' to only test files which match this prefix.
Would make it easier for Travis unittesting (we now specify the files manually)

**Comment by sjovdnbos** [comment]
fixed by #1907
package info: openvstorage-2.11.1-dev.1513782087.ea0b9f5

**Comment by sjovdnbos** [comment]
This is now used for easier Travis unittesting in framework-alba-plugin
https://github.com/openvstorage/framework-alba-plugin/pull/544
Package information: openvstorage-backend-1.11.0-dev.1514990193.4bf1161

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
