### ISSUE TITLE
 Investigate parameters for auto healing of RabbitMQ.

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1875]
Investigate parameters for auto healing of RabbitMQ. 
@saelbrec please add content you want to have investigated.

**Comment by wimpers** [comment]
@matthiasdeblock I believe the research has been done for this. Can I close this one?

**Comment by matthiasdeblock** [comment]
It has been investigated and implemented in our setup for external RabbitMQ. 

@wimpers , will this be implemented in the framework as well for the internally managed RabbitMQ?

**Comment by matthiasdeblock** [comment]
Ticket to add autoheal: https://github.com/openvstorage/framework/issues/1930
PR for the change: https://github.com/openvstorage/framework/pull/1931
