### ISSUE TITLE
Update improvements

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1876]
Our update logic has too much logic spread over several repositories. We also restart services when its unnecessary sometimes. It would be much better and more maintainable to have gather ALL update related information during the scheduled task and perform the update according to the model. Instead of gathering information in every separate piece in the update code.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/iscsi-manager/pull/42 --> iscsi-manager-0.3.0-dev.1512461178.705abd4
https://github.com/openvstorage/framework/pull/1877 --> openvstorage-2.11.1-dev.1512462328.2f7b322
https://github.com/openvstorage/framework-alba-plugin/pull/530 --> openvstorage-backend-1.11.0-dev.1512462379.c50a4f3
https://github.com/openvstorage/alba-asdmanager/pull/305 --> openvstorage-sdm-1.11.0-dev.1512461202.9713965
https://github.com/openvstorage/framework-extensions/pull/54 --> openvstorage-extensions-0.3.0-dev.1512461138.7193d1b
https://github.com/openvstorage/framework-iscsi-plugin/pull/33 --> openvstorage-iscsi-plugin-0.3.0-dev.1512461242.763a44e

**Comment by wimpers** [comment]
Assigning to @JeffreyDevloo as Kevin is no longer with us. 

What is the status of this one? Since there are packages shouldn't this be code_complete?

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
