### ISSUE TITLE
conflict on python-six dependency with devstack

### ISSUE THREAD

**Issue by zhouyuan** [openvstorage/framework#189]
Installing ovs on ubuntu 14.04 will install python-six 1.5.2. The python lib will be at /usr/lib/python2.7/dist-packages
While Openstack Kilo needs some newer version of six (1.9). With pip it will be at /usr/local/lib/python2.7/dist-packages

By default python will select the 1.5.2 version first, this results some Openstakc module not working.

rm /usr/lib/python2.7/dist-packages/six\* will fix this but this is not the best way.

Is it possible to provide a newer python-six deb package in the ovs repo? So there will be no conflict.

**Comment by tomzo** [comment]
I had related problem when installing on ubuntu, with openstack Juno. I had to install six and suds with explicit versions.

```
sudo easy_install six==1.7.0
sudo easy_install suds==0.4
```

**Comment by wimpers** [comment]
We have added it to our bug tracker.

**Comment by wimpers** [comment]
No longer an issue on

Openstack 9.0.0 (Newton)
Openvstorage 2.7.0
Package python-six is installed by openstack.
