### ISSUE TITLE
default function params

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1908]
Some function headers have default params such as 
`def fun(x={}):`
`def fun(x=[]):`
This may lead to unpredictable behavior and is subawesome.

**Comment by sjovdnbos** [comment]
https://github.com/openvstorage/framework/pull/1900
package info: openvstorage-2.11.1-dev.1513783726.5853860
https://github.com/openvstorage/framework-alba-plugin/pull/543
package info: openvstorage-backend-1.11.0-dev.1513783836.cb71b4e
https://github.com/openvstorage/framework-extensions/pull/60
package info: openvstorage-extensions-0.3.0-dev.1513783962.09564b1

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
