### ISSUE TITLE
create vpools error

### ISSUE THREAD

**Issue by run283092610** [openvstorage/framework#1910]
hi
i met a question when i create vpools 
how can i solve this problem
thanks

the message log
Dec 23 15:46:15 localhost gunicorn: 2017-12-23 08:46:15 52700 +0100 - localhost - 2832/140098847882608 - hybrids/storagedriver.py - fetch_statistics - 270 - ERROR - Error loading statistics_node from test-pool2k8aRVaFCTAB2GrBL: Python argument types in
Dec 23 15:46:15 localhost gunicorn: StorageRouterClient.statistics_node(StorageRouterClient, str)
Dec 23 15:46:15 localhost gunicorn: did not match C++ signature:
Dec 23 15:46:15 localhost gunicorn: statistics_node(volumedriverfs::PythonClient {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > node_id, bool reset=False)
Dec 23 15:46:15 localhost gunicorn: 2017-12-23 08:46:15 54100 +0100 - localhost - 2832/140098847882608 - hybrids/storagedriver.py - fetch_statistics - 271 - ERROR - Error loading statistics_node from test-vpoolk8aRVaFCTAB2GrBL: Python argument types in
Dec 23 15:46:15 localhost gunicorn: StorageRouterClient.statistics_node(StorageRouterClient, str)
Dec 23 15:46:15 localhost gunicorn: did not match C++ signature:
Dec 23 15:46:15 localhost gunicorn: statistics_node(volumedriverfs::PythonClient {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > node_id, bool reset=False)
Dec 23 15:46:16 localhost arakoon: 2017-12-23 15:46:16 226047 +0800 - localhost.localdomain - 1202/0 - arakoon - 5411 - info - 192.168.3.217:client_service:session=0 connection=192.168.3.217:client_service_1780 socket_address=ADDR_INET 192.168.3.217,57491

**Comment by wimpers** [comment]
Can you still remove the vPool from the Storage Router and try again?

**Comment by run283092610** [comment]
i have solve this problem thanks
