### ISSUE TITLE
Refreshing update information times out after 30 minutes when a node is offline fro scrubbing.

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#1911]
This step takes ages when a node is offline/unreachable (during framework upgrade from 2.9.5 to 2.9.9):

```
2017-12-26 09:47:26 19600 -0500 - SV4SRV0015 - 27261/140431625942784 - update/core - 38 - DEBUG - Refreshing update information
```

**Comment by sjovdnbos** [comment]
I investigated this with the information provided, but this issue is not present in current develop. 
This was most probably fixed by the update rework introduced in bighorn.
We also do not want to backport this.
