### ISSUE TITLE
VDisk creation name validation doesnt work

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1915]
Tried to make a vdisk with name '2' or any other integer, could initalize creation only to receive an error afterwards 

> Adding vDisk failed: 'int' object has no attribute 'strip'

2 checks are faulty here: 
- length of the name should be longer then 3 (as stated in the description)
- pure integers should either be allowed or mentioned in the description as invalid

**Comment by JeffreyDevloo** [comment]
Looks like the initial checking of the regex does not work. The name is translated as an int, not a string. Just casting it to a string should do the trick

**Comment by sjovdnbos** [comment]
Fixed in #1932

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
