### ISSUE TITLE
Scrubbing vdisks should reuse proxies where possible

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1920]
### Problem description
Since we changed the scrubbing proxy to be a uniquely generated uuid as name instead of something comfortable, we are no longer able to reuse a scrubbing proxy
This will give off some issues:
- Scrubbing 2 vdisks of the same vpool at the same time with the single scrub won't work (the second proxy would be deployed with the same port)
- More proxies would be deployed when scrubbing single vdisks than necessary

I propose to keep an entry in Arakoon whether the scrubbing proxy should be removed and the last scrubber should clean this up

Estimation:  1 day

**Comment by wimpers** [comment]
Please also patch on 2.9.x

**Comment by JeffreyDevloo** [comment]
Hmmm my initial estimate is not entirely correct.
The current scrub flow was meant to be primarily used by the scheduled tasks, which ensured only one would run at a given time
I have identified the following issues:
- Creating proxies could fail if different workers would be executing a scrub job at the same time for vdisks of the same vpool
- Every scrubbing job creates its own proxy, causing the framework to track multiple services instead of one and also increasing resource consumption on the node
- Multiple scrub jobs could each deploy the max number of scrubbing threads, causing the overall number of scrubbing threads to exceed the max number (say the max number of threads to scrub a disk at the same time would be 20. But creating 2 jobs, the number of threads could already be 40, so bypassing this restriction) (this can be fixed at another time)

Changes to be done:
- Re-use the same proxy: this requires tracking the usage of the proxy through multiple threads and multiple workers 
- Track vdisk scrub states (to identify scrubbing issues)
- Provide information of scrubbing jobs (link the celery job id to the job that is executing )
- Track the number of threads (can be fixed at another time)

So my estimation for all of this work is 10 days

Possible shortcut to take: 
do not re-use the proxies and so do not track all job information 
- this would leave operations blind again (seeing as there are issues popping up frequently, this might no be a good idea)
- it would also mean I'd need to further investigate https://github.com/openvstorage/framework/issues/1916 of which all debugging info is kind of lost

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.9.10 release
