### ISSUE TITLE
Enable autoheal for RabbitMQ

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1930]
For the externally managed RabbitMQ cluster we have enabled autoheal. 

Autoheal will fix partitioning issues from RabbitMQ when suffering a network outage or a downtime from one or more RabbitMQ node(s).

Adding ```{cluster_partition_handling, autoheal},``` to /etc/rabbitmq/rabbitmq.config.
https://github.com/openvstorage/framework/blob/0c62bdabca0f41f1b4f94285099d8141e6baf73c/ovs/lib/nodetype.py#L583

Example:
```
[
   {rabbit, [{tcp_listeners, [5672]},
              {default_user, <<"ovs">>},
              {default_pass, <<"0penv5tor4ge">>},
              {cluster_partition_handling, autoheal},
              {log_levels, [{connection, warning}]},
              {vm_memory_high_watermark, 0.2}]}
].
```

**Comment by matthiasdeblock** [comment]
PR https://github.com/openvstorage/framework/pull/1931

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.11.1 release
