### ISSUE TITLE
Look for potential issues in list caching

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1935]
### Problem description
@dejonghb had managed to create two vdisks which were not shown on the total overview of the vdisk page but they were shown on the vpool detail page

In short the overall list returned old results and the queried list showed the newest result

After a while the items resolved out of them selves (due to invalidation or expiration of the cache most likely)

**Comment by wimpers** [comment]
Can no longer reproduce. Re-open if it re-occurs.
