### ISSUE TITLE
Support page doesn't show all installed packages

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1949]
As seen on 199.191

```
Arakoon: 1.9.22
Open vStorage: 2.12.0-dev.1516977258.b6e19a4-1
: 0.4.0-dev.1516808173.bd0fe37-1
Storage Driver Enterprise Edition - Base: 6.16.6-0
Storage Driver Enterprise Edition - Server: 6.16.6-0
```

F.e. alba and backend package is missing

**Comment by sjovdnbos** [comment]
Will be fixed by: https://github.com/openvstorage/framework-alba-plugin/pull/567
https://github.com/openvstorage/framework-iscsi-plugin/pull/54
https://github.com/openvstorage/framework/pull/1971

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.11.3
