### ISSUE TITLE
Statsmonkey integration should only attempt to restart on master nodes

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1952]
### Problem description
Configuring the statsmonkey through the gui restarts all ovs-scheduled tasks. It does this by looping over all storagerouters.
The issue is that the scheduled tasks is only deployed on master nodes and so the restart sequence fails

**Comment by sjovdnbos** [comment]
Fixed by: #1970

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.11.3
