### ISSUE TITLE
Support page doesn't display IP of last storage node

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1954]
Support page doesn't display IP of last storage node
![2018-01-30_17-34-21](https://user-images.githubusercontent.com/8392927/35580202-b574a83c-05e8-11e8-8f03-cf0ce8f1d951.png)

**Comment by sjovdnbos** [comment]
On what environment was this seen?  I checked:
- develop
- andes
- staging
- fargo
- my own 2 node (develop) env

and none of these showed this behaviour.

**Comment by wimpers** [comment]
Bighorn RC1 - 2.10.3

**Comment by JeffreyDevloo** [comment]
@simonOpenV it might only occur on environments who have separate ASD nodes. (The QA ones you might have checked would be hyperconverged)

**Comment by sjovdnbos** [comment]
Fixed by https://github.com/openvstorage/framework-iscsi-plugin/pull/52

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-iscsi-plugin/releases/tag/0.3.2
