### ISSUE TITLE
Option to configure email escalation from the GUI

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#1955]
After discussion with @saelbrec en @jtorreke:

Under Administration > Support and a new section for monitoring
* URL(IP & Port) of checkMK API, login and passwd 
* Email address(es) for escalation

**Comment by JeffreyDevloo** [comment]
Small question. What is to be escalated?

**Comment by wimpers** [comment]
Events/Alerts. The email addresses need to be added to an checkMK instance

**Comment by wimpers** [comment]
Currenly no longer a requirement. Re-open if needed.
