### ISSUE TITLE
Need to refresh vdisk GUI page before you can iSCSI expose

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#1962]
When you just created a new vdisk and open the detail page, the iSCSI action button shows a rotating icon until you refresh the page manually. After the refresh, the action button pops up almost instantly.

**Comment by JeffreyDevloo** [comment]
My initial thought is that the plugin hooking is not firing when changes happen to the vDisk observable

**Comment by wimpers** [comment]
@simonOpenV  is this fixed?

**Comment by sjovdnbos** [comment]
No longer appears to be a problem, so would be fixed by 
#2093
openvstorage-2.13.0-dev.1529408893

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
