### ISSUE TITLE
[Develop] Extending vPool via GUI not working. The first backend is always selected

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1968]
### Problem description
The first backend is presented in the GUI as teh backend to extend

**Comment by wimpers** [comment]
I guess this one duplicates https://github.com/openvstorage/framework/issues/1953

If not let me know.

**Comment by JeffreyDevloo** [comment]
It is indeed a duplicate if that occurred on Develop. 
Fixed by https://github.com/openvstorage/framework/pull/1969
Packaged in openvstorage-webapps_2.12.0-dev.1518099253.1133a90-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
