### ISSUE TITLE
GUI support page doesn't show iscsi plugin name

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1974]
##Issue
The name of the iscsi plugin is not shown in the gui support page, where the version number is. 

##solution
The i18n json does not contain the specified key.
![screenshot from 2018-02-15 16-34-07](https://user-images.githubusercontent.com/33058909/36264880-3ce0deb2-126e-11e8-8a05-0ad1bd0f01a7.png)

**Comment by sjovdnbos** [comment]
Fixed by #1975

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.11.4
