### ISSUE TITLE
Scrub tasks getting deleted from the result backend after 1 day

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1979]
Scrub tasks getting deleted from the result backend after 1 day. 

Version:
```
openvstorage                         2.9.10-1
```

Task:
```
In [11]: task.backend.expires
Out[11]: 86400

In [14]: print task.backend.get(task.backend.get_key_for_task(task.id))
None
```

Why not just implement it in a way that you do not touch running task ID's? Instead of setting a fixed time?

**Comment by JeffreyDevloo** [comment]
A bit more context to clarify why it is an urgent thing to fix:
A scrub job was running from 20 feb 10am. The cleanup for those entries that might to old happen every day at 4 am. It checks the lifetime of a task entry (1 day by default). So on 22feb 4am the check occurred, saw that the entry is older than a day and it removed it but the task was still running.

For longer-running jobs we should wait until the state of a task is something that has finished together with the day checking. This way we avoid this issue

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/1981
Release in https://github.com/openvstorage/framework/releases/tag/2.9.11
Packaged in openvstorage-core_2.9.11-1_amd64.deb
