### ISSUE TITLE
Arakoon cluster names are identical

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#2000]
nuvolat@NY1SRV0005:~$ alba dev-extract-config --config arakoon://config/ovs/arakoon/ny1-hddbackend01-nsm_01/config?ini=%2Fmnt%2Fssd1%2Farakoon%2Fexternal_arakoon_cacc.ini | grep cluster
cluster = 54JvUoNRaeDhqqD3,FLM4OmtPuCivo528,N0RCG4vXgbP0w8LQ,hVEIul3TXTpCAWwg,wZ4GAcmR2MZl5x7S
cluster_id = ny1-hddbackend01-nsm_01

nuvolat@NY1SRV0005:~$ alba dev-extract-config --config arakoon://config/ovs/arakoon/ny1-hddbackend01-nsm_02/config?ini=%2Fmnt%2Fssd1%2Farakoon%2Fexternal_arakoon_cacc.ini | grep cluster
cluster = 54JvUoNRaeDhqqD3,FLM4OmtPuCivo528,N0RCG4vXgbP0w8LQ,hVEIul3TXTpCAWwg,wZ4GAcmR2MZl5x7S
cluster_id = ny1-hddbackend01-nsm_02

**Comment by sjovdnbos** [comment]
@wimpers In case Ops created these arakoons, this is not a framework issue
