### ISSUE TITLE
node_id changing when installing manager 

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2001]
### case
I first installed the iscsi-manager
``` system().get_my_machine_id() ``` resulted in CPb9tClS0RAF2MsX
Next, I installed the asd-manager
```system().get_my_machine_id ``` resulted in 'vdlXHhUZ5Lp19Z8r'
Ultimately, I installed openvstorage-hc
```system().get_my_machine_id ``` resulted in 'ruUhfibE6UOBTdpa'

This last id, 'ruUhfibE6UOBTdpa' is the expected id: it is present in /etc/openvstorage_id since the asd-manager installation. [code](https://github.com/openvstorage/iscsi-manager/blob/1bb7b4f55e892ebb8c6afcbe35704631d667626f/packaging/debian/debian/iscsi-manager.preinst)

this is obviously subawesome, as all the calls should result in the same value since they are installed on the same node. 
Right now, this is not resulting in issues, since all are updated upon install of a new package.

**Comment by JeffreyDevloo** [comment]
This is intended behavior. The ASD-Manager, ISCSI-manager and the Framework itself are all separate products and thus have their own code.
Every product has a different file in which the ID gets stored and their implementation of the `System` class references that file.

**Comment by wimpers** [comment]
I understand where this behaviour comes from.  I don't think on the other hand that it is a good idea that  a node_id changes based on packages you installed.  F.e. in the above the same code first returns  `CPb9tClS0RAF2MsX` and after installing the HC packages the same call results a different id `ruUhfibE6UOBTdpa`. This can be intended behaviour but it makes things very complex.

I believe a better strategy would be to generate a fixed node_id (first install of one of our packages) once so `system().get_my_machine_id()` always returns the same id. I understand this is a quite drastic change especially for the ASD-manager. For the iSCSI manager I would make this change, for the ASD manager we can put this as a Roadmap item and pick up later.

**Comment by JeffreyDevloo** [comment]
Please note that this is not the same system call. The ones for every product still return the same ID all the time. They are just different for the Framework, ASD-Manager and Iscsi-Manager
Todo:
get_my_machine_id() should point towards the same file for every product. This could be done in the openvstorage_extensions (as the system base class is located here)
add an additional get_my_product_id() and use that to differentiate different parts of the product so we are backwards compatible

**Comment by sjovdnbos** [comment]
### Fixed by 
https://github.com/openvstorage/framework-extensions/pull/92

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
