### ISSUE TITLE
Integrate ALBA recycle bin concept

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#2010]
See https://github.com/openvstorage/alba_ee/issues/270#issuecomment-376144179

Set the default cleanup time to 30 days at install time.

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0/https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb/openvstorage-backend-core_1.12.0-1_amd64.deb
