### ISSUE TITLE
Updating framework result into updating iscsi plugin from rc1 -> rc2

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#2012]
# Problem
On Centrilogic i updated FWK, Alba and Volumedriver from rc1 -> rc2.
ISCSI plugin is also installed on this environment and i was not sure if this was tested or not. So i unchecked the update for this plugin.
Found in the logs that ISCSI plugin was also been updated on the nodes while i ask not to do this.

# Logs
[update.log](https://github.com/openvstorage/framework/files/1850944/update.log)

**Comment by JeffreyDevloo** [comment]
THe iscsi-plugin is part of the Framework update. This is intended as all plugins need to work with the latest Framework version

**Comment by jeroenmaelbrancke** [comment]
So why do give the option on the update page to update/not update the plugin?
+Found out that the volumedrivers are not restarted via the gui.

**Comment by JeffreyDevloo** [comment]
The option points towards the iscsi-managers. The Framework models them as iscsi-nodes which come from the plugin.
There is a valid explanation. The naming just isn't that good :)

**Comment by wimpers** [comment]
Just rename the confusing entry.

**Comment by sjovdnbos** [comment]
#### Fixed by: 
https://github.com/openvstorage/framework/pull/2100
openvstorage-core_2.13.0-dev.1529995953.7c95847

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases
