### ISSUE TITLE
Dynamic update

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2020]
### Feature description
The current Framework update requires all Framework related components to be down. The reason behind this is so that the whole clustered setup runs with the same version all at once to avoid:
- Database inconsistency
- Code inconsistency (celery workers would be running older code than another worker)

This ticket serves as a reminder that we should opt to make it dynamic, like all other components in the product.

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/framework/issues/1179 ?

**Comment by JeffreyDevloo** [comment]
@wimpers Indeed.
