### ISSUE TITLE
Detect AWS disks

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2023]
### Problem description
The disks of an AWS node do not have any id associated with them. AWS ensures that the diskname stays the same.
The Framework is currently unable to work with only the diskname. We should detect and assume it is an AWS in that case.
For sync_disks logging: please see https://github.com/openvstorage/alba-asdmanager/issues/325

**Comment by wimpers** [comment]
To be checked if boto might tackle this.

**Comment by sjovdnbos** [comment]
#### Rework done for sync disks:
https://github.com/openvstorage/framework-extensions/pull/169
https://github.com/openvstorage/framework/pull/2166
https://github.com/openvstorage/alba-asdmanager/pull/340/

**Comment by sjovdnbos** [comment]
#### Integration of AWS disk detection:
https://github.com/openvstorage/framework-extensions/pull/174
https://github.com/openvstorage/framework/pull/2171
https://github.com/openvstorage/alba-asdmanager/pull/344

#### Package information:
openvstorage-extensions-0.5.1-dev.1535465753.0b22789
openvstorage-2.13.2-dev.1535531480.5c5c63c
openvstorage-sdm-1.13.1-dev.1535531618.819f98a

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.2
