### ISSUE TITLE
Handle the combined Alba/Arakoon package

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2040]
See https://github.com/openvstorage/alba_ee/issues/311

**Comment by sjovdnbos** [comment]
Too be implemented when https://github.com/openvstorage/alba_ee/issues/424 is finished

**Comment by sjovdnbos** [comment]
After discussion with @jtorreke, we concluded that, after all, it would not be a good idea to change the template files and service files of the framework. This to let things be easily modifiable by OPS. 
However, they will still need to point latestgreatest or any other alba version however to `/usr/bin/alba`, upon install.

Any thoughts, @toolslive ?

**Comment by toolslive** [comment]
why not use the environment ?
so not use `/usr/bin/alba` but `alba` (same for arakoon)
specific service files can still modify the environment (in casu `PATH`) to point to whatever flavour they need.

**Comment by wimpers** [comment]
After discussion with @simonOpenV and @jtorreke closing this one down as status is won't fix.
