### ISSUE TITLE
Auto-refresh dynamics

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2052]
### Feature description
This feature is a responsive to big lists having longer-to-calculate dynamics. Retrieving a big list which serializes the dynamics of the object can take so long that the cached dynamics of that object have already expired. Fetching that same list again would thus result in re-calculating the dynamics.

There should be separate process which keeps on refreshing the dynamics to avoid this issue. It might be mandatory to track which dynamics are more 'hot' than others to get some priority into this.

**Comment by wimpers** [comment]
This is what SIMF does:
contents=vpools,vdisks,info,_dynamics,_relations,snapshots,snapshot_ids,-statistics

**Comment by JeffreyDevloo** [comment]
For all vdisks (2.8k).

**Comment by wimpers** [comment]
> From: K. IR We will try to manage it from our end... In case we hit a BRICK WALL will ping you guys

Let's re-open this request once they hit that brick wall.


There are some voldrv tickets which might help here too
* https://github.com/openvstorage/volumedriver-ee/issues/34
* https://github.com/openvstorage/volumedriver/issues/366
* https://github.com/openvstorage/volumedriver/issues/332
* https://github.com/openvstorage/volumedriver/issues/325
