### ISSUE TITLE
Scrubber config incorrect amount of proxies

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#2054]
# Problem
The scrubber uses the config from an existing volumedriver and changes the ip and port of the proxy.
In the current setup we only deploy one scrubber proxy while the existing volumedriver have more than one proxy configured.

The suggestion is to deploy 4 scrubber proxies so the scrubber can blacklist some proxies if needed.

**Comment by JeffreyDevloo** [comment]
Number of proxies was moved to a different ticket: https://github.com/openvstorage/framework/issues/2059
Fixed by https://github.com/openvstorage/framework/pull/2056
Released in https://github.com/openvstorage/framework/releases/tag/2.9.13
Packaged in openvstorage-core_2.9.13-1_amd64.deb
