### ISSUE TITLE
Volume creation should setup the full mds backend config

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2057]
### Problem description
After creating the volume: the mds_checkup code is ran to extend the mds backend config with mds slave information.
This can be problematic in the scenario where the mds_checkup would fail. Setting it correct initially could avoid some problems

**Comment by wimpers** [comment]
Closing as MDS_checkup should be more robust and we should monitor volumes which have a subawesome MDS setup.
