### ISSUE TITLE
Investigate support-agent memory consumption

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2058]
### Problem description
The support-agent seems to cumulate memory the longer it runs.
As seen of the Pocops envir: 3.5G memory in use. After restart this was 90MB

**Comment by wimpers** [comment]
Might be caused by the persistent client (https://github.com/openvstorage/framework-extensions/issues/113)

**Comment by wimpers** [comment]
@JeffreyDevloo isn't this one fixed as the related issue is fixed? I would advise to close and re-open if seen again?

**Comment by JeffreyDevloo** [comment]
Indeed fixed by clearing transactions.
