### ISSUE TITLE
How to Turn On and Off Automatic Virtual Disk Snapshots, My Version 2.10.3

### ISSUE THREAD

**Issue by Seealso** [openvstorage/framework#2066]

**Comment by JeffreyDevloo** [comment]
Hi Seealso
There is currently no real straightforward way to disable automatic snapshots. Our snapshotting system does not cause any overhead so we'd never have thought on disabling it with an API call.
If you wish to disable automatic snapshotting, you need to change the scheduling interval of the task to 'null':
 ```
ovs config get /ovs/framework/scheduling/celery
{"ovs.generic.snapshot_all_vdisks": null}
```
Editing this entry can be done using `ovs config set`. The inserted data must be of JSON format

After editing this entry you need to restart `ovs-scheduled-tasks` on all nodes. The easiest way is to restart the whole framework using `ovs stop framework all` and then starting it again `ovs start framework all`

**Comment by Seealso** [comment]
thank you for your reply
My current situation is not to run an automatic snapshot of an hour's worth of virtual disks. I need this feature and be able to customize the setup interval. what do I need to do?

**Comment by Seealso** [comment]
Hello, thank you for your reply
My current virtual disk does not have an automatic snapshot. I hope to have this feature and can customize the interval. what do I need to do? @JeffreyDevloo
