### ISSUE TITLE
Framework should check for valid input from the config arakoon

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#2069]
Currently the  framework gets the data from the config arakoon without checking if what comes from the config is somehow valid. 

As an example the following issue made the scrubber fail as an `int` was stored while a `json` was expected
```
root@SV4SRV0001:~# ovs config get /ovs/framework/hosts/PK60o4X2lfl6XVmk/config
10
root@SV4SRV0001:~# ovs config get /ovs/framework/hosts/PK60o4X2lfl6XVmk/config
{
 "scrub_stack_threads": 10
}
```

Maybe just extending  `Configuration.get(key=threads_key,` default=2)` with the type you expect would already be a step forward. If the key would not be of the specified format, you could fall back to the default.

**Comment by JeffreyDevloo** [comment]
It was more the case of `/ovs/framework/hosts/R7kxOqtCkMGphcXM/config|scrub_stack_threads` which means retrieve key scrub_stack_threads from this config entry. If the config entry is not a json, we'd get keyerrors (suboptimal)

**Comment by wimpers** [comment]
Sure, but if there is a key error , you would expect the default to become true?

**Comment by wimpers** [comment]
Closing this one. After discussion with @JeffreyDevloo there should be no fallback to default but it should raise as it does now. Manual mistake.
