### ISSUE TITLE
VDisk Auto Snapshot Settings

### ISSUE THREAD

**Issue by Seealso** [openvstorage/framework#2071]
VDisk automatic snapshot settings Hello, thank you for your reply
My current virtual disk does not have an automatic snapshot. I hope to have this feature and can customize the interval. what do I need to do? and l   ovs config get  /ovs/framework/scheduling/celery  is null

**Comment by JeffreyDevloo** [comment]
Hi Seealso
Disabling snapshots can be done by: 
```
ovs config get /ovs/framework/scheduling/celery
{"ovs.generic.snapshot_all_vdisks": null}
```
Changing the interval can be done by:
```
ovs config get /ovs/framework/scheduling/celery
{"ovs.generic.snapshot_all_vdisks": {"minute": "*"}}
```
The format of a scheduling entry is composed of all possible crontab scheduling options from celery (http://docs.celeryproject.org/en/latest/reference/celery.schedules.html#celery.schedules.crontab)
Accepted keywords: `minute`, `hour`, `day_of_week`, `day_of_month`, `month_of_year`

If no automatic snapshots are made: please check the logging of your ovs-workers (journalctl -u ovs-workers) on all your nodes and look for `snapshot_all_vdisks`.

**Comment by Seealso** [comment]
My Ubuntu has automatic snapshots of virtual disks, why centos 7 does not have automatic snapshots of virtual disks, what do I need to do? Does it not support the centos7 system? @JeffreyDevloo

**Comment by JeffreyDevloo** [comment]
We only support Ubuntu 16.04. I can't assist you with the CentOS compatibility.
