### ISSUE TITLE
Why are Ubuntu and centos 7vdisk automatic snapshots different?

### ISSUE THREAD

**Issue by Seealso** [openvstorage/framework#2074]
My Ubuntu has automatic snapshots of virtual disks, why centos 7 does not have automatic snapshots of virtual disks, what do I need to do?

**Comment by JeffreyDevloo** [comment]
We only support Ubuntu 16.04. I can't assist you with the CentOS compatibility.
See https://github.com/openvstorage/framework/issues/2071

**Comment by yongshengma** [comment]
Is it a big deal to enable automatic snapshot in CentOS 7 ?
maybe I can do some coding work on it if you give some clue.
