### ISSUE TITLE
A volume's MDS slave should not be reconfigured as master if its state is unclear

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#2079]
Cf. https://github.com/openvstorage/volumedriver/issues/353 : a slave was newly set up and while the initial TLog replay was still ongoing, the volume was already configured to use this slave as master, which forces it to wait for the rebuild to finish.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2092
Packaged in openvstorage-core_2.9.15-1_amd64.deb
Released in https://github.com/openvstorage/framework/releases/tag/2.9.15
