### ISSUE TITLE
[Scrubber] - Push statistics of scrub jobs 

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2085]

**Comment by simonOpenV** [comment]
#### Will be fixed by: 
https://github.com/openvstorage/framework/pull/2115/

**Comment by wimpers** [comment]
after discussion with @jtorreke , can we add:
* status of the job (ok, failed)
* batch size - as in the number of disks requested to be scrubbed (if available)

**Comment by jtorreke** [comment]
* batch size
* number of successfully scrubbed vdisks
* number of failed vdisks

**Comment by sjovdnbos** [comment]
Fixed by:
#2115: openvstorage-2.13.0-dev.1531317306.2b53593
openvstorage/framework-extensions#137: openvstorage-extensions-0.4.2-dev.1531311919.0eeb480
openvstorage/framework-alba-plugin#601 :openvstorage-sdm_1.13.0-dev.1531316493.7a07f16

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
