### ISSUE TITLE
[lib decorators] - Preserve function contexts within decorators

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2086]
Certain decorators do not have the functool.wraps around them. This means that certain information is lost when fetching the docstrings

**Comment by sjovdnbos** [comment]
#### Fixed by:
#2118
#141

#### Package information:
openvstorage-2.13.0-dev.1531383139.d725c9e
openvstorage-extensions-0.4.2-dev.1531383165.cb0924f

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
