### ISSUE TITLE
The GUI mode sometimes reverts to undefined instead of the default full

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#2091]
The GUI mode sometimes reverts to undefined instead of the default full.

http://<ip>/#undefined/<more stuff> instead of http://<ip>/#full/<more stuff>

It happens sometimes, not yet discovered why. 

http://jira.openvstorage.com/browse/OVS-2748

**Comment by wimpers** [comment]
@simonOpenV  isn't this one fixed by your iSCSI changes?

**Comment by sjovdnbos** [comment]
This one seems to be fixed by framework hooking changes indeed.
#2093
openvstorage-2.13.0-dev.1529408893

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
