### ISSUE TITLE
Work around volumedriver lockup when removing MDS slaves of removed volumes

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#2101]
https://github.com/openvstorage/volumedriver-ee/issues/79

After volume removal MDS slaves self-destruct once the absence of the backend namespace is detected (during the periodic backend poll). If at the same time an MDS slave is removed via the Python API there's a potential for a lockup.

**Comment by redlicha** [comment]
Ideally the fwk shouldn't have to remove MDS slaves at all after volume removal due to the self-destruction mechanism. It should check for abandoned MDS masters and remove these.

**Comment by redlicha** [comment]
After discussion with @JeffreyDevloo : might be too rare an event to address this in the fwk?

**Comment by JeffreyDevloo** [comment]
Something to clear up:
- The Framework does not delete slaves when a volume is removed
- The Framework only messed around with MDS layout on the vdisk_checkup which is scheduled periodically or on resize/move event or by changing the vdisk parameters

What might have happened:
MDSCheckup was running as task A. On the delete_namespace the volume got removed in Task B.
The tasks were racing
