### ISSUE TITLE
celery: IOError: [Errno 13] Permission denied: '/var/lock/ovs_flock_messaging'

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2111]
I'm using ovs on CentOS 7.4 and there's an error report:

Jun 29 12:29:30 Node-35 celery: 2018-06-29 12:29:30 60900 +0800 - Node-35 - 2242/140005497288512 - celery/celery_run.py - task_postrun_handler - 3 - ERROR - Caught error during post-run handler
Jun 29 12:29:30 Node-35 celery: Traceback (most recent call last):
Jun 29 12:29:30 Node-35 celery: File "/opt/OpenvStorage/ovs/celery_run.py", line 167, in task_postrun_handler
Jun 29 12:29:30 Node-35 celery: MessageController.fire(MessageController.Type.TASK_COMPLETE, task_id)
Jun 29 12:29:30 Node-35 celery: File "/opt/OpenvStorage/ovs/lib/messaging.py", line 38, in new_function
Jun 29 12:29:30 Node-35 celery: filemutex = file_mutex('messaging')
Jun 29 12:29:30 Node-35 celery: File "/usr/lib/python2.7/site-packages/ovs_extensions/generic/filemutex.py", line 48, in _init_
Jun 29 12:29:30 Node-35 celery: self._handle = open(self.key(), 'w')
Jun 29 12:29:30 Node-35 celery: IOError: [Errno 13] Permission denied: '/var/lock/ovs_flock_messaging'

cd /var/lock

[root@Node-35 lock]# ls -la
total 0
drwxr-xr-x  6 root root 140 Jun 29 12:29 .
drwxr-xr-x 31 root root 980 Jun 29 13:30 ..
drwx------  2 root root  60 Jun 29 12:29 iscsi
-rw-r--r--  1 root root   0 Jun 29 12:29 kdump
drwxrwxr-x  2 root lock  40 Jun 29 12:29 lockdev
drwx------  2 root root  40 Jun 29 12:29 lvm
drwxr-xr-x  2 root root  60 Jun 29 12:29 subsys

My tiny solution:
Step 1
chmod a+w /var/lock
Step 2
systemctl restart ovs-workers.service

Then that error is gone.

[root@Node-35 lock]# ls -la
total 0
drwxrwxrwx  6 root root 160 Jun 29 13:38 .
drwxr-xr-x 31 root root 980 Jun 29 13:38 ..
drwx------  2 root root  60 Jun 29 12:29 iscsi
-rw-r--r--  1 root root   0 Jun 29 12:29 kdump
drwxrwxr-x  2 root lock  40 Jun 29 12:29 lockdev
drwx------  2 root root  40 Jun 29 12:29 lvm
-rw-rw-rw-  1 ovs  ovs    0 Jun 29 13:38 ovs_flock_messaging
drwxr-xr-x  2 root root  60 Jun 29 12:29 subsys

However, the permission on /var/lock goes back to 755 if I reboot system.

Best regards,
Yongsheng

**Comment by JeffreyDevloo** [comment]
Thanks @yongshengma, we will look into this issue if we pick up Centos again!

**Comment by wimpers** [comment]
Currently CentOS is out of scope so closing this one down with won't fix.
