### ISSUE TITLE
Add vdisk: size gets overwritten too fast

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#2114]
When trying to add a vdisk via the GUI, when you remove the 1 to create a 2GB disk, the 1 immediately gets put back. So you need to make it 12GB first, then remove the 1.

**Comment by sjovdnbos** [comment]
This happens because the observable (i.e. the size) should be a numeric value and  1 < x  < 65535. When removing the 1, no numeric value is entered and it defaults back to 1.

**Comment by JeffreyDevloo** [comment]
Yes, but you can delay it or make it update after keyup.

**Comment by sjovdnbos** [comment]
#### Fixed by:
https://github.com/openvstorage/framework/pull/2121
https://github.com/openvstorage/framework-alba-plugin/pull/602
#### Package information:
openvstorage-2.13.0-dev.1531406012.50e02de
openvstorage-backend-1.13.0-dev.1531406066.2ce723b

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
