### ISSUE TITLE
Sync vdisk with reality code should also check parenthood

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2126]
### Enhancement description
The current sync does not account for any hierarchy. Certain clones could not be flagged as clones in the Framework if the sync created the vdisk for the clone. This leads to confusion and might mess up other paths too

**Comment by sjovdnbos** [comment]
#### Will be fixed by:
https://github.com/openvstorage/framework/pull/2160
#### package information: 
openvstorage-2.13.0-dev.1534845256.210ac3d

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
