### ISSUE TITLE
template's ownership

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2141]
Once a vdisk is set as a template, it can't be used as a vdisk any more.  
In the vpool's directory, there'are bunch of vdisk.raws.  It's very nice that I can manipulate vdisk.raw and install a VM on it.  But I have to remember which one is a template that I shouldn't use for this operation.  Is a template really special or different from a vdisk?

**Comment by yongshengma** [comment]
about its ownership, i mean there's no way to move this template to another node.

**Comment by JeffreyDevloo** [comment]
Templates are not owned by a storagerouter. They are a read-only disk that can be used for cloning operations and that is available for cloning on all nodes.

**Comment by yongshengma** [comment]
I do vm installation on cmd line by using virt-install, so there is chance to operate on this template, isn't it?

**Comment by JeffreyDevloo** [comment]
Hi yongshengma

The only operation that is possible on a template is reading. The most common use case for vtemplates is the use create base images with them. These images can be be cloned to quickly deploy virtual machines
For example: 
- Install a Ubuntu 16.04 VM
- Set the bootdisk of this VM as a vtemplate.
    - The VM can no longer be used now since it went into read-only
- Create a clone of this vtemplate
- Hook up a new VM to the clone
- VM is now ready

`But I have to remember which one is a template that I shouldn't use for this operation.` 
A vtemplate is essentially still a disk that can be read so it should be accessible. You can organise your disks to make it more clear. All templates could be named with templates/DISKNAME so you'd see a folder templates inside the mountpoint.

**Comment by yongshengma** [comment]
Nice use!  Thanks.
