### ISSUE TITLE
Framework configuration information should be cached

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2145]
Frequently seeing `Too many open files: '/opt/OpenvStorage/config/framework.json'` when working with a number of threads

Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]: 2018-08-10 19:03:19 46400 -0400 - NY2SRV0003 - 29489/140349602002688 - lib/generic tasks scrub - 12244 - ERROR - Scrubber aea34e77-f22f-4837-a686-e085d55d49aa - vPool data-g-03 - StorageRouter NY1SRV1000 - Stack 0 - Scrubbing thread 2 - vDisk pcd_be616cb5-6708-49bd-97f5-2ab17b86c2a8 with volume id 93f9897b-d423-4090-be8c-60773e3d261a - Scrubbing failed
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]: Traceback (most recent call last):
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 622, in _execute_scrub
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:     backend_config=Configuration.get_configuration_path(self.backend_config_key))
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 80, in get_configuration_path
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:     key=key)
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 326, in _passthrough
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:     store, params = cls.get_store_info()
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/extensions/generic/configuration.py", line 132, in get_store_info
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]:     with open(cls.BOOTSTRAP_CONFIG_LOCATION) as config_file:
Aug 10 19:03:19 NY2SRV0003 ovs-workers[29462]: IOError: [Errno 24] Too many open files: '/opt/OpenvStorage/config/framework.json'

**Comment by wimpers** [comment]
Why not increasing the amount of allowed open files? Would also fix https://github.com/openvstorage/framework/issues/2146

**Comment by JeffreyDevloo** [comment]
It makes no sense to keep reading the file when it will never change.

**Comment by sjovdnbos** [comment]
#### Fixed by: 
https://github.com/openvstorage/framework/pull/2153

**Comment by JeffreyDevloo** [comment]
Fixed by #2153
Packaged in openvstorage-core_2.9.20-1_amd64.deb
Released in https://github.com/openvstorage/framework/releases/tag/2.9.20
