### ISSUE TITLE
why adding vpool can choose multiple IPs

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2148]
When I add or extend a vpool , I find both public ip and storage ip show up in the list widget `storage ip`.  This means I can choose either ip.  

However, I selected only one specific ip for storage during asd manager setup.  What's the sense for vpool to use other ips?

**Comment by JeffreyDevloo** [comment]
Hi yongshengma

The asd-manager setup asks for an IP to use for API communications and a list of IPs for ASD communication.
The API is used to manage ASDs on that particular manager. The ASDs are listening on the IP that you specified during the setup.

The VPool wizard requests a storage ip. This IP is used for the data path. The IP used for the management path within a VPool is the cluster IP set when you install the storagerouter.

You'd use different IPs to separate management calls from the data path. Example: you configure all management calls to go over 10.0.0.0/8 and the data path to go over 11.0.0.0/8. 
This means that 
- All bandwidth can be used for a particular path 
- Management network goes down: no impact on the data path
- Data path network goes down: hosts still accessible for managing (to figure out what is wrong)

Best regards
