### ISSUE TITLE
Widget reaction time slow

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2176]
Following https://github.com/openvstorage/framework/issues/2114, reaction time was bumped and digit enter fields now react properly. 
However, when entering digits via widgets or other places, these fields now do not react intuitively anymore.

Only entries to fix however were:
- amount of proxies in add new vPool + reconfigure vPool

**Comment by sjovdnbos** [comment]
#### Fixed by:
https://github.com/openvstorage/framework/pull/2177
#### Package information: 
openvstorage-2.13.2-dev.1535725066.c1ebb58

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.2
