### ISSUE TITLE
[Andes updates 3] Adding a linked local BE fails 

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#2179]
#### Problem
Adding a local backend fails: loading of backends fails and redirects  _or_ reloads in the GUI wizard of add-vpool.

#### stacktrace
```
[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"inputVpoolClientSecret" class=​"autofocus form-control" data-bind=​"value:​ data.clientSecret, valueUpdate:​ 'input'">​
OPTIONS https://<storagerouter_ip>/api/?timestamp=1535964909364 0 () x25
Navigated to https://172.17.16.19/
```
![image](https://user-images.githubusercontent.com/2900612/44977563-a8e77200-af68-11e8-8a0b-f9e93f8d31c1.png)

**Comment by JeffreyDevloo** [comment]
Based on the logging above: an api call must have failed which caused the GUI to check if the API was still responding before failing over (https://github.com/openvstorage/framework/blob/2.9.21/webapps/frontend/lib/ovs/api.js#L91)
The logging above shows the GUI contacting all nodes within the cluster and failing: https://github.com/openvstorage/framework/blob/2.9.21/webapps/frontend/lib/ovs/generic.js#L274

**Comment by JeffreyDevloo** [comment]
After some refactoring and pondering about this ticket:
- Relaying api call that timeout should not trigger the reload immediately. A validation should first be done to the current host
- Failing over could be done more gracefully

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2207

**Comment by JeffreyDevloo** [comment]
Packaged in https://github.com/openvstorage/framework/releases/tag/2.13.4
