### ISSUE TITLE
KeyError: 'HTTP_X_REAL_IP' at very beginning of debug

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2183]
This is not a real issue that I should post here, but I really want to find a way to do some debug work.

I stop 'ovs-webapp-api.service' and then go to '/opt/OpenvStorage/webapps/api' to modify settings.py:
```
DEBUG = True
#WSGI_APPLICATION = 'django.wsgi.application'
WSGI_APPLICATION = 'wsgi.application'

```
To start wsgi, run 
`python ./manage.py runserver 0.0.0.0:8000`
and it gets ready.

I input `http://192.168.2.21:8000/` in a browser, then login page comes out and everything goes fine afterwards.

This way has been working all the time a few months ago.  

However, now it looks not working as the same as before.  I didn't keep the old debug env and so can't compare and figure out.  The new env, i believe,  is absolutely the same as before (Ubuntu Fargo).  The issue I'm getting is when I input `http://192.168.2.21:8000/` in a browser.  The message on runserver terminal is:

```
root@Node-21:/opt/OpenvStorage/webapps/api# python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
September 07, 2018 - 05:57:50
Django version 1.8.7, using settings 'settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/usr/lib/python2.7/dist-packages/rest_framework/settings.py:23: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

/usr/lib/python2.7/dist-packages/rest_framework/serializers.py:152: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  return SortedDict(fields)

2018-09-07 05:58:03 53700 +0200 - Node-21 - 21813/140580482402048 - api/middleware - 0 - ERROR - An unhandled exception occurred: 'HTTP_X_REAL_IP'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/view.py", line 134, in dispatch
    return super(MetadataView, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/oauth2/decorators.py", line 57, in new_function
    results = f(*args, **kw)
  File "/opt/OpenvStorage/webapps/api/oauth2/decorators.py", line 91, in new_function
    request.META['HTTP_X_REAL_IP']
KeyError: 'HTTP_X_REAL_IP'
[07/Sep/2018 05:58:03] "GET / HTTP/1.1" 500 67
[07/Sep/2018 05:58:04] "GET /favicon.ico HTTP/1.1" 500 61977
[07/Sep/2018 05:58:04] "GET /favicon.ico HTTP/1.1" 500 62097

```

I use pycharm to attach processes and find that this key HTTP_X_REAL_IP doesn't exist at all.

Whatsoever, firstly i want to know why I didn't meet this issue before.  I have tried several env to make sure and they all gave this key error.  I also can't find any places that I did differently from a few months ago unless I really remember sth wrong.   Maybe some changes in settings.py should be made, but I also tried.  I get stuck .............. and hope to find help.

**Comment by JeffreyDevloo** [comment]
Hi @yongshengma 
Which browser are you using and are you tweaking anything of that browser?
The only browser that the Framework supports is an unmodified Google Chrome.

The `HTTP_X_REAL_IP` header is a header that all browsers add when making requests towards the server. This header contains the IP of the current user.
The Framework tracks the IP of the user to enforce certain rate limiting.

Edit:
If this problem persist: augment that part of the code by replacing `request.META['HTTP_X_REAL_IP']` to `request.META.get('HTTP_X_REAL_IP')` on  `/opt/OpenvStorage/webapps/api/oauth2/decorators.py` line 91
Note that all users that are missing the header will share the same rate limiting this way.

**Comment by yongshengma** [comment]
Hi @JeffreyDevloo 

Thanks for hints.  It's gone.  The solution is to change the runserver port to 8002 and still send requests to nginx like `https://192.168.2.21`.  Then it's working!  The cause might be HTTP_X_REAL_IP header was lost if not going through nginx.  The gunicorn uses 8002 port all the time, so I needn't modify related config. 
 Appreciate again!

**Comment by yongshengma** [comment]
i'm using both Chrome and Firefox without tweaking.

**Comment by wimpers** [comment]
Issue was found and is outside OVS
