### ISSUE TITLE
[develop] update in gui results in undefined

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2206]
After updating within the current develop, I am redirected towards `https://<ip>/undefined` instead of refreshing of the page, as it used to do

**Comment by JeffreyDevloo** [comment]
The GUI will try to failover to a different node if the API is becoming unresponsive.
The redirection can occur but fetchen the plugin metadata might fail which is causing the undefined.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2207
