### ISSUE TITLE
add remote resource -->   port 443 should be filled in by default in stead of 80

### ISSUE THREAD

**Issue by OVSchristophe** [openvstorage/framework#2225]
add remote resource -->   port 443 should be filled in by default in stead of 80
![selection_053](https://user-images.githubusercontent.com/45066628/49739731-e14aca80-fc92-11e8-93bd-12b5667c0ef0.png)

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/1821 which is part of the 2.13.3 release
