### ISSUE TITLE
[Node update] Support updating ALBA on a single node

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2308]
Provide an api to locally update the alba packages on a node to latest greatest. 
---------------------

## requirements
use locking, so that no other nodes can update their alba on the same moment

## implementation
- apt-get install alba-ee
- update alternatives to the new version
- restart all alba services, one by one, restart all arakoons, one by one

**Comment by JeffreyDevloo** [comment]
A single node should be able to update all ALBA related components on it.
This holds true for
- proxies
- arakoon
- asds

Implementations:
- It has to be accessible through an API (CLI or HTTP)
- Provide a way to track the update progress
- Use locking to enforce single node

Implement first on andes-updates-4 (1.9x series)

**Comment by sjovdnbos** [comment]
## Extensions:
https://github.com/openvstorage/framework-extensions/pull/227
## Framework
https://github.com/openvstorage/framework/pull/2311
## Alba
https://github.com/openvstorage/alba-asdmanager/pull/362
