### ISSUE TITLE
Xenserver Support

### ISSUE THREAD

**Issue by sjkeerthi** [openvstorage/framework#387]
Hi 

Will there is support for xenserver / docker or any future paln.

**Comment by wimpers** [comment]
Hi,

we have support for docker. See 
https://openvstorage.gitbooks.io/openvstorage/content/Administration/createvdisk.html#docker

For XenServer you should be able to use the blktap interface we added:
https://openvstorage.gitbooks.io/openvstorage/content/Administration/createvdisk.html#block
