### ISSUE TITLE
git repo structure cleanup

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#411]
todo
- move framework to separate repo
- the openvstorage main repo (this one) should only be used for documentation & milestones & stories !!!
- the stories on openvstorage main repo should link to Feature Requests or Bugs on the other repo's
- make sure each repo has a well chosen name
- move all documentation to this repo & make sure gitbook follows this  change

**Comment by wimpers** [comment]
Documentation piece will be picked up in https://github.com/openvstorage/home/issues/3
