### ISSUE TITLE
logging & eco's to redis

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#417]
todo org
- create Feature Request (ISSUE) on each relevant repo
- link the FR's to this story

todo work
- send all logging info to local redis
- make sure there is a config setting for each component to define which redis to use & port, if not specified do not log or keep on logging to files
- when logging to redis do not log to files
  -also send all ECO's to redis
- document the behaviour

ECO= Error Condition = Event

**Comment by khenderick** [comment]
Integrated and documented at [gitbooks](https://openvstorage.gitbooks.io/framework/content/docs/log.html)
