### ISSUE TITLE
stats to redis

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#418]
todo org
- create Feature Request (ISSUE) on each relevant repo
- link the FR's to this story

todo work
- send all stats info to local redis
- make sure there is a config setting for each component to define which redis to use & port, if not specified do not send stats
- define in config file  (ETCD) what stats to send and at what interval
- document the behaviour & used stat counters

example
- for volume driver want to see IOPS per volume, cache hits, ...

**Comment by wimpers** [comment]
@jeroenmaelbrancke  since you are working on this, assigned to you 

Documentation can be put here 
 https://www.gitbook.com/book/openvstorage/ovs-monitoring/details

**Comment by JeffreyDevloo** [comment]
The following aspects (related to this ticket) are not included in the 'Statsmonkey':
- config setting for each component
- config file (ETCD) what stats to send and at what interval

There are however global configuration files to specify  redis to use & port & the interval.
@despiegk is the option to define what stats will be reported at configurable intervals necessary? Grafana is ideal to get an overview of the statistics of a certain component at a given time.

**Comment by wimpers** [comment]
Closing this ticket. If additional features are required a new ticket will be created.
