### ISSUE TITLE
all configuration info comes from ETCD

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#419]
todo org
- create Feature Request (ISSUE) on each relevant repo
- link the FR's to this story

todo
- make sure that all config settings for each component are in ETCD
- properly document these config settings in our main doc repo 
- ETCD connection param should be defined on command line when starting the daemons
- explain how to use ETCD as backend and how to startup each component while  using ETCD

**Comment by wimpers** [comment]
@khenderick is there anything left open for this FR?

**Comment by khenderick** [comment]
@wimpers, for the framework everything is implemented and documented.
