### ISSUE TITLE
Add Snapshot and Set as vTemplate as possible actions for a vDisk

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#533]
Add Snapshot and Set as vTemplate as possible actions for a vDisk. This is currently available for vMachines but not for vDisks.

**Comment by wimpers** [comment]
@khenderick aren't you working on this one? I believe this is a duplicate?

**Comment by khenderick** [comment]
This is indeed a duplicate of more recently created #629 because I just can't manage to find anything in this huge pile of tickets at various repositories. Adding to the confusion; it also wasn't linked to it's storycard.
