### ISSUE TITLE
Setting up GRID fails because of new Etcd version

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#549]
2016-05-25 16:08:17 87400 +0200 - OVS-2 - 17375/139777810417472 - lib/setup - 12 - INFO - Extending Etcd cluster to this node
2016-05-25 16:08:18 39700 +0200 - OVS-2 - 17375/139777810417472 - lib/setup - 14 - ERROR - Failed to setup extra node
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 467, in setup_node
    hypervisor_info=hypervisor_info)
  File "ovs/lib/setup.py", line 1129, in _setup_extra_node
    EtcdInstaller.deploy_to_slave(master_ip, cluster_ip, 'config')
  File "ovs/extensions/db/etcd/installer.py", line 269, in deploy_to_slave
    info = re.search(EtcdInstaller.MEMBER_REGEX, item).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
2016-05-25 16:08:18 39800 +0200 - OVS-2 - 17375/139777810417472 - lib/setup - 15 - ERROR - 'NoneType' object has no attribute 'groupdict'
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 467, in setup_node
    hypervisor_info=hypervisor_info)
  File "ovs/lib/setup.py", line 1129, in _setup_extra_node
    EtcdInstaller.deploy_to_slave(master_ip, cluster_ip, 'config')
  File "ovs/extensions/db/etcd/installer.py", line 269, in deploy_to_slave
    info = re.search(EtcdInstaller.MEMBER_REGEX, item).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/550

**Comment by JeffreyDevloo** [comment]
### Information

Seeing as this error has been fixed on 25 May and we no longer encountered it during our ETCD setups, the issue has been resolved.

_Default installation steps_

### Steps:
- Installed ovs on three nodes

### Output:

All nodes were installed without error

### Package information:
- ii  openvstorage                       2.7.1-fargo.2-1                                          amd64        openvStorage
- ii  openvstorage-backend               1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin
- ii  openvstorage-backend-core          1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin core
- ii  openvstorage-backend-webapps       1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin Web Applications
- ii  openvstorage-cinder-plugin         1.2.1-fargo.1-1                                          amd64        OpenvStorage Cinder plugin for OpenStack
- ii  openvstorage-core                  2.7.1-fargo.2-1                                          amd64        openvStorage core
- ii  openvstorage-hc                    1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin HyperConverged
- ii  openvstorage-sdm                   1.6.1-fargo.1-1                                          amd64        Open vStorage Backend ASD Manager
- ii  openvstorage-test                  2.7.1-fargo.2-1                                          amd64        openvStorage autotest suite
- ii  openvstorage-webapps               2.7.1-fargo.2-1                                          amd64        openvStorage Web Applications
