### ISSUE TITLE
'avahi-daemon --reload' fails during setup

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#552]
You reload avahi and then restart it as seen here:
https://github.com/openvstorage/framework/blob/master/ovs/lib/setup.py#L1595
Why not just restart it, because sometimes avahi gives problems after installation:

```
root@ctl01:~# avahi-daemon --reload
Failed to kill daemon: No such file or directory    
root@ctl01:~# service avahi-daemon restart
avahi-daemon stop/waiting
avahi-daemon start/running, process 17484
root@ctl01:~# avahi-daemon --reload
```

**Comment by wimpers** [comment]
@kinvaris please create a PR to restart.
