### ISSUE TITLE
Extending vpool does nothing in GUI when directory with same name is already present in /mnt

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#559]
When a directory is present in `/mnt` with the same name as the vPool, you cannot extend the vpool to the that node. The frontent just does nothing when trying to extend it.

```
root@cmp02:/mnt# ls
myvpool-2-a  ssd1  ssd2  ssd3
```

**Comment by wimpers** [comment]
At least an error should be created in this case.

@kinvaris  did something previously went wrong with the cleanup?

**Comment by wimpers** [comment]
Probably the same code path as https://github.com/openvstorage/framework/issues/626

**Comment by wimpers** [comment]
Set to duplicate after discussion with @khenderick .
