### ISSUE TITLE
Set up alba cache-eviction service for a backend when it's used as a cache

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework#562]
Some process will need to evict items from the cache ... towards this end we added `alba cache-eviction`.
You should set up a (bunch of) service(s) for this when a backend is configured to be used as a cache (when setting up a vpool / extending it to a node). You probably want multiple of these services for HA, much like how you do it for maintenance.

`alba cache-eviction --help`
`alba cache-eviction --config /path/to/this/backends/abmcfg --prefix prefix --preset preset`

**Comment by wimpers** [comment]
@domsj reopen if still required but I believe this will be fixed in https://github.com/ovs-projects/org_development/issues/18 by allow the maintenance agents to do cache eviction
