### ISSUE TITLE
Racecondition when two ends of a relation are updated at the same time

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#576]
Version:

```
  Installed: 1.7.0-rev.595.cda7770-1
  Candidate: 1.7.0-rev.595.cda7770-1
  Version table:
 *** 1.7.0-rev.595.cda7770-1 0
        500 http://apt.openvstorage.org/ unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

env:
ctl/cmp nodes: 10.100.199.1-4

When deleting a VM via KVM manager the Vdisk is still available via the GUI.

![vdisk](https://cloud.githubusercontent.com/assets/2900612/15849959/8c1bcbce-2c95-11e6-8734-bc0a251fea17.png)

Vdiks has been removed on the vpool:

```
lroot@cmp01:~# ls /mnt/be-vpool
lQiJLjC7I4drgtmf
```

Vdisk object still exists in the model:

```
In [1]: from ovs.dal.lists.vdisklist import VDiskList
In [2]: vdisk = VDiskList.get_vdisks()[0]
In [3]: vdisk.guid
Out[3]: '7e9dede6-ad66-4a98-8f6b-664baa53c6b8'
In [4]: vdisk.volume_id
Out[4]: u'0007195f-18ee-414a-a6b6-e617a95a2808'
In [5]: vdisk.name
Out[5]: u'test_boe'
```

Exception i found on cmp01:
[ovs-volumedriver_be-vpool.txt](https://github.com/openvstorage/framework/files/302074/ovs-volumedriver_be-vpool.txt)
[ovs-webapp-api.txt](https://github.com/openvstorage/framework/files/302075/ovs-webapp-api.txt)

**Comment by khenderick** [comment]
Also reported by internal ticket OVS-4549

**Comment by khenderick** [comment]
As requested by @wimpers in the internal ticket, it's not related to multiple vDisk deletions at the same time, but related to deleting the vMachine at the same time.

**Comment by saelbrec** [comment]
@khenderick ,
Does the same problem exist in the Eugene-updates code base?

**Comment by khenderick** [comment]
@saelbrec, no, it was introduced in the major DAL refactoring on master. The eugene-updates branch uses extensive (slower) locking.
