### ISSUE TITLE
AlbaCLI wrapper should not ignore errors when executing the command locally

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#579]
if client is None:
    try:
        output = check_output(cmd, shell=True).strip()
    except CalledProcessError as ex:
        output = ex.output

This piece of code makes sure the potential errors are ignored, which we should not do

**Comment by domsj** [comment]
I don't agree with the assessment that this can only be fixed when the linked alba issue has been fixed...

**Comment by wimpers** [comment]
@kvanhijf can you asses the impact of changing this?

**Comment by kvanhijf** [comment]
@Wimpers: this has already been fixed actually, since it was a minor thing to fix
Forgot to close this issue
