### ISSUE TITLE
Dedupe can be selected even if the correct package isn't installed 

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#599]
When creating a  vPool () it is possible to select deduplication while this feature might not be available in the voldrv package of the storage router. We should capture/block this so if the voldrv package without dedupe is installed that you can't select dedupe.

Same issues plays for editing vDisks.

**Comment by khenderick** [comment]
It was previously decided that this would not be required. However, it still makes a lot of sense to do this, but shouldn't we then also check whether the volumedriver is installed at all and block creation of a vpool if not?

**Comment by wimpers** [comment]
For a first version this is ok, for GA we want to fix this.

**Comment by khenderick** [comment]
Seems this one was also fixed by #729

**Comment by deepshirsath** [comment]
Open vStorage: 2.7.1-fargo.1-1

root@ubuntu1:~# dpkg -l | grep volume
ii  volumedriver-no-dedup-base         6.0.3-dev.201607191821.0758481                           amd64        VolumeDriver common infrastructure
ii  volumedriver-no-dedup-server       6.0.3-dev.201607191821.0758481                           amd64        VolumeDriver daemon and helpers

When correct voldrv package i.e without dedupe installed then you can't select dedupe. (you will not see dedupe in drag down list anymore) same applies to vDisk configuration.

![issue-599](https://cloud.githubusercontent.com/assets/14201912/17514935/179ae24a-5e53-11e6-83c8-5b8f3f76e8ef.PNG)
