### ISSUE TITLE
Prevent selecting a domain as recovery domain if it's not primary anywhere

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#600]
Prevent selecting a domain as recovery domain if it's not primary anywhere

**Comment by wimpers** [comment]
I understand that this would lead to  issues but on the other hand this causes annoyance when you set the first Storage Router. You first need to assign the domain to another storage router and next you need to update the first one again. Same if you want to config things automatically.

Maybe a better idea is to have the health check check if there are storage routers which have a recovery domain which aren't set as primary?

@khenderick , @saelbrec wdyt?

**Comment by wimpers** [comment]
The solutions also doesn't protect us if all the storage routers with that primary domain are gone. Health check is the only way to go I believe.

**Comment by khenderick** [comment]
Why put this in another tool if we can as well and with minimum effort put e.g. an exclamation mark next to such selected domain if it has no primary entry yet. The customers can select what they want, and they immediately are reminded of the fact that they still have to set it as primary somewhere.

**Comment by wimpers** [comment]
I like the !-idea. The user can still select what he wants but is reminded that there is an issue. 
Created https://github.com/openvstorage/openvstorage-health-check/issues/258 for  the health check.

**Comment by khenderick** [comment]
Fixed by #1358, packaged in dev openvstorage-2.7.10-dev.1484819295.b90ca13

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
VALIDATED OK:
gui shows:
 No StorageRouter found for: two
a domain for which there is indeed no primary set yet
