### ISSUE TITLE
RAID partition with / on it is seen as empty raw disk.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#604]
![](http://s32.postimg.org/5mr2xjal1/md_bug_partitions.png)

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1032 --> openvstorage-2.7.4-rev.4136.8d34d87
https://github.com/openvstorage/alba-asdmanager/pull/128 --> openvstorage-sdm-1.6.4-rev.388.1f4375d

**Comment by kinvaris** [comment]
### Status
PASSED

### OS
`Ubuntu 16.04`

### Flow
* Added 2 disks to a CI environment
* Created a MD device, added a partition table and added a filesystem
* Mount the MD device
* Check the GUI

### Results
* Top disk is the MD device
* `sdi` & `sdh` are the raid devices

![](http://i.imgur.com/u9vYdfG.png)
