### ISSUE TITLE
Move status on vPool list to front

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#608]
The status of the vPool is now shown as last column of the vPool list page. We should bring the layout inline with the storage router list page and move the status column to the front.

Same for Backend status on the Backends page.

**Comment by khenderick** [comment]
Fixed by #730

**Comment by deepshirsath** [comment]
**Open vStorage: 2.7.1-fargo.1-1**

Status of the vPool is now shown  before the vPool name on 'vPools' list page. (see screenshot)

![vpool-status](https://cloud.githubusercontent.com/assets/14201912/17515758/e7162058-5e57-11e6-8a61-45607b627254.png)

Also status of the backend is now shown before the backend name on 'Backends' list page. (see screenshot)

![backend-status](https://cloud.githubusercontent.com/assets/14201912/17515764/eff33ad0-5e57-11e6-9978-7fe463df16fc.png)
