### ISSUE TITLE
vDisk mgmt actions: bring cache options inline with vPool

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#609]
On a vPool level the cache options are read, write, read/write and no caching. on vdisk level you have read, write  and no caching. We should bring both inline and add read/write to the vDisks caching options.

**Comment by wimpers** [comment]
@khenderick what happens if you set to no cache on vPool level and on vDisk level you override this setting with cache on read?

**Comment by kvanhijf** [comment]
According to the code, the vDisk should use this new setting and will
ignore the global vPool setting

On Mon, Jun 20, 2016 at 11:07 AM, Wim Provoost notifications@github.com
wrote:

> @khenderick https://github.com/khenderick what happens if you set to no
> cache on vPool level and on vDisk level you override this setting with
> cache on read?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/openvstorage/framework/issues/609#issuecomment-227088633,
> or mute the thread
> https://github.com/notifications/unsubscribe/AM6JZr2ZTPxIBj3-r7oqTcPP6M0B8YPNks5qNlhqgaJpZM4I1J4E
> .

## 

_Kevin Van Hijfte, Software Engineer_

www.openvstorage.com http://www.cloudfounders.com/ |
kevin.vanhijfte@openvstorage.com kevin.vanhijfte@cloudfounders.com

_Tel: +32 9 324 25 70_

_Open vStorage, Storage for the Cloudscale Datacenter_

Disclaimer:

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you are not the named addressee or an employee or agent responsible for
delivering this message to the named addressee, you are hereby notified
that you are not authorized to read, print, retain, copy or disseminate
this message or any part of it. If you have received this email in error we
request you to notify us by reply e-mail and to delete all electronic files
of the message. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on the
contents of this information is strictly prohibited.
E-mail transmission cannot be guaranteed to be secure or error free as
information could be intercepted, corrupted, lost, destroyed, arrive late
or incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the content of this message, and
shall have no liability for any loss or damage suffered by the user, which
arise as a result of e-mail transmission.

**Comment by wimpers** [comment]
I see.

This is probably not what we want as this will configure voldrv caching while you want to configure ALBA proxy caching.

@domsj can you configure the alba proxy cache per namespace or is that a global setting per proxy?

**Comment by domsj** [comment]
The type of cache and cache-on-read/write/read&write is currently configured per proxy.

The proxy read_object_rfs  call has a should_cache argument, but I think it only influences caching of the metadata (manifest), while the actual data will be cached anyway (but I have to verify).
The partial read call, which is used to fetch the actual volume data, and write_object_fs - used to write scos/objects - does not have a should_cache argument.

We could expand those calls with some extra flags that the volume driver can then pass on to the alba proxy which would then influence the fragment caching behaviour...

Other options might include:
- expand proxy config file so this can be configured per namespace
- store this info in the albamgr

(but I think passing a bit more information from voldrv to proxy is probably the way to go)

**Comment by wimpers** [comment]
@kvanhijf if you overrule at vdisk level, does it create a file for the cache (if previously set to none)?

**Comment by wimpers** [comment]
cc @pploegaert you are working on a similar ticket.

**Comment by wimpers** [comment]
@pploegaert  I believe this ticket is no longer relevant as there is only fragment cache?  Can I close this one?

**Comment by wimpers** [comment]
No longer relevant. Re-open if needed.
