### ISSUE TITLE
Harden delete vPool

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#623]
Follow up of https://github.com/openvstorage/framework/issues/622

In case you expand a vPool to a node where no KVM is running, you can't delete the vPool.

**Comment by wimpers** [comment]
See https://groups.google.com/forum/#!topic/open-vstorage/TLv9wkQTSVQ for errors

**Comment by wimpers** [comment]
@pploegaert acccording to @kvanhijf the delete vPool is hardened in Fargo so this issue might be already fixed. Can we test?

**Comment by kvanhijf** [comment]
@wimpers : you asked me if an offline node could be removed from a vpool
The issue described here is not yet fixed apparently in Fargo

**Comment by despiegk** [comment]
it's important we can remove a vpool otherwise testing & updating is hard
also for a failed install, you need to be able to remove a vpool & restart

**Comment by wimpers** [comment]
maybe something to do with https://github.com/openvstorage/volumedriver/issues/110

**Comment by matthiasdeblock** [comment]
Had some issues while deleting vpool on GIG's env. Apparently there were some broken disks:

```
2016-09-09 10:02:12 05500 +0200 - stor-201.be-gen8-1 - 27270/139744949352256 - lib/storagerouter - 27460 - ERROR - Remove Storage Driver - Guid 7a1fe95b-9045-4621-82ee-6e62db831aa5 - Synchronizing disks with reality failed with error: Missing fields on disk: is_ssd, path, size

2016-09-09 09:40:46 08200 +0200 - stor-202.be-gen8-1 - 23197/139857426265920 - celery/celery.worker.job - 27301 - ERROR - Task ovs.storagerouter.remove_storagedriver[d9761089-30ce-4311-a149-4b351a47eff4] raised unexpected: RuntimeError('1 or more errors occurred while tr
ying to remove the storage driver. Please check the logs for more information',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1373, in remove_storagedriver
    raise RuntimeError('1 or more errors occurred while trying to remove the storage driver. Please check the logs for more information')
RuntimeError: 1 or more errors occurred while trying to remove the storage driver. Please check the logs for more information

```

**Comment by wimpers** [comment]
Same issue as https://github.com/openvstorage/framework-alba-plugin/issues/174 ?

**Comment by matthiasdeblock** [comment]
@wimpers , in my opinion i think it's related to the issue you've mentioned. 

In the attachment you can find the executed steps on GIG's environment that could help.
[Executed_steps.txt](https://github.com/openvstorage/framework/files/466862/Executed_steps.txt)

**Comment by wimpers** [comment]
Please close #891 if tackled

**Comment by kvanhijf** [comment]
openvstorage-2.7.3-rev.3978.4f93e02
Delete vPool should be re-entrant as of now
It is however impossible to delete a vPool which has still vDisks attached to it. This because shortly we will introduce a feature to be able to migrate vDisks from within the GUI

If an error occured while removing the vPool, it's advised to look in /var/log/upstart/ovs-workers.log or journalctl -u ovs-workers and see what exactly went wrong. Fix the issue at hand and try to delete the vPool again

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest OVS packages
- Setup a hyperconverged setup
- Added disk roles
- Setup backends
- Added Vpool
- Extended vpool

### Test scenarios
- Delete vpool on node that is down (succeeded)
- Delete vpool on node that has vdisk (GUI greyed out, intended)
- Delete vpool on running node (succeeded)

### Test result

Test passed.

Hyperconverged setup
- Three nodes with each three disks for the back-end

### Package information
- openvstorage                       2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage
- openvstorage-backend               1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.134.9ef41c0-1                                  amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.3-rev.357.ee7c9f5-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.3-rev.1012.608f550-1                                 amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage Web Applications
