### ISSUE TITLE
Allow possibility for customer to decide between performance and data protection regarding the DTL

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#625]
We can prioritize to configure the DTL for vDisks on the recovery domain(s) specified or on the regular domain(s) specified
With the regular domains prioritized, we have better performance, but could potentially have some data loss
With the recovery domains prioritized, we have a bit less performance, but are better protected from data loss

**Comment by wimpers** [comment]
I've extended this issue in  https://github.com/openvstorage/framework/issues/1165 and hence closing this one down as duplicate.
