### ISSUE TITLE
DTL not displayed correctly on single node

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#640]
DTL not displayed correctly on single node. Issue present on Fargo and Unstable.

**Comment by wimpers** [comment]
@khenderick what is displayed? what does it break

**Comment by khenderick** [comment]
The DTL status is reported as `unknown` and the vMachine name is not immediately shown on the vPool detail page.

**Comment by khenderick** [comment]
Most likely already solved, cannot reproduce

**Comment by deepshirsath** [comment]
- Installed single node with ovs build :- Open vStorage: 2.7.1-fargo.1-1
- Imported ubuntuos disk as raw in the vpool.
- Checked status on ovs gui for that disk under 'vDisks' which showed Healthy (Standalone) (screenshot attached)

![dtl-healthy-640](https://cloud.githubusercontent.com/assets/14201912/17479976/45c29ad4-5d93-11e6-9082-f78b2a178034.png)
