### ISSUE TITLE
Fix SNMP server

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#646]
By @khenderick 's request. An issue to fix the SNMP server code

Certain codepaths should fail, but i have no prove. Found out by looking in the code

eg:  self._register_dal_model(0, vm, 'hypervisorid', "7")  --> vmachine does not have attribute hypervisorid, but hypervisor_id instead

**Comment by khenderick** [comment]
A bunch of error are spit out when trying to walk through the data:

```
[EXCEPTION] 'VMachine' object has no attribute 'hypervisorid'
[EXCEPTION] 'VMachine' object has no attribute 'ip'
[EXCEPTION] 'VMachine' object has no attribute 'hypervisorid'
[EXCEPTION] 'VMachine' object has no attribute 'ip'
[EXCEPTION 2] invalid literal for int() with base 10: 'OK_STANDALONE'
[EXCEPTION 2] invalid literal for int() with base 10: 'OK_STANDALONE'
[EXCEPTION 2] invalid literal for int() with base 10: 'OK_STANDALONE'
[EXCEPTION] 'StorageRouter' object has no attribute 'devicename'
[EXCEPTION] 'StorageRouter' object has no attribute 'dtl_mode'
[EXCEPTION] 'StorageRouter' object has no attribute 'machineid'
```

Apart from that, almost nothing of the expected values is returned.

Command used: `snmpwalk -Os -c public -v 1 10.100.169.100:161 1.3.6.1.4.1.29961`

**Comment by wimpers** [comment]
Won't fix but we will remove in https://github.com/openvstorage/framework/issues/678
