### ISSUE TITLE
dpkg-query: package 'volumedriver-server' is not installed and no information is available

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#649]
root@ovs01:~/dev_ops/Ansible/traffic_shaping# apt-cache policy openvstorage
openvstorage:
  Installed: 2.7.0-rev.3624.ec9cec4-1
  Candidate: 2.7.1-rev.3669.10063a2-1
  Version table:
     2.7.1-rev.3669.10063a2-1 0
        500 http://apt.openvstorage.org/ unstable/main amd64 Packages
 **\* 2.7.0-rev.3624.ec9cec4-1 0
        100 /var/lib/dpkg/status

2016-06-22 14:56:07 68100 +0200 - ovs03 - 42181/140529442326336 - celery/celery.worker.job - 284 - DEBUG - Task accepted: ovs.storagerouter.get_version_info[edbab5b8-4f7d-45fa-9db4-80e62516192b] pid:45331
dpkg-query: package 'volumedriver-server' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'volumedriver-base' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'volumedriver-server' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
dpkg-query: package 'volumedriver-base' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

**Comment by khenderick** [comment]
Fixed by #661
