### ISSUE TITLE
vPool fails to remove from storage router without reason

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#650]
I removed my vPool and it failed, checked the logs and it failed at this point:
https://github.com/openvstorage/framework/blob/master/ovs/lib/storagerouter.py#L1484

When checking the `lib.log`, it contained no errors. 

When checking some nodes, I saw that the albaproxy services where not cleaned up. Which leaded to the failure of creation of another vPool with the same name.

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/framework/issues/623
