### ISSUE TITLE
the framework should require omniorb to be installed

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework#651]
The volumedriver doesn't require this package / service to be present and running, but it does need it when configured to use shared memory.
By default the framework configures the voldrv to use shared memory, so it's the frameworks responsibility to ensure the package gets installed and that the omniorb service is running (when the voldrv is started).

**Comment by redlicha** [comment]
The service that is needed is called 'omniNames' and comes with the omniorb-nameserver package.

**Comment by khenderick** [comment]
Doesn't this conflict with #665 where we disable SHM by default?

**Comment by khenderick** [comment]
After discussion with @saelbrec, wait for this ticket until SHM needs to be enabled (by default) again.

**Comment by khenderick** [comment]
Removed milestone and priority because it's on hold anyway.

**Comment by wimpers** [comment]
The dependency should be on the voldrv package. The voldrv can be used without the framework.

**Comment by khenderick** [comment]
@wimpers, it's an optional requirement for the volumedriver as the shared memory is by default enabled. In any case, if it should be a dependency, please move the ticket to the volumedriver repository.
