### ISSUE TITLE
Make sure errors in GUI display correctly

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#659]
Make sure errors in GUI display correctly. Now we use `error` and/or `error.responseText` and only one of both works, depending on when the error occurs.

**Comment by wimpers** [comment]
Assigned to you as you seem to know the exact issue.

**Comment by khenderick** [comment]
Resolved by #690

**Comment by deepshirsath** [comment]
**_Open vStorage 2.7.1-fargo.3-1_**
- Error shows exact issue (see the screenshot)

![errorclear](https://cloud.githubusercontent.com/assets/14201912/17929401/f2dadd12-6a1d-11e6-8f6d-3bcbdebccc75.png)
