### ISSUE TITLE
Claiming ASDs previously claimed by another backend throws unclear error

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#660]
Scenario:

Backend 1, backend 2 --> both 0 ASDs initialized
On backend 1 initialize some ASDs and claim a subset of them
Go to backend 2 detail page. Here you'll see the same amount of initialized ASDs, but the fact that some of them had been claimed takes a while for the code to 'see'
When clicking the claim all button on backend 2 detail page, i'd expect the unclaimed ASDs to be claimed and a clear error thrown that some ASDs could not be claimed, because they're already claimed by another backend
However this is not the case, there is an error thrown saying: No JSON object could be decoded

**Comment by wimpers** [comment]
@pploegaert can you see if this breaks anything?

**Comment by khenderick** [comment]
This issue was moved to openvstorage/framework-alba-plugin#154

**Comment by pploegaert** [comment]
It's quite easily reproducible ... and the error is shown as reported above ... 
It doesn't break anything at first sight ... but I'd fix this ...
- it doesn't give a good impression when setting up a backend already raises an error
- every customer running into this will contact support -> ticket -> engineering ... So we should avoid this ticket roundtrip anyway in favor of a better product impression.

**Comment by khenderick** [comment]
Most likely a misunderstanding here. This is the original ticket that was just reported on the wrong repo.
