### ISSUE TITLE
Remove hypervisor dependencies

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#666]
Currently we are relying on the hypervisor for some actions. With the Edge there will no longer be a hypervisor on the host.

Specs: https://github.com/openvstorage/framework/pull/668

Fixes also https://github.com/openvstorage/framework/issues/622

**Comment by wimpers** [comment]
@kvanhijf @khenderick , please check spec

**Comment by kvanhijf** [comment]
We did, there's nothing in it ;)

**Comment by JeffreyDevloo** [comment]
### Steps
- Checked the spec file
- Fixed some issues
  ### Test result
  Test passed (after merging)
  Closing.
