### ISSUE TITLE
Error aftere deleting a bad storage router from the vpool configuration page

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#667]
Vpool status went in failure state due to a missing package (virsh). After resetting the vpool status to 'RUNNING' i removed the storage router in the vpool configuration page and tried to delete the infected storage router. The delete failed with the following output:

```
2016-06-24 11:29:18 85600 +0200 - ovs04 - 79587/140489044752192 - celery/celery.worker.job - 9593 - ERROR - Task ovs.storagerouter.remove_storagedriver[efa8427b-0463-4b4d-8b47-3b2f618b3b8e] raised unexpected: RuntimeError('Not all StorageDrivers are reachable, please (re)start them and try again',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1157, in remove_storagedriver
    raise RuntimeError('Not all StorageDrivers are reachable, please (re)start them and try again')
RuntimeError: Not all StorageDrivers are reachable, please (re)start them and try again
```

**Comment by wimpers** [comment]
@matthiasdeblock  I believe there was a node wiped (but still accessible by IP)? Did you try to put the Storage router offline?

@khenderick  I believe in this case the 'putting the storage router offline' fixes this kind of scenarios?

**Comment by khenderick** [comment]
@wimpers, no the "putting the storage router offline" (assuming you mean the button "Mark this node Offline") won't help, the remove vPool logic required all storagedriver processes to be online as it needs to inform them about the changed configuration. The only solution here is getting the process started and try again (ymmv here) or remove the StorageRouter from the cluster completely (executing `ovs remove nodes <ip>`)

**Comment by saelbrec** [comment]
@khenderick ,
I think @wimpers means if 'ova remove nodes <ip>' would work if the node is shutdown.

**Comment by khenderick** [comment]
@saelbrec, this should also work but there's a ticket open that this is currently broken.

**Comment by khenderick** [comment]
@wimpers, you assigned the `type_bug` label; can you explain how you see this as a bug? The framework can't reliably shrink a vPool if not all StorageDrivers are running since they all need to be informed about the change.

**Comment by wimpers** [comment]
There should always be an option to get out of this deadlock kind of scenario. A force remove should be possible like we do with the "Mark this node Offline".  If you invoke the force remove, you better make sure it doesn't come back.

**Comment by khenderick** [comment]
The "remove vPool"-logic has been cleaned up to be more resilient to challenging situations. Please reopen/verify if still an issue.

**Comment by JeffreyDevloo** [comment]
### Information
We do not have virsh as a dependency anymore. We are unable to reproduce the issue.

If a similar error occurs, please open up a new ticket with more detailed information.
