### ISSUE TITLE
Albaproxy is killed by upstart if volumedriver can't start

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#684]
This should be removed from every `albaproxy`:
`stop on stopped ovs-volumedriver_all-flash-local-roub`

**Comment by khenderick** [comment]
Why should this be removed? It's a runtime dependency for the volumedriver and should not be running if the volumedriver process is not running.

**Comment by wimpers** [comment]
Maybe we should revisit this in the light of RDMA and the scrubber that can use a remote proxy.

**Comment by khenderick** [comment]
@wimpers, this ticket was apparently qualified (milestone set to Fargo), so what needs to be done here? What's the issue we want to fix here in the first place? We need at least a benefit that justifies the extra work.

**Comment by wimpers** [comment]
I had a discussion with @saelbrec about this. In the old days we could take the decision to shoot the albaproxy if the voldrv wouldn't start as they were on the same node but we see cases where the voldrv. So having this dependency doesn't hold anymore. Do check with Stefaan for details.

**Comment by khenderick** [comment]
I still don't think this ticket makes much sense:
- The volumedriver and alba proxy must share a filesystem, so they must run on the same node
- When scrubbing a separate scrub-only proxy is deployed (and cleaned up afterwards).

What's the usecase of a running alba proxy without a volumedriver using it?

**Comment by wimpers** [comment]
After discussion with @khenderick : having the voldrv not on the same box as the proxy isn't supported atm. if this scenario should be supported , more actions will be required (https://github.com/openvstorage/volumedriver/issues/150). 

Hence closing this ticket down with won't fix. If you ( @kinvaris , @saelbrec ) disagree, please re-open and provide a use case.
