### ISSUE TITLE
Only one crash dump per application is preserved

### ISSUE THREAD

**Issue by redlicha** [openvstorage/framework#685]
Together with this volumedriver bug https://github.com/openvstorage/volumedriver/issues/51 this prevents investigating the root cause of said bug (there's of course a tradeoff to be made of keeping enough history vs. filling the system up with crash dumps).

**Comment by khenderick** [comment]
@redlicha, what's expected on the framework? Is this a volumedriver settng we need to change?

**Comment by redlicha** [comment]
@khenderick, my fuzzy, high level expectation is that the operating system (or more specifically apport) is configured to preserve a bigger number of core dumps.

**Comment by khenderick** [comment]
@wimpers, I assume that is a request for documentation? Do we need a ticket here, or on some docs repo?

**Comment by wimpers** [comment]
This issue was moved to openvstorage/ovs-documentation#14
