### ISSUE TITLE
ovs-albaproxy service remains in stop/waiting at vpool shrink

### ISSUE THREAD

**Issue by mnuca** [openvstorage/framework#689]
used the following scenario:

3 node grid
created an alba backend spread on all 3 nodes
created a vpool on the main node
extended the vpool to the other two nodes
vpool creation ok
tried shrinking the vpool back to one node
ovs-albaproxy service remains in stop/waiting on the two nodes that were just shrinked
when removing the vpool from the 3rd node ovs-albaproxy service gets deleted but the remnants of the other 2 nodes are left as is

**Comment by khenderick** [comment]
Fixed by #726

**Comment by deepshirsath** [comment]
**PASSED** on **Open vStorage: 2.7.1-fargo.3-1**
- Setup 3 node grid
- Created an alba backend spread on all 3 nodes
- Created a vpool on the main node
  ![pool-created](https://cloud.githubusercontent.com/assets/14201912/17625485/b9c48132-60c6-11e6-97e1-452d997f020a.PNG)
- Extended the vpool to the other two nodes

![pool1-extended](https://cloud.githubusercontent.com/assets/14201912/17625504/d5e42ba6-60c6-11e6-975f-a8ae2510ce6e.PNG)
- Before shrink 'ovs monitor services' status

![before-shrink-n2](https://cloud.githubusercontent.com/assets/14201912/17625571/1aec1b8c-60c7-11e6-93f1-10b7bed699eb.PNG)
![before-shrink-n3](https://cloud.githubusercontent.com/assets/14201912/17625578/1f087d78-60c7-11e6-9e43-aa9cd220e908.PNG)
- Tried shrinking the vpool back to one node which was completed without any issues. (removed node 2 and 3)

![pool-shrinked](https://cloud.githubusercontent.com/assets/14201912/17625596/2875f534-60c7-11e6-9816-cf17534f4bc1.PNG)
- After shrink 'ovs monitor services' status

![after-shrink-n2](https://cloud.githubusercontent.com/assets/14201912/17625616/3c686c02-60c7-11e6-8b84-63ff16c05775.PNG)
![after-shrink-n3](https://cloud.githubusercontent.com/assets/14201912/17625621/40002a94-60c7-11e6-850d-4131756f7332.PNG)
- ovs-albaproxy service did not went in stop/waiting on the two nodes that were just shrink-ed (node 2 and 3)
- Unable to re-produce, hence closing.
