### ISSUE TITLE
When configuring a role on a disk when another role is being configured, you get only one role.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#694]
When configuring a role on a disk, it is possible to assign another role on that disk. But If you do that when another role is being configured it overwrites the amount of roles.

**Comment by khenderick** [comment]
If I understand it correctly, you did the following:
- Assign role X to disk A, partition B
- Assign role Y to disk A, partition B

And disk A, partition B ended up with only role Y

Isn't that expected, as the second time, you explicitly selected only Y out of the possibilities X, Y and Z. If you would expect both X and Y to be assigned, I'd expect that you selected both X and Y the second time.

Or am I missing something?

**Comment by khenderick** [comment]
Technical information: The task to assign roles to a disk runs in chained mode; it can only process one disk role assignment task after one other (resulted in another ticket to speed things up). In the above case (assumed on the small amount of info we got in the report) it handled both requests subsequently and when the second task was processed (assign role Y to disk A, partition B) it did exactly as it was asked to.
