### ISSUE TITLE
RDMA flag in pre-configuration not working

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#695]
When trying to deploy OVS with RDMA through the pre-configuration. It gives this result:
`Errors found while verifying pre-configuration:\r\n - Key rdma is not supported by OpenvStorage to be used in the pre-configuration JSON`

**Comment by khenderick** [comment]
Resolved by #697

**Comment by kinvaris** [comment]
PASSED: RDMA setup completed without problems while always using the RDMA key in the pre-config.
`{"setup": {"cluster_ip": "10.100.199.161", "master_password": "rooter", "enable_heartbeats": true, "master_ip": "10.100.199.161", "node_type": "master", "rdma": false}, "asdmanager": {"api_ip": "10.100.199.161", "asd_ips": ["10.100.199.161"], "api_port": 8500}}`
