### ISSUE TITLE
Allow role assignment in parrallel

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#696]
When assigning a role to a disk. The disk in question is format at first then the filesystem is added and then the role is added. This happens in a sequential way, thus it takes a long time if you have 50 + nodes.

This should happen in parallel so we can make the general setup faster.

**Comment by wimpers** [comment]
@khenderick  any reason why we do this sequential and not in parallel?

**Comment by khenderick** [comment]
There were issues in the past and back then we choose the easy solution of executing them sequential. Most likely some actions can be executed in parallel but we'll have to test and see what's possible there.

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/framework/issues/514 ?

**Comment by khenderick** [comment]
@wimpers, indeed.

**Comment by wimpers** [comment]
This has been made faster. Please re-open this ticket if needed ( and add timings) if this would still be an issue.
