### ISSUE TITLE
Setup hangs when it is not able to SSH keyscan to other nodes

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#701]
When a node is not able to ssh to another node via a certain IP or subnet, the setup hangs at SSH keyscan. 

The command is executed on these lines: https://github.com/openvstorage/framework/blob/master/ovs/lib/setup.py#L350 & https://github.com/openvstorage/framework/blob/master/ovs/lib/setup.py#L351.

A timeout should be introduced so if it is not able to SSH, the setup fails with a decent and clear error.

**Comment by khenderick** [comment]
Resolved by #714

**Comment by kinvaris** [comment]
PASSED: `2.7.2-rev.3867.ec9d46d-1`. When the setup cannot ssh to other nodes via a certain IP address it will time out and give an error: `Timeout during ssh keyscan, please check node interconnectivity`
