### ISSUE TITLE
If session was expired, then auto-logout did not work

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#703]
If session was expired, then auto-logout did not work

**Comment by khenderick** [comment]
Fixed by #702

**Comment by deepshirsath** [comment]
Cluster ID: R4AGIzjN0LyULKqj

Storage Routers:
ubuntu1: TLEcQFNOPSrQaGbt  
ubuntu2: 3M4N4clQ4cL3ZADM  
ubuntu3: YDJJdnMx7hLHtHHv      

Open vStorage: 2.7.1-rev.3756.f2510a0-1
Open vStorage - Backend: 1.7.1-rev.635.b81d605-1
Open vStorage - SDM: 1.6.1-rev.327.9490bc3-1
Storage Driver - Base: 6.0.1-dev.201607041405.f07e34a
Storage Driver - Server: 6.0.1-dev.201607041405.f07e34a
Alba: 0.9.13
Arakoon 1.9.7
- Installed 3 node cluster with OVS unstable build '2.7.1-rev.3756.f2510a0-1'
- When logging in after installation, OVS gui asked for login credentials. (Screenshot attached)

![asked-login](https://cloud.githubusercontent.com/assets/14201912/16768458/16a4e28e-4862-11e6-8a1d-5227dd7802fe.PNG)
