### ISSUE TITLE
remove ovs-volumerouter-consumer process from ovs monitor services on non-master nodes

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#704]
ovs-volumerouter-consumer is not implemented anymore but is still a "running" process.

**Comment by khenderick** [comment]
Since the vMachine removal this service doesn't have a use on non-master nodes so it should not be deployed on these nodes. At this point, it terminates itself, but is then restarted by upstart (and this repeats)

**Comment by khenderick** [comment]
Resolved by #712

**Comment by pploegaert** [comment]
PASSED - env 10.100.131.6x - 4th node output

<img width="368" alt="screen shot 2016-08-08 at 10 48 17" src="https://cloud.githubusercontent.com/assets/8393135/17474380/dbf90bca-5d55-11e6-94ef-d751a9f64a59.png">
