### ISSUE TITLE
Create vPool wizard times out on ALBA backend fetching

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#716]
In case you have many backends, the create vPool wiward will not load the ALBA backend due to a timeout. 

> we load all information about all possible backends, which times out in this case
> can be optimized by only loading the required information, being the name and preset information

**Comment by kvanhijf** [comment]
vPool wizard has been updated to only load the relevant ALBA backend data. Still, loading the 'presets' information can take quite some time and perhaps we should finetune this in another ticket

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed a 3 node setup
- Added 25 backends (preset 1,1,1,1)
- Initialized 50 disks
- Claimed 2 for each backend
- Initialized vPool wizard and looked at the networking happening

### Output

Got all backend information necessary

### Test result

The wizard does not timeout any longer but it is still not optimized.
See: https://github.com/openvstorage/framework/issues/837
Closing.

### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications
