### ISSUE TITLE
Storage Router Detail page: add vDisk tab

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#725]
Currently it is hard to find out which vDisks are attached to which Storage Router. With the fact that we allows vDisks to migrate between datacenters it only become more complicated. Hence adding the vDisk tab to the Storage Router Detail page would make things easier to find out.

Use same layout as on the vpool detail page. Icon can be the vDisks icon as used on the vPool detail page. Use http://fontawesome.io/icon/server/ for the physical disk tab.

**Comment by pploegaert** [comment]
PASSED - 2.7.1-fargo.1-1
![screen shot 2016-08-08 at 12 59 52](https://cloud.githubusercontent.com/assets/8393135/17477890/35c4814a-5d68-11e6-83f6-ce7303e030b1.png)
![screen shot 2016-08-08 at 12 59 41](https://cloud.githubusercontent.com/assets/8393135/17477888/35c28228-5d68-11e6-9168-6e0993efbbab.png)
![screen shot 2016-08-08 at 12 59 20](https://cloud.githubusercontent.com/assets/8393135/17477889/35c34c12-5d68-11e6-86f1-7536a5aaf9b9.png)
![screen shot 2016-08-08 at 12 59 02](https://cloud.githubusercontent.com/assets/8393135/17477887/35c1dcb0-5d68-11e6-9597-7c1a60147c6a.png)
