### ISSUE TITLE
add vpool wizard reports unrelated error

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#732]
When adding vpool with local alba backend, 2nd screen shows:

![image](https://cloud.githubusercontent.com/assets/8393135/16979007/33f5bacc-4e5f-11e6-9173-5e4e052f608b.png)

**Comment by khenderick** [comment]
Some more information on reproducing; add a vpool with only a single backend available on the local node which is used as primary backend.

**Comment by khenderick** [comment]
Resolved by #737

**Comment by khenderick** [comment]
In the future, please provide some more information on how to reproduce, that can save me some time.

**Comment by pploegaert** [comment]
PASSED on 2.7.1-fargo.1-1
