### ISSUE TITLE
vPool should show info about its backend!

### ISSUE THREAD

**Issue by deepshirsath** [openvstorage/framework#735]
**Please consider this is as a feature request.**
- When we add backend and assign vpool for that backend...no information is being displayed anywhere which vpool belongs to which backend.
- On backend or on vpool no where we can point...which vpool is configured for which backend.
- Means backend also does not show any info related to vpool and Vpool properties also does not show any info related to its backend.

We could put it on the vpool detail page if possible!  

![backend-properties](https://cloud.githubusercontent.com/assets/14201912/17030129/ae447534-4f8b-11e6-8ac8-70526ea49fd4.PNG)
![backend-view](https://cloud.githubusercontent.com/assets/14201912/17030126/ae3ee042-4f8b-11e6-81ea-3173347abe5c.PNG)
![pool-properties](https://cloud.githubusercontent.com/assets/14201912/17030128/ae43e3da-4f8b-11e6-91c6-d5960e5774d4.PNG)
![pool-view](https://cloud.githubusercontent.com/assets/14201912/17030127/ae426b86-4f8b-11e6-8804-f00c3a96ab0d.PNG)

**Comment by khenderick** [comment]
It was requested to be removed from the backend page. On the vPool detail page, we can indeed show some more information since we have it available anyway.

**Comment by khenderick** [comment]
It's relatively easy; few hours of work

**Comment by wimpers** [comment]
Please provide mockups/specs.

**Comment by wimpers** [comment]
On the vPool Detail page (under Backend):
- If an OVS backend, name + link to the backend; next line: preset name
- If an external OVS backend or S3: login and next line connection info
- Write speed 
- Read speed

**Comment by khenderick** [comment]
From #998 by @kinvaris:

> Currently we get not much information about what backend is linked to what vPool. Only the preset.
> Maybe the vPool page should provide more information about:
> (Possible) Alba Accalerated Alba backend and used preset
> Linked backend and used preset

**Comment by wimpers** [comment]
Since the accelerated ALBA is depending on the Storage Router, I don't see how we can add that to the vPool page. I created https://github.com/openvstorage/framework/issues/1000 to tackle that.

**Comment by kinvaris** [comment]
@wimpers : don't you mean storagedriver? 
When looking at the `extending` page you can add the accelerated ALBA there. And display the underlying backend on the main vpool page.

**Comment by wimpers** [comment]
Good point by @kinvaris 

Add the Accelerated ALBA to the Storage Routers serving this vPool part under the Management actions tab. Updated https://github.com/openvstorage/framework/issues/852 with the same

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1130 --> openvstorage-2.7.5-rev.4273.d9bb7fb
https://github.com/openvstorage/framework-alba-plugin/pull/267 --> openvstorage-backend-1.7.5-rev.811.c1b83e6

**Comment by kvanhijf** [comment]
vPool overview page, shows information on the backend used
vPool detail page, shows information on the backend used
vPool detail page --> management actions shows information on the accelerated backend used / storagerouter

**Comment by kinvaris** [comment]
### Status
PASSED

### OS
`Ubuntu 16.04`

### Steps
* Go to vPools page
* Go to tab `management actions`

### Result
![](http://i.imgur.com/8OjxWAr.png)
