### ISSUE TITLE
Implement Edge in GUI

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#739]
Implement Edge in GUI

Story: ovs-projects/org_development#35

**Comment by khenderick** [comment]
Fixed by #730

**Comment by kinvaris** [comment]
PASSED: This is now visible in front of every vdisk. When no edge clients are connected: `No Edge Clients Connected`. When there are edge clients connected it will give the IP address of the connected clients. `2.7.2-rev.3867.ec9d46d-1`
