### ISSUE TITLE
After vDisk migration the snapshot list is empty

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#745]
If you have a vDisk with snapshots and you move the vDisk to another Voldrv, for some time the snapshot list will be empty.

**Comment by wimpers** [comment]
To be investigated what the issue exactly was

**Comment by saelbrec** [comment]
@pploegaert ,
Can you please coordinate the required steps to be taken:
- Troubleshooting or issue identification
- Test or autotest creation
