### ISSUE TITLE
After creating a vpool, we cannot change the DTL of a vdisk

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#746]
When trying to change the vdisk its settings after initializing a vpool:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 668, in set_config_params
    raise ValueError('If DTL mode is Asynchronous or Synchronous, a Domain guid should always be specified')
ValueError: If DTL mode is Asynchronous or Synchronous, a Domain guid should always be specified
```

When I put the DTL settings on `disabled`, I can change the settings again.

Is this error referring to `domains` and `recovery domains`? Because if so, we should be notified during the vpool creation.

**Comment by khenderick** [comment]
It is referring to Domains en RecoveryDomains, but it's more likely the check that's incorrect as without domains it should assume to not work with domains at all.

**Comment by pploegaert** [comment]
scenario:
- 3 node setup
- create backend / vpool / vdisk on each node member
- change setting of vdisk + click save
- add 2 domains
- assign 1st domain as domain / 2nd as shown in screenshot:
  ![screen shot 2016-08-08 at 14 06 42](https://cloud.githubusercontent.com/assets/8393135/17479511/3a0ad654-5d73-11e6-86a3-1798a495d161.png)
- change setting of vdisk + click save
- change DTL setting of vdisk on storagerouter2 - deselect recovery domain - fails as expected but without clear error. - separate ticket already exists to handle this: https://github.com/openvstorage/framework/issues/691
