### ISSUE TITLE
setup rollback should be optional

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#748]
When a exception occurs during the setup a rollback is performed.
A rollback is good but it deletes all evidence to repair or investigate any problems during the setup.
It would be good to make this rollback optional with a flag like: `ovs setup --no-rollback`

**Comment by khenderick** [comment]
Generally speaking, the logging should be sufficient to see what went wrong, and the rollback should not mess up the environment even more.

I like the `--no-rollback` idea.

**Comment by kinvaris** [comment]
Indeed logging should normally be sufficient to go further but it is always good to have the system in that failed state so you can test stuff for yourself eventually to improve the software.

**Comment by wimpers** [comment]
What do you think about the following: by default we ask the question whether we need to rollback [y/n]? Optional add a `--rollback`  for automated installs where you don't care and just want go on and try again.

**Comment by khenderick** [comment]
I'd rather not ask that question, generally speaking you want a rollback, so just another question just makes the setup more cumbersome.

**Comment by kvanhijf** [comment]
Suggestion: Only when a preconfig is used, one can decide whether rollback
should be done or not
rollback : true/false

**Comment by wimpers** [comment]
**Decision from BAM:**
- By default no rollback 
- Add option `ovs setup --rollback`

**Comment by khenderick** [comment]
Implemented in #1204

**Comment by pploegaert** [comment]
seems actual parameter is:
--rollback-on-failure

**Comment by pploegaert** [comment]
validation steps via keeping a port in use (e.g. memcache: 11211)

/etc/init.d/memcached stop
nc -4 -k -l -v localhost 11211 &
ovs setup --rollback-on-failure

**Comment by pploegaert** [comment]
Seems this task is incomplete
By default no rollback is triggered, option is available, outcome is unpredictable unless we take up
https://github.com/openvstorage/framework/issues/1370

VALIDATION for this ticket is OK
