### ISSUE TITLE
'Add vPool'-wizard still not good enough

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#755]
On the StorageDriver configuration page, the global write buffer size can be specified, but is overwritten each time when clicking Next or Previous. Eg: I select 100GiB, click next, click previous --> Size is overruled again to 1500GiB

Another issue is the over-allocation errormessage is displayed by default
This can be reproduced on 10.100.193.154 by setting following roles on node1:
- /dev/sdb: READ, WRITE
- /dev/sdc: DB, WRITE
  Total available write buffer space is 1573, but GUI suggests 1574, which is indeed too much

**Comment by khenderick** [comment]
Relates to #1198

**Comment by wimpers** [comment]
Fix https://github.com/openvstorage/framework/issues/1332 also when working on this

**Comment by kvanhijf** [comment]
Cannot reproduce any of above scenarios
Probably due to latest vPool wizard rework

**Comment by kvanhijf** [comment]
Shouldn't have closed probably

**Comment by pploegaert** [comment]
Cannot reproduce either -> closed
