### ISSUE TITLE
Restrict usage of external backends

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#758]
If you are a provider of external backends you can atm not limit the backends that are exposed and to who. This feature request is to allow this:
- In the GUI: 
  - Allow to define which users & clients has access to which backends.
  - Create a new group 'Backends', which only has access to the backends page.
- IN the api: list backends call should check which backends the user & clinet have access to and only list those.

**Comment by saelbrec** [comment]
What's the reason for only doing this on backends? Or is the FR to do the same on vpool, vdisk and vTemplate in different issue? We need the same functionality on those levels.

**Comment by khenderick** [comment]
Fixed by #780

**Comment by JeffreyDevloo** [comment]
Cannot close this issue due to other issues that arose with this feature:
Validation failed:
- #827 (Done)
- #826 (Done)
- #825 (Done)

**Comment by JeffreyDevloo** [comment]
Can be closed as the other issues have been tackled.
