### ISSUE TITLE
Allow configuration from arakoon

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#782]
Allow configuration from arakoon. Story: ovs-projects/org_development#44
- [x] Support Etcd and Arakoon for configuration
- [x] Change setup to be able to setup a filesystem backed arakoon for configuration management
- [x] Single entry volumedriver config
- [x] Update volumedriver config code to work with Etcd and Arakoon
- [x] Update all service file generating code to work with Etcd and Arakoon
- [x] Make sure the cacc is distributed automatically by the watchers

**Comment by khenderick** [comment]
- [ ] Support Etcd and Arakoon for configuration
- [ ] Update volumedriver config code to work with Etcd and Arakoon
- [ ] Update all service file generating code to work with Etcd and Arakoon
- [ ] Make sure the cacc is distributed automatically by the watchers

**Comment by khenderick** [comment]
Fixed by #810

**Comment by JeffreyDevloo** [comment]
### Information
We currently use arakoon as our deploy configuration management. Testing is mainly done with arakoon as configuration management as well.
