### ISSUE TITLE
Add vPool, small inconsistency

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#783]
Small inconsistency on 4th tab

Validate whether the required cache sizes are correct.

> Write Buffer: 168 GiB

Should be "Global write buffer"

**Comment by wimpers** [comment]
@kvanhijf  should be a small one to fix

**Comment by khenderick** [comment]
Seems to be already fixed.

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool

### Output

The proposed name has been implemented.
![selection_112](https://cloud.githubusercontent.com/assets/17570109/19438181/e62ad4ca-9478-11e6-8b50-748987a6bb02.png)
Edit: forgot to add a screenshot for the last tab:
![selection_008](https://cloud.githubusercontent.com/assets/17570109/19479811/c4c9c3b0-9548-11e6-8530-d4f16bf18f7e.png)

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications

**Comment by wimpers** [comment]
@JeffreyDevloo it is on the validation step (last screen of the wiward). The screenshot is pre-validation.

**Comment by JeffreyDevloo** [comment]
The last tab was also checked, forgot to include a screenshot. Fixed.
