### ISSUE TITLE
Frontpage overview of global backends should be listed as backends/ASDs not ASDs only.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#795]
![](http://i.imgur.com/pZr0jf1.png)

Instead of only `ASD`, this should be: `Backend/ASD`
![](http://i.imgur.com/gq2SBNh.png)

**Comment by khenderick** [comment]
Feel free to do pull requests for text changes; all translations are in https://github.com/openvstorage/framework/blob/master/webapps/frontend/locales/en-US/ovs.json.

Other options: just call it OSDs (then it's correct either way), or call it ASDs in case of "Local Backends" and "Backends" in case of "Global Backends". But I'd rather call it just "OSDs", so it's always correct, even if we start using e.g. kinetic drives again.
