### ISSUE TITLE
DTL status shows healthy for vDisk in DTL disabled case.

### ISSUE THREAD

**Issue by deepshirsath** [openvstorage/framework#800]
**_Open vStorage: 2.7.1-fargo.1-1_**
- When we disable the DTL while creating the vPool and then import the vDisk in to vPool, still its DTL status shows 'healthy standalone'

![dtl-disabled-1](https://cloud.githubusercontent.com/assets/14201912/17561287/f6e1dc98-5f42-11e6-9645-ec00e5b3e636.png)

![dtl-disabled](https://cloud.githubusercontent.com/assets/14201912/17561298/00135058-5f43-11e6-8ef2-18e9c06d191a.png)
- vDisk DTL status should be something else than healthy in DTL disabled scenario.

**Comment by khenderick** [comment]
The volumedriver reports - in this case - the status as `ok_standalone`, which is in the GUI translated to the message reported. An option could be to add some code that returns some other status when the status is `ok_standalone` and the DTL is disabled.

**Comment by wimpers** [comment]
I would use a grey color instead of green if no DTL configured.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1350 --> openvstorage-2.7.10-dev.1484667229.0ab83af

**Comment by kvanhijf** [comment]
@QA:
DTL for vDisks in GUI will be grey in following scenarios:
* DTL is globally disabled on the vPool
* DTL has been manually configured to disabled via the vdisk-detail page

The DTL for a vDisk should consistently be correctly displayed on all pages:
* vDisk overview page
* vDisk detail page
* vPool detail page --> vdisks tab
* StorageRouter detail page --> vdisks tab

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by JeffreyDevloo** [comment]
Closing because it solely handles about GUI.
