### ISSUE TITLE
Creating back-end during the removal of a node will freeze the back-end on the installing status

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#804]
# Problem description

Creating back-end during the removal of a node will freeze the back-end on the installing status
I suspect that it will generally break anything when the setup changes.

Also I found that when I added a new back-end, while the other was stuck on installing, that the newly installing one disappears from the GUI.
# Possible root of the problem

Workers restart during the remove nodes procedure
# Possible solution

Unknown
# Temporary solution

Reverting to a previous state is the only way back.
# Additional information
## Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
## Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by wimpers** [comment]
@JeffreyDevloo did you manage in the end to deleted that backend? Did the remove node complete as planned?

**Comment by JeffreyDevloo** [comment]
The node was removed successfully. I couldn't the delete the back-end on the GUI as it was still installing.

**Comment by wimpers** [comment]
Will be fixed as part of a larger ticket https://github.com/openvstorage/framework/issues/1342
