### ISSUE TITLE
Support Ubuntu 16.04

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#806]
Add support for Ubuntu 16.04.

First tests from QA revealed issues with Etcd (connection refused).

Installation snippet provided by QA:

```
remote_con.process.execute('cd /tmp; wget http://10.100.129.100:8080/view/volumedriver/view/ubuntu/job/volumedriver-dev-release-ubuntu-16.04/lastSuccessfulBuild/artifact/volumedriver-core/build/debian/volumedriver-base_6.0.3-dev.201608092006.f23221e_amd64.deb')
remote_con.process.execute('cd /tmp; wget http://10.100.129.100:8080/view/volumedriver/view/ubuntu/job/volumedriver-dev-release-ubuntu-16.04/lastSuccessfulBuild/artifact/volumedriver-core/build/debian/volumedriver-server_6.0.3-dev.201608092006.f23221e_amd64.deb')
remote_con.process.execute('apt-get install -y gdebi-core')
remote_con.process.execute('cd /tmp; gdebi -n ./volumedriver-base_6.0.3-dev.201608092006.f23221e_amd64.deb')
remote_con.process.execute('cd /tmp; gdebi -n ./volumedriver-server_6.0.3-dev.201608092006.f23221e_amd64.deb')
```

The wgets is for downloading Ubuntu 16.04 enabled volumedriver builds; gdebi is a local deb installer that fetches dependencies.

**Comment by khenderick** [comment]
Alba and arakoon packages also need to be a specific build. So first install the special packages (voldrv, arakoon, alba), then install openvstorage.

https://github.com/openvstorage/alba/releases/ and https://github.com/openvstorage/arakoon/releases (see the release names)

**Comment by kvanhijf** [comment]
OVS can now be installed on Ubuntu16.04
Apt repository on which the OVS packages suited for 16.04 are present:  apt.openvstorage.com

1 VERY IMPORTANT REMARK:
Before actually being able to install the packages on the ubuntu, the correct djangorestframework version must be installed prior to the ovs packages

apt-get update
apt-get install -y --allow-unauthenticated python-djangorestframework=2.3.12-1
apt-get install -y --allow-unauthenticated volumedriver-no-dedup-server
apt-get install -y --allow-unauthenticated openvstorage-hc

**Comment by kvanhijf** [comment]
openvstorage_2.7.3-rev.4011.a41bbc3
openvstorage-sdm-1.6.3-rev.367.5996435
openvstorage-backend_1.7.3-rev.713.f2fab03
