### ISSUE TITLE
ovs remove nodes only removes the node from Models

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#812]
## Problem description

ovs remove nodes only removes the node from Models when the removed node was removed when it was online.
When you use the wiper after the removal, you will remove your etcd configs on all nodes therefore rendering the cluster corrupt.

These services were still running after the node was removed:

```
OVS running processes:

ovs-etcd-config start/running, process 4665
ovs-support-agent start/running, process 1564
ovs-watcher-framework start/running, process 11117
ovs-watcher-volumedriver start/running, process 2590
ovs-workers start/running, process 11138

OVS non-running processes:
```
## Possible root of the problem

The remove node doesn't stop the running services on the node that will be removed.
## Possible solution

Stop the services
## Temporary solution

Shutdown the node before removal to avoid these issues.
### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by wimpers** [comment]
@JeffreyDevloo isn't it logic that if a node is marked offline we don't remove anything on the node. From OVS standpoint the node should not be accessible anymore (up to the user to make it doesn't come back and make it is dead by f.e. removing the power ).

> When you use the wiper after the removal, you will remove your etcd configs on all nodes therefore rendering the cluster corrupt.

can you elaborate on this? Isn't this a bug in the wiper (and not in the framework)?

**Comment by kinvaris** [comment]
@wimpers: this is a bug in the framework. In some cases your node is not down and you just want to remove it to use it for something else. In the future remove node should make an attempt to login in the node and execute these tasks to terminate any connections to the node:

**If it can login:**
- Terminate any access to ETCD
- Stop all services

**If it cannot login:** you can assume that the node is dead, but you would have to be sure that if the node would not come online again. The removed node cannot connect through any means to the active cluster or it could corrupt stuff. (in general just cut-off any communication to the configuration masters e.g. ETCD). If the removed node would come online again, refuse any communication to and from that node.

_Currently_ after the node is presumed dead, **it can still connect to ETCD**. The general idea of the wiper is to wipe everything. If that ETCD connection is dead, it will not be able to hurt the active cluster. Thus this being a bug in the framework.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1078 --> openvstorage-2.7.4-rev.4193.aa0ed1c
https://github.com/openvstorage/alba-asdmanager/pull/131 --> openvstorage-sdm-1.6.4-rev.394.22c93f2
https://github.com/openvstorage/framework-alba-plugin/pull/250 --> openvstorage-backend-1.7.4-rev.784.647dd17

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed cluster
- Configured cluster (vpool extended to all nodes)
- Marked node 1 offline
- Removed node 1 via ovs remove node
- Verified that no ovs services were running anymore

### Output
```
OVS running processes
=====================



OVS non-running processes
=========================


ASD Manager running processes
=============================



ASD Manager non-running processes
=================================


```
### Test result
Test passed. No services were running anymore

### Packages
Tested for Ubuntu 16.04.
- openvstorage                                        2.7.6-rev.4323.a37c7f7-1       amd64                          openvStorage
- openvstorage-backend                                1.7.6-rev.817.91abb7c-1        amd64                          openvStorage Backend plugin
- openvstorage-backend-core                           1.7.6-rev.817.91abb7c-1        amd64                          openvStorage Backend plugin core
- openvstorage-backend-webapps                        1.7.6-rev.817.91abb7c-1        amd64                          openvStorage Backend plugin Web Applications
- openvstorage-core                                   2.7.6-rev.4323.a37c7f7-1       amd64                          openvStorage core
- openvstorage-hc                                     1.7.6-rev.817.91abb7c-1        amd64                          openvStorage Backend plugin HyperConverged
- openvstorage-sdm                                    1.6.6-rev.449.77bd347-1        amd64                          Open vStorage Backend ASD Manager
- openvstorage-webapps                                2.7.6-rev.4323.a37c7f7-1       amd64                          openvStorage Web Applications
