### ISSUE TITLE
vPool creation can be done on other nodes if 1 node has only read/write role.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#817]
During some testing I had created a vpool on 1 node. On that node all the roles where set on disks.
When I try to create a second vpool on the second node (where the roles are not set) it also works.

**INFO:** If you go through with the installation, you cannot create a vpool because you are blocked at step 3 (allocating read and/or write cache)

**Comment by khenderick** [comment]
@kinvaris, can you explain what's wrong here?

You had no roles at all on the 2nd node so:
- A DB role isn't mandatory (as the voldrv cluster can run on other nodes)
- A read and/or write role are mandatory so the step where you configure everything related to caches will inform you about this and block the wizard.

**Comment by khenderick** [comment]
Fixed by #1038, packaged in openvstorage-2.7.4-rev.4147.6f02d53

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks of node 1
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Tried to add vpool on node 2

### Output

Received the following error:
![selection_111](https://cloud.githubusercontent.com/assets/17570109/19439869/06443a1a-9480-11e6-9e27-4a6bab7986e7.png)

Write role is necessary for vpool
Mds information is stored on the DB roles
Both roles are required to host a vpool

### Test result

You can no longer add a vpool from the first wizard window if you do not have the required roles.
Test passed.

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications
