### ISSUE TITLE
Make fragment size of preset configurable through GUI

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#819]
Currently we have to create a preset through the CLi if we want another fragment size.
In the GeoScale perspective, it would be interesting to make the fragment size of the preset configurable during creation/update.

**Comment by domsj** [comment]
FYI: updating the fragment size of an existing preset is currently not supported by alba.
If you need that (and maybe allow updating compression/encryption/name and others(?) too while at it): please file a ticket for alba too.

**Comment by domsj** [comment]
This is important for global backends: you definitely want a bigger fragment size there.
