### ISSUE TITLE
User Mgmt: viewers can't see a single list

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#826]
## Problem description

In the documentation it states : 'Viewers can only see the dashboard and the detail pages but can not launch any actions' (Source: https://github.com/openvstorage/ovs-documentation/blob/master/Administration/usingthegui/administration.md)
When I logged in as a member of the viewers group, I couldn't see any information except for the pages within the menu.
**Accessed the user management as viewer (to give you some context):**
![selection_026](https://cloud.githubusercontent.com/assets/17570109/17810496/c6942bd6-661d-11e6-97c5-2610140be07f.png)
**No entries in any list:**
![selection_025](https://cloud.githubusercontent.com/assets/17570109/17810491/b5aebb24-661d-11e6-85b3-f0a92e2563c4.png)
![selection_027](https://cloud.githubusercontent.com/assets/17570109/17810597/5c852d8e-661e-11e6-8ed2-71a3f0c00ad7.png)
![selection_028](https://cloud.githubusercontent.com/assets/17570109/17810609/6aa7b472-661e-11e6-904c-237ec62d3ce3.png)

Can see the backend in the list when the rights were assigned:
![selection_029](https://cloud.githubusercontent.com/assets/17570109/17810626/87fd1238-661e-11e6-8eca-435ca796a0ff.png)
Without rights it's just an empty list:
![selection_030](https://cloud.githubusercontent.com/assets/17570109/17810677/d4e2b148-661e-11e6-9e19-71e1b0c9725b.png)

**You can access the pages when you enter the url**
For instance a storage router page:
![selection_031](https://cloud.githubusercontent.com/assets/17570109/17810718/1608c43c-661f-11e6-85c6-669938ca29bf.png)
### Steps
- Logged in as admin
- Added a user to Viewers group
- Logged in as the viewer
- Found no entries in any list
### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
To add some information; this behavior is as expected and as requested. We couldn't spend too much time doing a proper user management integration.
