### ISSUE TITLE
Remove 40GB reservation for the metadata DB per vPool

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#831]
Currently we reserve 40GB per vPool for the metadata DB per vPool. This means a lot of space gets reserved without being used.

Proposal don't reverse any space. One should have monitoring to keep an eye on the used space and make you don't run into a full disk.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/965
https://github.com/openvstorage/framework-alba-plugin/pull/218

**Comment by kvanhijf** [comment]
openvstorage-2.7.3-rev.4038.f9a177d
openvstorage-backend-1.7.3-rev.715.7636787

**Comment by kvanhijf** [comment]
@QA: Install single vPool on storagerouter with a DB role on a partition < 40GB
Install multiple vPools on the same storagerouter, this should have no effect on available sizes (unless READ cache is used)
Install single vPool with a huge backend (of several TBs) and claim all available Global Write Buffer space suggested --> no issue should be raised about more requested than available

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Setup cluster
- Added disk roles to 5GB disks
- Added backend
- Initialized disk and claimed asd
- Added (1,1,1,1) preset to work for my limited test environment
- Added two vpools
- Claimed all space for Global Write Buffer on the second vpool

### Output

![selection_109](https://cloud.githubusercontent.com/assets/17570109/19437913/b69624cc-9477-11e6-8e46-747f0712f440.png)
Both vpools were succesfully made on the 5GB disk:

![selection_110](https://cloud.githubusercontent.com/assets/17570109/19437929/cf5f88b8-9477-11e6-8766-9839672c5d70.png)

### Test result

Test passed.

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications
