### ISSUE TITLE
Backend detail page load

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#834]
## Problem description

Fetching the detail page of a backend puts alot of strain of the cpu (More noticable the more backends you have with initialized and claimed disks). This is being problematic when you quickly hop from one page to another as the API calls queue and get resolved asynchronously.

![selection_038](https://cloud.githubusercontent.com/assets/17570109/17856941/216bee90-6880-11e6-8241-0a131c10b107.png)
## Possible root of the problem

I've noticed that there is ALOT of redundant data and this data is scaling with the amount of backends/asds that you have.
![selection_043](https://cloud.githubusercontent.com/assets/17570109/17857588/a01f575c-6882-11e6-8720-34fedb2ffe39.png)
I have 25 backends and for every backend I get this request with the local_stack attribute containing information about every ASD in the cluster. Inside of this local_stack we find the meta-data of every asd.

With a small calculation I found that I receive 1,336MB (55.70kb of data for each request, only one of these requests is necessary and I have 25 backends so 55,70*(25-1)) of redundant data fetched over 24 extra, unnecessary requests.

On top of this I also perceived that API calls are still fetched even after trying to navigate to another page. The requests stay pending in the browser.
The following image logs what happens when I switched from a back-end page back to the overview. On the red arrow I clicked the 'Backends' button on the dashboard but it wouldn't transition to that page just yet because alot of requests are still pending. Once these were resolved, I was redirected to the overview page.
![selection_041](https://cloud.githubusercontent.com/assets/17570109/17858154/d7bf9594-6884-11e6-8c40-6e3e8625f11c.png)
## Possible solution

Every request for each backend contains all the information of every back-end in the cluster.
![selection_044](https://cloud.githubusercontent.com/assets/17570109/17857959/1e34cf72-6884-11e6-8592-594cc82c0624.png)

Instead of fetching all this #number of backends times, we should only fetch this once and fetch the backend guid and its name for every other backend.

Additionally all the open requests should be canceled when the user is trying to navigate to different pages.
### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
- 25 backends
- 50 disks initialized with one ASD for each disk
- 2 ASD for each backend
- Preset (1,1,1,1)
### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
Short: for the "other" backends we should not request `_dynamics` nor `_relations`, as that should be the only thing we need anyway for these backends.

**Comment by khenderick** [comment]
Some feedback:
- Aborting the requests upon page navigation doesn't matter too much for server-side, since the requests are being processed anyway
- The backend overview page doesn't load non-required data

**Comment by khenderick** [comment]
Fixed by openvstorage/framework-alba-plugin#235, packaged in openvstorage-backend-1.7.4-rev.743.af3422d
