### ISSUE TITLE
vPool wizard: loading backends load

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#837]
## Problem description

It takes a while to  (re)load the backend information in the vpool wizard. This is mainly due to the local_stack query that happens on the API to get the necessary information. 
![selection_048](https://cloud.githubusercontent.com/assets/17570109/17883984/f12ad6d8-6915-11e6-8d38-667b673109a3.png)
## Possible solution

Cache the local_stack information for every node in the cluster so it doesn't need to be fetched for each backend.
### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
- 25 backends
- 50 disks initialized with one ASD for each disk
- 2 ASD for each backend
- Preset (1,1,1,1)
### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
The `local_stack` contains slightly different information per backend. However, parts of the data uses can be cached/shared across backends/nodes which should speed up these calls.

**Comment by khenderick** [comment]
Fixed by openvstorage/framework-alba-plugin#235, packaged in openvstorage-backend-1.7.4-rev.743.af3422d
