### ISSUE TITLE
Increase amount of alba statistics in GUI to make it more transparent

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#847]
Currently you see the preset in use and policy in use. 
But this is too little information to keep the system rolling.
A vital part to know if your backend is still ok, is to know:
- How much data has been written in a certain policy
- How healthy is my policy? (e.g. policy is will stop working after 6 disks or 2 nodes stop working)
- ...

**Comment by wimpers** [comment]
@kinvaris 

I'd rather take this up under the Open vStorage Monitoring project (https://github.com/openvstorage/openvstorage-monitoring/issues/53). Do you have a use case/reason why this would not be a good idea?

**Comment by wimpers** [comment]
Decision from BAM, add more alba health stats to the GUI.  @wimpers to define specs with OPS

**Comment by wimpers** [comment]
After discussion with @jtorreke , nothing is required as they can get stats from the monitoring tools.
