### ISSUE TITLE
vDisk configuration missing domain names when trying to configure a target domain

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#849]
![screen shot 2016-08-24 at 16 40 27](https://cloud.githubusercontent.com/assets/12733895/17934953/09c14754-6a1a-11e6-8877-53ba6abd7cb7.png)

Encountered on OVH

"versions": {
            "openvstorage-backend-core": "1.7.1-fargo.1-1",
            "volumedriver-no-dedup-base": "6.0.3-dev.201607191821.0758481",
            "alba": "0.9.17",
            "openvstorage-webapps": "2.7.1-fargo.2-1",
            "volumedriver-no-dedup-server": "6.0.3-dev.201607191821.0758481",
            "openvstorage-backend-webapps": "1.7.1-fargo.1-1",
            "openvstorage-core": "2.7.1-fargo.2-1",
            "openvstorage": "2.7.1-fargo.2-1",
            "openvstorage-cinder-plugin": "1.2.1-fargo.1-1",
            "openvstorage-backend": "1.7.1-fargo.1-1",
            "arakoon": "1.9.9"
        }

**Comment by wimpers** [comment]
If you select  the name gets show so there is a workaround. Probably a very stupid issue in the wizard.

**Comment by kvanhijf** [comment]
Referenced issue (https://github.com/openvstorage/framework/issues/972) has been fixed, but i could not manage to reproduce this issue, nor could i find a way in code which could cause this. An environment on which this is reproducable would be handy

**Comment by wimpers** [comment]
@kinvaris  @JeffreyDevloo  can you try to reproduce this one on the latest fargo/unstable?

**Comment by wimpers** [comment]
Not fixed in "openvstorage": "2.7.5-fargo.3-1"

@kvanhijf please check current OVH install

**Comment by wimpers** [comment]
Werid, after a while it works.

The flow I tried to reproduce:
* Create vDisk -> domain isn't showing
* Check Domain page
* Check vDisks page, domains is showing

Seems like sometimes it is working and sometimes it isn't.

**Comment by khenderick** [comment]
Most likely a race condition of some sort where the Domain guids are already loaded, but the displayed text not.

**Comment by kvanhijf** [comment]
Don't think its a race condition. When going through the code i don't see anything that actually waits for certain fields to be filled out. We just start showing stuff as soon as we have some info. I think we should introduce a general 'everything_is_loading' flag and only start displaying stuff when this flag is false again.
Shouldn't take more than a couple of hundred milliseconds

**Comment by khenderick** [comment]
But the fact that there are three checkboxes let me think that our list observable (```dtlTargets``` I think) would have three entries in it. And the function that process the text shown foreach item would then somehow return nothing (item not yet in the ```domainCache``` map?)

**Comment by kvanhijf** [comment]
yes, thats my thought as well
The domaincache is populated later in the process

**Comment by khenderick** [comment]
Fixed by #1271, packaged in openvstorage-2.7.8-rev.4437.ecccd78

**Comment by pploegaert** [comment]
VALIDATED OK
