### ISSUE TITLE
vPool GUI work

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#852]
- Add vPool wizard - Step 1
  - [x]  Remove backend type selection
    -Add vPool wizard - Step 2
  - [x] "Fragment Cache" should become "Cache"
  - [x] "Place Fragment Cache on disk" should be "Use local disk"
  - [x] "Use another ALBA Backend as Fragment Cache" should be "Use another Backend Cache"
- Add vPool wizard - Step 3
  - [x] Replace "StorageDriver Caching Information" by "Storage Driver Write Buffer"
  - [x] Remove Strategy
  - [x] Remove Deduplication
- Add vPool wizard - Step 4
  - [x]  https://github.com/openvstorage/framework/issues/783
- vPool overview page
  - [x] Remove Type, Connection and Login and replace by OVS Backend & preset
- vPool detail page
  - [x] Add backend info https://github.com/openvstorage/framework/issues/735
  - [x] Under configuration remove "Cache strategy", "Dedupe Mode"
  - [x] Under Mgmt actions add a link to the accelerated ALBA for each storage router (link to the backend)
  - [x] Under Mgmt actions make the Storage routers clickable

**Comment by wimpers** [comment]
Some clarification around vPool overview page. The result should be following columns:

 status|name|backend (preset)|stored data|IOPS

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1130 --> openvstorage-2.7.5-rev.4273.d9bb7fb
https://github.com/openvstorage/framework-alba-plugin/pull/267 --> openvstorage-backend-1.7.5-rev.811.c1b83e6

**Comment by kvanhijf** [comment]
Additional commit for update fixes:
https://github.com/openvstorage/framework/pull/1136 --> openvstorage-2.7.5-rev.4281.6612d8c

**Comment by JeffreyDevloo** [comment]
All of these GUI changes have been implemented.
