### ISSUE TITLE
Vpool creation/extending: too much space requested for WRITE cache

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#858]
openvstorage: 2.7.2-rev.3884.42ef467-1 (unstable)

HC setup with 3 nodes. Write and DB role on the same disk.

```
2016-08-29 11:45:29 74600 +0200 - pocops01-ovs03 - 6141/140161114023744 - celery/celery.worker.job - 18392 - ERROR - Task ovs.storagerouter.add_vpool[695ccaa7-090f-40cd-a059-d834092a4105] raised unexpected: ValueError('Errors validating the partition roles:\n - Too much space requested for WRITE cache. Available: 57.97 GiB, Requested: 64.00 GiB',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 539, in add_vpool
    raise ValueError('Errors validating the partition roles:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the partition roles:
 - Too much space requested for WRITE cache. Available: 57.97 GiB, Requested: 64.00 GiB
```

**Comment by matthiasdeblock** [comment]
![issue_858_1](https://cloud.githubusercontent.com/assets/14923932/18050231/ac48be18-6ded-11e6-904e-1bc16fcc9465.png)
![issue_858_2](https://cloud.githubusercontent.com/assets/14923932/18050232/ac4cab4a-6ded-11e6-95e8-ad109bdf07e5.png)

**Comment by kinvaris** [comment]
Maybe roundup mistake?

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework/issues/831

**Comment by kvanhijf** [comment]
Moved to Fargo since issue was fixed while fixing another issue on Fargo

**Comment by JeffreyDevloo** [comment]
### Information
Same steps as the referenced ticket which was behind the issue of this ticket.

### Steps
- Installed latest packages
- Setup cluster
- Added disk roles to 5GB disks
- Added backend
- Initialized disk and claimed asd
- Added (1,1,1,1) preset to work for my limited test environment
- Added two vpools
- Claimed all space for Global Write Buffer on the second vpool

### Output
![selection_109](https://cloud.githubusercontent.com/assets/17570109/19437913/b69624cc-9477-11e6-8e46-747f0712f440.png)
Both vpools were succesfully made on the 5GB disk:
 
![selection_110](https://cloud.githubusercontent.com/assets/17570109/19437929/cf5f88b8-9477-11e6-8766-9839672c5d70.png)

### Test result
Test passed.

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications
