### ISSUE TITLE
API to create/delete snapshots of multiple vDisks at once.

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#861]
Nuvolat/Skystor needs this to lower the amount of API calls/roundtrips.

Proposal:
API/VPOOL/GUID/create_snapshots
Creates a snapshot for multiple vDisks at once
        :param vdisks: List of Guids of the virtual disks to create a snapshot for
        :param name: Name of the snapshot (label)
        :param version: Client version
        :param timestamp: Timestamp of the snapshot - integer
        :param consistent: Flag - is_consistent
        :param automatic: Flag - is_automatic
        :param sticky: Flag - is_sticky

Task return value: dict with vdiskGUID/snapshotGUID pairs

API/VPOOL/GUID/remove_snapshots
Remove a snapshot from multiple vDisks at once
        :param snapshot_dict: dict with vdiskGUID/snapshotGUID pairs to delete

Task return value: dict with snapshotGUID/boolean pairs

**Comment by khenderick** [comment]
You don't need to pass in `version`, that's an internal field (the client passes this through the accept-header)

**Comment by khenderick** [comment]
Create snapshots:
- POST `/api/vpools/<vpool_guid>/create_snapshots/`
- mandatory parameters: 
  - `vdisk_guids`: list of vDisk guids
  - `name`: name of all snapshots
- optional parameters:
  - `timestamp`: unix timestamp on which the snapshot is taken
  - `consistent`: True/False, indicates whether the snapshots are consistent
  - `automatic`: True/False, indicates whether the snapshots were taken automatically
  - `sticky`: True/False, indicates whether OVS should clean up the snapshots
- return value: Dict with as key the vDisk guids and as value a list where the first element indicates either success or failure (True/False):
  - Success: The second element is the snapshot_id
  - Failure: The second element is the error

Delete snapshots:
- POST `/api/vpools/<vpool_guid>/remove_snapshots/`
- mandatory parameters:
  - `snapshot_mapping`: A dict where the key is a vDisk guid and the value is a snapshot_id to be deleted.
- return value: Dict with as key the vDisk guids and as value a list where the first element indicates either success or failure (True/False):
  - Success: the second element is the deleted snapshot_id
  - Failure: the second element is the error

**Comment by khenderick** [comment]
Fixed by #878, packaged in openvstorage-2.7.3-rev.3941.ea3d176

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup nodes
- Setup Postman
- Logged in to get a token
- Did the following call:

![selection_071](https://cloud.githubusercontent.com/assets/17570109/18387445/0344fe7c-769d-11e6-9ce7-784d52fddeda.png)
- Received a task id: 173b9ea7-3217-4c3a-89f6-d8c4e87b0a8d
- Checked its status:
  ![selection_072](https://cloud.githubusercontent.com/assets/17570109/18387482/25c9cbee-769d-11e6-803d-d6ec1e491f23.png)

### Output

Got a succes. Verified deletion on the GUI: snapshot was removed.

### Test result

Test passed
