### ISSUE TITLE
Ovs remove node takes a long time to complete

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#862]
When performing a `ovs remove node` on a gig environment we saw some performance problems when the cluster has a lot of vdisks at these parts:
https://github.com/openvstorage/framework/blob/71749e3459d816c4d67ed01b8bde903798460661/ovs/lib/setup.py#L652

https://github.com/openvstorage/framework/blob/71749e3459d816c4d67ed01b8bde903798460661/ovs/lib/storagerouter.py#L1117

To test and reproduce this problem we will deploy 200 - 300+ disks on a cluster and start the removal procedure.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1078 --> openvstorage-2.7.4-rev.4193.aa0ed1c
https://github.com/openvstorage/alba-asdmanager/pull/131 --> openvstorage-sdm-1.6.4-rev.394.22c93f2
https://github.com/openvstorage/framework-alba-plugin/pull/250 --> openvstorage-backend-1.7.4-rev.784.647dd17

**Comment by wimpers** [comment]
Closed by PM.
