### ISSUE TITLE
Write role check is incorrect

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#866]
When you create a new vPool on OVH I get an error the name is missing and a write role is missing. When I enter a name, the write role message disappears also.

![2016-08-31_16-11-21](https://cloud.githubusercontent.com/assets/8392927/18132274/795e3a64-6f96-11e6-957b-ce23365f724c.jpg)
![2016-08-31_16-11-51](https://cloud.githubusercontent.com/assets/8392927/18132279/7e1e2064-6f96-11e6-83d7-867b443c2b65.jpg)

**Comment by khenderick** [comment]
That one is fixed to by some of the latest changes (but I can't remember anymore which ones)

**Comment by wimpers** [comment]
Closed by PM.
