### ISSUE TITLE
Demote can fail if host is running single-node voldrv arakoon cluster

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#868]
Demote can fail if host is running single-node voldrv arakoon cluster. To be correct, we should not raise, but leave the node running after which the checkup should move the arakoon node to another master node.

**Comment by wimpers** [comment]
Since single node issue moved to gilbert.

**Comment by kvanhijf** [comment]
openvstorage-2.7.4-rev.4157.09b9e2c -- > https://github.com/openvstorage/framework/pull/1044

**Comment by khenderick** [comment]
Needs a bit more love

**Comment by khenderick** [comment]
Fixed by #1196, packaged in openvstorage-2.7.6-rev.4346.136e041
