### ISSUE TITLE
Re-enable upgrades

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#877]
Re-enable upgrades

**Comment by khenderick** [comment]
Fixed by #876, packaged in openvstorage-2.7.3-rev.3935.ca8dbd4

**Comment by khenderick** [comment]
Please note that the upgrade will work from the above package onwards. Upgrading to that package won't work.

**Comment by JeffreyDevloo** [comment]
### Steps
- Used ovs upgrade framework command on my nodes who were running openvstorage                       2.7.3-rev.3945.833fb96-1
- Saw in the logs that they were done
- Verified state of backend, vpool and vdisk

## 

Similar testscenario: 
- Used ovs upgrade framework command on my nodes who were running openvstorage                       2.7.3-rev.3945.833fb96-1
- Saw in the logs that they were done
- Verified creation of backend, vpool and vdisk

### Test result

Test passed.
