### ISSUE TITLE
Change auto-decommission policy

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#882]
I just had a chat with Stefaan and apparently the default auto-decommission policy is set to 15 minutes. If we had done this on the current live environments, we'd no longer have environments. I would propose to disable auto-decommissioning by default or set the timer to 1-2 months or something.

An example (similarities with real life situations are purely based on coincidence):
- You have a failing raid controller in a storage node which loses access to all disks after 4 months of uptime. In the current situation all disks would be decommissioned after 15 minutes. AS20 anyone?

**Comment by domsj** [comment]
It seems there's been some confusion.
Alba has an auto-repair feature, which kicks in after 15 minutes.
As long as the failure detector thinks the osd is unavailable we'll keep on repairing any objects that were on the disk. Soon after the disk becomes available we'll stop repairing objects that had fragments on it, and we'll use the disk just as before.
Alba never auto decommissions osds... so I'll close this ticket :-)
