### ISSUE TITLE
vTemplates are visible in the vPool detail page in the vDisk section

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#883]
vTemplates are visible in the vPool detail page in the vDisk section. They can be clicked and go to the detail page which loads and then immediately redirect to the overview page again since a vTemplate's details cannot be viewed. The vTemplates should not be shown on the vPool detail page.

**Comment by khenderick** [comment]
Fixed by #986, packaged in openvstorage-2.7.3-rev.4067.4d6888b

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed ovs cluster
- Added roles to disks
- Added backends (mybackend)
- Initialized disks
- Claimed ASDS
- Add vpool on node 1
- Extended vpool to node 2
- Added vdisks (myvtemplate01, myvdisk01) to myvpool01
- Added myvtemplate01 to vtemplates

### Output

**Vtemplate page:**
![selection_009](https://cloud.githubusercontent.com/assets/17570109/19481106/214675f8-954d-11e6-9043-eadbb6028ce3.png)

**vpool pages:**
myvpool01:

![selection_010](https://cloud.githubusercontent.com/assets/17570109/19481133/3a5974f0-954d-11e6-9460-50a207a1fded.png)

myvpool02:

![selection_011](https://cloud.githubusercontent.com/assets/17570109/19481139/418afeba-954d-11e6-82b7-f0ca7dcac577.png)

### Test result
- [x] No entry in myvpool01 page (where disk originates from)
- [x] No entry in myvpool02 page
- [x] Tried navigating back to the page via the URL and got redirected to vdisks page.

The vtemplate is not visible on the vpool pages.
Test passed.

### Packages
- openvstorage                       2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.390.89e2ad4-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage Web Applications
