### ISSUE TITLE
ovs get-key key

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#888]
Add to the ovs cli an option to easiliy set/get/list configuration keys

`ovs list key-prefix` : lists  all keys starting with key-prefix
`ovs set key value` : set key/value
`ovs get key` : get the key

The above options should work for all configuration mgmt systems.

**Comment by khenderick** [comment]
Fixed by #914, packaged in openvstorage-2.7.3-rev.3962.304ec6e

**Comment by khenderick** [comment]
Implemented as:
- `ovs config edit some/key` to edit that key in your `$EDITOR`. If it doesn't exist, it is created
- `ovs config list some` to list all keys with the given prefix
- `ovs config get some/key` print the contents of the given key

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest OVS
- Setup diskroles
- Added backend
- Tried all ovs config command

### Output

```
root@ovs-node2:~# ovs config get ovs/arakoon/voldrv/config
[s6zN7RABK1NsFljX]
crash_log_sinks = console:
ip = 10.100.199.152
tlog_compression = snappy
client_port = 26416
home = /mnt/hdd1/arakoon/voldrv/db
log_level = info
name = s6zN7RABK1NsFljX
fsync = true
log_sinks = console:
messaging_port = 26417
tlog_dir = /mnt/hdd1/arakoon/voldrv/tlogs

[global]
cluster = 52GAMfFlswlIaI2U,OlUD8NlOApLn5SNO,s6zN7RABK1NsFljX
cluster_id = voldrv
tlog_max_entries = 5000
plugins = 

[52GAMfFlswlIaI2U]
crash_log_sinks = console:
ip = 10.100.199.151
tlog_compression = snappy
client_port = 26416
home = /mnt/hdd1/arakoon/voldrv/db
log_level = info
name = 52GAMfFlswlIaI2U
fsync = true
log_sinks = console:
messaging_port = 26417
tlog_dir = /mnt/hdd1/arakoon/voldrv/tlogs

[OlUD8NlOApLn5SNO]
crash_log_sinks = console:
ip = 10.100.199.153
tlog_compression = snappy
client_port = 26416
home = /mnt/hdd1/arakoon/voldrv/db
log_level = info
name = OlUD8NlOApLn5SNO
fsync = true
log_sinks = console:
messaging_port = 26417
tlog_dir = /mnt/hdd1/arakoon/voldrv/tlogs
```

```
root@ovs-node2:~# ovs config edit ovs/arakoon/voldrv/config
```

![selection_084](https://cloud.githubusercontent.com/assets/17570109/18631718/ebe27582-7e73-11e6-9bd2-e175e0e7159f.png)

```
EDITOR=vim ovs config edit ovs/arakoon/voldrv/config
```

![selection_085](https://cloud.githubusercontent.com/assets/17570109/18631812/824b49ae-7e74-11e6-931f-e76d25cb035d.png)

```
root@ovs-node2:~# ovs config list ovs/arakoon
ovsdb
vm-backend-abm
vm-backend-nsm_0
vm-backend2-abm
vm-backend2-nsm_0
vm-backend3-abm
vm-backend3-nsm_0
voldrv

```

### Test result

Get: passed
Edit: 
Nano editor:
- Wrote something without saving. Verified if entry was not saved (OK)
- Wrote something and saved. Verified if entry was there (OK)

VIM editor
- Wrote something without saving. Verified if entry was not saved (OK)
- Wrote something and saved. Verified if entry was there (OK)
  List: passed

### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end

### Package information
- openvstorage                       2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage
- openvstorage-backend               1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.3-rev.709.5bb94c8-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.134.9ef41c0-1                                  amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.3-rev.357.ee7c9f5-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.3-rev.1012.608f550-1                                 amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.3-rev.3978.4f93e02-1                                 amd64        openvStorage Web Applications
