### ISSUE TITLE
GUI can hang on cloning from template

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#889]
## Problem description

When you clone from a vtemplate of which the host is down (for instance a vtemplate hosted on node 1 and node 1 is offline), the GUI will sometimes not process your cloning.

![selection_067](https://cloud.githubusercontent.com/assets/17570109/18382074/be8dc3f8-767f-11e6-9eca-fc880aadb0d3.png)
What happens is that when you click 'Finish', the button will grey out and the modal keeps showing. After a brief delay, the finish button is clickable again and you can retry. In some cases it works, in others it wont.

When the button is clicked and greys out (without closing the modal), there is no post happening to the API. With this I close the possibility of the API not handling the call.
## Temporary solution

The temporary solution seems to be retrying by closing the modal and restarting the whole process.
### Setup

Hyperconverged setup with 3 nodes
### Package
-  openvstorage                       2.7.3-rev.3947.f6124e7-1                                 amd64        openvStorage
-  openvstorage-backend               1.7.3-rev.689.95a4c61-1                                  amd64        openvStorage Backend plugin
-  openvstorage-backend-core          1.7.3-rev.689.95a4c61-1                                  amd64        openvStorage Backend plugin core
-  openvstorage-backend-webapps       1.7.3-rev.689.95a4c61-1                                  amd64        openvStorage Backend plugin Web Applications
-  openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
-  openvstorage-core                  2.7.3-rev.3947.f6124e7-1                                 amd64        openvStorage core
-  openvstorage-hc                    1.7.3-rev.689.95a4c61-1                                  amd64        openvStorage Backend plugin HyperConverged
-  openvstorage-health-check          2.0.0-rev.134.9ef41c0-1                                  amd64        Open vStorage HealthCheck
-  openvstorage-sdm                   1.6.3-rev.352.76af109-1                                  amd64        Open vStorage Backend ASD Manager
-  openvstorage-test                  2.7.3-rev.1012.608f550-1                                 amd64        openvStorage autotest suite
-  openvstorage-webapps               2.7.3-rev.3947.f6124e7-1                                 amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
Most likely a check that doesn't display a correct warning.

**Comment by JeffreyDevloo** [comment]
I'd like to add that there is no indication on the front-end that displays if something went wrong during this process.

**Comment by khenderick** [comment]
After some discussions with @JeffreyDevloo, this might have been a side-effect from #857. Please validate and re-open if required.

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Setup disk roles
- Added backend
- Initialized disks
- Claimed asds
- Create vpool
- Added vdisks (myvdisk01, myvtemplate01)

Verification:
- Set myvtemplate01 as template on node 1
- Switched to different GUI
- Forced node 1 off
- Cloned from myvtemplate01 to node 2 as myvclone01 

### Output

Both vdisks were created without the issue described in the issue.
![selection_012](https://cloud.githubusercontent.com/assets/17570109/19485039/13b96334-955a-11e6-9109-237fc553f41e.png)

### Test result

Test passed.

### Packages
- openvstorage                       2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.390.89e2ad4-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage Web Applications
