### ISSUE TITLE
Ovs update framework - add log to specify the revision you are updating to and from

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#900]
### Enchancement description

Add a log entry that says what revision you are updating from and what revision you are updating to. EG. : 2016-09-14 10:10:09 18200 +0200 - ctrl-stras-03 - 185941/140202909386560 - lib/update - 1 - INFO - Updating from 1.7.3-rev.694.f9f958c-1 to 1.7.3-rev.696.90408c4-1

**Comment by wimpers** [comment]
If urgently needed , please create a PR.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1141 --> openvstorage-2.7.7-rev.4375.355aa3e
https://github.com/openvstorage/alba-asdmanager/pull/165 --> openvstorage-sdm-1.6.7-rev.468.144789e
https://github.com/openvstorage/ovs-documentation/pull/52
https://github.com/openvstorage/framework-alba-plugin/pull/278 --> openvstorage-backend-1.7.7-rev.837.7922150

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework/issues/1123
