### ISSUE TITLE
Remove statistics page from under Administration

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#909]
Remove statistics page from under Administration as this has become a meaningless page.

**Comment by khenderick** [comment]
Fixed by #1043, packaged in openvstorage-2.7.4-rev.4155.42b2f87

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup cluster
- Browsed to GUI
- Tried to access statistics via menu (I couldn't)
- Tried to access statistics via the url (I couldn't)

### Output

![selection_117](https://cloud.githubusercontent.com/assets/17570109/19440447/4227970a-9482-11e6-80cc-3cc7a004dd79.png)

### Test result

Test passed.
