### ISSUE TITLE
Volumename incorrect

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#911]
Reported via @grimpy:

Using qemu-convert over edge, following volume is created: `openvstorage+tcp://ip:port/templates/Ubuntu.1604.uefi.x64`

This will cause a fuse-visible disk on `/mnt/vpool_name/templates/Ubuntu.1604.uefi.x64.raw`.

It is however reported that the displayed name is "Ubuntu", which isn't very informative (there could be multiple versions etc), and ideally, it should be called "Ubuntu.1604.uefi.x64".

**Comment by khenderick** [comment]
Line of interest: https://github.com/openvstorage/framework/blob/master/ovs/lib/vdisk.py#L168

Something like `volume_path.rsplit('/', 1)[-1].rsplit('.', 1)[0]` would be better I think.

**Comment by wimpers** [comment]
please fix together with #912

**Comment by khenderick** [comment]
Fixed by #982, packaged in openvstorage-2.7.3-rev.4061.083329a

**Comment by JeffreyDevloo** [comment]
### Information
The name was being cut up because of the dot splitting. Since the related ticket(:github.com/openvstorage/framework/issues/912) has been closed, I am closing this one too.
