### ISSUE TITLE
Integrate LRU cache

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#919]
Integrate LRU cache.
- Setup a redis cluster instead of separate redis nodes
- Configure every backend to use LRU in case it would be used as a fragment cache

**Comment by khenderick** [comment]
Fixed by #922 and openvstorage/framework-alba-plugin#214, packaged in openvstorage-2.7.3-rev.3971.6debc60 and openvstorage-backend-1.7.3-rev.709.5bb94c8

**Comment by kinvaris** [comment]
- Currently this is by default enabled for every backend, you cannot configure this in the GUI nor during the setup.
- At setup time the redis service for LRU is setup on every node although 1 is only used, this would mean manual reconfiguration if 1 master node would die. This can easily be solved by implementing a `keepalived` ip address. 

FYI This keepalived address would also solve the memcached problem in the geoscale story, currently if a master node goes down like in OVH. We need manual intervention to re-enable the GUI.

**Comment by wimpers** [comment]
For QA:
- Decision was made not to set up a cluster but use one of the nodes. 
- Was not requested to be in the GUI.
- Manual reconfiguration in case the redis goes down.

**Comment by kinvaris** [comment]
@wimpers: should it be able to add a external redis server during setup?

**Comment by wimpers** [comment]
No, if needed create a separate ticket for this as discussed.

**Comment by wimpers** [comment]
Created https://github.com/openvstorage/framework/issues/1119 for the external redis enhancement. Closing this one down. Re-open if needed.
