### ISSUE TITLE
Create new disk from GUI with name uppercase letter, changes its device name to lowercase.

### ISSUE THREAD

**Issue by nhonnavar** [openvstorage/framework#928]
Issue:
Created a disk with name “win2008R2”  and in the vpool it shows device name as  win2008r2.raw, uppercase R changed to lowercase.  This is causing an issue when I connect the vdisk on ISCSI target (kernsafe) server as device name of the vdisk is different than name in the GUI.

Possible fix I tried  
Removed lower() function at line number 1170 of /opt/OpenvStorage/ovs/lib/vdisk.py  
name = name.strip('/').replace(' ', '_').lower()

Does it causes any issue if device name has uppercase+lowercase letter..?

**Comment by khenderick** [comment]
Removing the lower/uppercase should not introduce any issues, so it might be a good idea.

**Comment by wimpers** [comment]
@khenderick  should be a small one?

**Comment by khenderick** [comment]
Fixed by #982, packaged in openvstorage-2.7.3-rev.4061.083329a

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Added vdisk with uppercase name

### Output

The name is no longer lowercased:
![selection_002](https://cloud.githubusercontent.com/assets/17570109/19442949/6ccfd9a0-948b-11e6-9ab3-8ca901a58005.png)

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications
