### ISSUE TITLE
/dev/disk/by-id/wwn-xxx device links break the FWK device discovery

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#929]
The are rules in /lib/udev/rules.d/60-persistent-storage.rules which generate wwn-\* symlinks under /dev/disk/by-id/ to certain devices. On some systems these links got created for a subset of the scsi devices. Not sure why that happened and we never saw this before on others.
But the Open vStorage Framework code used to identify the scsi devices by its id is apparently tripping on these.
For now as a workaround the links can be removed and devices rescanned.
Customer ticket for more info: http://support.openvstorage.com/browse/OVSSUP-94

**Comment by dejonghb** [comment]
The WWN (World Wide Name) or World Wide Identifier (WWID) is, iirc, certainly used with fibre channel so if we want to support that we probably will need to allow these WWN as well...
Links are created if an ID_WWN_WITH_EXTENSION is found by one of probing utils used in the rules (scsi_id / ata_id ) so it depends on what the device (firmware) is reporting.

**Comment by dejonghb** [comment]
Note: it should be checked problem wasn't caused by underlying hardware reporting the same WWN for several disks (cfr. we've seen certain ssds reporting the same serial number on multiple devices)

**Comment by wimpers** [comment]
We don't support devices with the same serial nr. To be re-opened if it would be caused by another issue.
