### ISSUE TITLE
vdisk size not present for some disks in GUI

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#936]
Vdisk `jonas11` with volume_guid `9cbf286e-2d48-4800-973f-7d1cf09e62ee` has no `size`

```
root@cmp01:~# ls /mnt/rora2/jonas11.raw -alsh
10G -rwxrwxr-x 1 ovs ovs 10G Sep 20 11:20 /mnt/rora2/jonas11.raw
root@cmp01:~# ls /mnt/rora2/jonas1.raw -alsh
10G -rwxrwxr-x 1 ovs ovs 10G Sep 20 11:19 /mnt/rora2/jonas1.raw
```

But it has a size in the volumedriver:

```
In [46]: client.info_volume("9cbf286e-2d48-4800-973f-7d1cf09e62ee").volume_size
Out[46]: 10737418240
```

We've seen this problem in multiple disks, these disks where deployed with `for i in {1..16}; do truncate -s 10G jonas${i}.raw; done`
![](http://i.imgur.com/Xr91aHG.png)

**Comment by khenderick** [comment]
I just created 16 disks with the same command and their sizes show up correctly. Please provide some logs to see what went wrong on your env. Interesting logs are in this case `/var/log/upstart/ovs-volumerouter-consumer.log` and `/var/log/upstart/ovs-workers.log`

**Comment by khenderick** [comment]
Back to `state_verification` so it gets back to QA's task list to reproduce the issue (and close the issue if it works - or provide more information if it doesn't work). Nobody is looking at this `state_question`.

**Comment by kinvaris** [comment]
Just tried to reproduce it on our CI environments. No results. So failed to reproduce.
