### ISSUE TITLE
Errors while upgrading openvstorage-sdm package

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#939]
```
root@cmp02:~# apt-cache policy openvstorage-sdm
openvstorage-sdm:
  Installed: 1.6.3-rev.352.76af109-1
  Candidate: 1.6.3-rev.367.5996435-1
  Version table:
     1.6.3-rev.367.5996435-1 0
        500 http://apt.openvstorage.org/ unstable/main amd64 Packages
 *** 1.6.3-rev.352.76af109-1 0
        100 /var/lib/dpkg/status
root@cmp02:~# apt-get install openvstorage-sdm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  openvstorage-sdm
1 upgraded, 0 newly installed, 0 to remove and 185 not upgraded.
Need to get 75.3 kB of archives.
After this operation, 16.4 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openvstorage-sdm
Install these packages without verification? [y/N] y
Get:1 http://apt.openvstorage.org/ unstable/main openvstorage-sdm amd64 1.6.3-rev.367.5996435-1 [75.3 kB]
Fetched 75.3 kB in 0s (640 kB/s)            
(Reading database ... 144348 files and directories currently installed.)
Preparing to unpack .../openvstorage-sdm_1.6.3-rev.367.5996435-1_amd64.deb ...
Unpacking openvstorage-sdm (1.6.3-rev.367.5996435-1) over (1.6.3-rev.352.76af109-1) ...
Setting up openvstorage-sdm (1.6.3-rev.367.5996435-1) ...
dpkg: error processing package openvstorage-sdm (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openvstorage-sdm
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by kinvaris** [comment]
Also seeing this problem during method: `ovs.storagerouter.get_update_status`

```
2016-09-21 18:06:43 04700 +0200 - stor-202.be-gen8-1 - 30178/139947926800192 - celery/celery.worker.job - 248 - ERROR - Task ovs.storagerouter.get_update_status[0bc16649-5d5d-4314-a2b7-b55fa7b853f7] raised unexpected: RuntimeError(u"type object 'Upstart' has no attribute 'list_service_files'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1533, in get_update_status
    output = function(root_client)
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albacontroller.py", line 1119, in get_metadata_sdm
    candidate = node.client.get_update_information()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 187, in get_update_information
    return self._call(requests.get, 'update/information', timeout=120, clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 82, in _call
    raise RuntimeError(data.get('_error', 'Unknown exception: {0}'.format(data)))
RuntimeError: type object 'Upstart' has no attribute 'list_service_files'
```

**Comment by kinvaris** [comment]
maybe related to https://github.com/openvstorage/framework/issues/938 ?

**Comment by khenderick** [comment]
Might indeed be related. Since #938 is already fixed, I suspect this installation had an older sdm still installed. Please verify updating from a more recent sdm package.

**Comment by JeffreyDevloo** [comment]
### Steps
-  Reverted back to snapshot with older packages (see package information)
- Updated ovs framework to latest one to avoid https://github.com/openvstorage/alba-asdmanager/issues/126
- Updated SDM

### Output

All updates were successful.

### Test result

Test passed.

### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end

### Package information
- openvstorage                       2.7.3-rev.4059.6d404af-1                                 amd64        openvStorage
- openvstorage-backend               1.7.3-rev.721.b4724e5-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.3-rev.721.b4724e5-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.3-rev.721.b4724e5-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.3-rev.4059.6d404af-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.3-rev.721.b4724e5-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.3-rev.372.0cfe8a2-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.3-rev.4059.6d404af-1                                 amd64        openvStorage Web Applications
