### ISSUE TITLE
openvstorage-sdm is upgraded during StorageDriver upgrade in GUI.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#941]
While upgrading the storagedriver, it seems like `openvstorage-sdm` is also upgraded, shouldn't this be upgraded by the framework?

**Comment by khenderick** [comment]
No, we consider that part of the storage/volumedriver layer, since restarting ASDs might have impact on the volumes running. The framework is framework-only and can be updated without impact.
