### ISSUE TITLE
Close all FD's when forking

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#944]
Initiated with the issues that one of the Arakoon clients wasn't properly cleaned up on forking, a few thoughts where exchanged. @toolslive came up with the idea to just close all possible filedescriptors when forking.

Dummy code:

```
getrlimit(NOFILE)
for fd in xrange(n_fds):
    close(fd)
```

**Comment by toolslive** [comment]
basically: close all fds you're not explicitly planning to use.

**Comment by domsj** [comment]
This might help, but it's not enough to prevent accidents.

E.g. there's a singleton pyrakoon client. Process fork, close all fds. Next in the forked process you open a few extra fds, one of which has the same value as the fd for the pyrakoon client. Now when using the pyrakoon client it will suddenly be using another socket!

(Btw there's also the close-on-exec bit for fds, but that probably has the same problem as just described)

**Comment by khenderick** [comment]
I'm going to suggest to close this ticket. We haven't seen any issues lately and I think making assumptions might - like @domsj states - introduce other possible issues.

**Comment by wimpers** [comment]
after discussion with @khenderick , set to closed reopen if needed.

cc @saelbrec
