### ISSUE TITLE
Add `env ALBA_LWT_ENGINE=libev` to all alba processes when no RDMA is used

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#948]
Like in the example, requested by @domsj awaiting for another fix in oRDMA library.

```
description "alba proxy"

start on starting ovs-volumedriver_vmstor
stop on stopped ovs-volumedriver_vmstor

kill timeout 60
respawn
respawn limit 10 5
console log
setuid root
setgid root
limit nofile 4096 4096
limit memlock unlimited unlimited

env LD_LIBRARY_PATH=/usr/lib/alba
env ALBA_LWT_ENGINE=libev

pre-start script
    if [ ! -d /opt/OpenvStorage/run ]
    then
        mkdir /opt/OpenvStorage/run
        chown ovs:ovs /opt/OpenvStorage/run
    fi
    echo `alba version --terse` > /opt/OpenvStorage/run/albaproxy_vmstor.version
end script

exec /usr/bin/alba proxy-start --config arakoon://config/ovs/vpools/885075ed-41ea-4d02-b02d-68196ba9fdc8/proxies/020c5483-93a8-42e0-9c42-b1c57d0f675c/config/main?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --log-sink console:
```

**Comment by saelbrec** [comment]
@domsj ,
I thought you mentioned that you ran into a maintenance daemon where setting this environment variable did not have any effect?

**Comment by domsj** [comment]
I indeed ran into this... not sure where the problem is. I think alba behaves correctly when it sees the env variable, so I think there must've been some problem with passing the env var towards the maintenance process?

**Comment by kvanhijf** [comment]
openvstorage-2.7.3-rev.4054.a1f9f0e

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Checked alba init files

Files that must contain this line (got info from @domsj):
- ovs-albaproxy-*
- alba-albamaintenance-*

### Output

Found 'env ALBA_LWT_ENGINE=libev' for
- ovs-albaproxy-*

Did not find entry in:
- alba-albamaintenance_*
- alba-asd-*

### Test result

Test failed.

### Required changes
- Add 'env ALBA_LWT_ENGINE=libev' to alba-albamaintenance_*

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/129 -- > openvstorage-sdm-1.6.4-rev.390.89e2ad4

**Comment by JeffreyDevloo** [comment]
Updating to the latest package does NOT fix this issue.

## After update

### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Checked alba init files

Files that must contain this line (got info from @domsj):
- ovs-albaproxy-*
- alba-albamaintenance-*

### Output

Found 'env ALBA_LWT_ENGINE=libev' for
- ovs-albaproxy-*

Did not find entry in:
- alba-albamaintenance_*

### Test result

Test failed.

## After reinstall

### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Checked alba init files

Files that must contain this line (got info from @domsj):
- ovs-albaproxy-*
- alba-albamaintenance-*

### Output

Found 'env ALBA_LWT_ENGINE=libev' for
- ovs-albaproxy-*
- alba-maintenance-*

### Test result

Test passed.

A reinstall fixes the issue.

### Packages
- openvstorage                       2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.770.ae31d34-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.390.89e2ad4-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4161.5f26491-1                                 amd64        openvStorage Web Applications

**Comment by kinvaris** [comment]
The following issue occurs when there are more than 1024 file descriptors open by the process. By default the ASD is configured to have max. 1024 file descriptors open at the same time. But if this would increase to more by e.g. a tweak or something. It would be recommended to add it by default to the ASDs too.

**Comment by toolslive** [comment]
It's not an ASD configuration, but an operating system configuration (`$ ulimit -n => 1024`).
However: the ASD could protect itself and use only a certain amount of fds (see [alba/#372](https://github.com/openvstorage/alba/issues/372) )

**Comment by toolslive** [comment]
Also, there was an issue with RORA where certain errors on rora-server side would leak a file descriptor.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/136 --> openvstorage-sdm-1.6.4-rev.398.77e981d

**Comment by JeffreyDevloo** [comment]
Updating to the latest package does NOT fix this issue. A manual patch must be done

## After update

### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Checked alba init files

Files that must contain this line:
- ovs-albaproxy-*
- alba-albamaintenance-*
- alba-asd-*

### Output

Found 'env ALBA_LWT_ENGINE=libev' for
- ovs-albaproxy-*
- alba-albamaintenance-*

Did not find entry in:
- alba-asd-*

### Test result

Test failed.

## After reinstall

### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool on node 1
- Checked alba init files

Files that must contain this line:
- ovs-albaproxy-*
- alba-albamaintenance-*
- alba-asd-*

### Output

Found 'env ALBA_LWT_ENGINE=libev' for
- ovs-albaproxy-*
- alba-maintenance-*
- alba-asd-*

### Test result

Test passed.

A reinstall fixes the issue.

### Packages

```
- openvstorage                         2.7.4-rev.4254.b181bf9-1        amd64        openvStorage
- openvstorage-backend                 1.7.4-rev.801.33cbb60-1         amd64        openvStorage Backend plugin
- openvstorage-backend-core            1.7.4-rev.801.33cbb60-1         amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.4-rev.801.33cbb60-1         amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.4-rev.4254.b181bf9-1        amd64        openvStorage core
- openvstorage-hc                      1.7.4-rev.801.33cbb60-1         amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                     1.6.4-rev.414.20eee54-1         amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                 2.7.4-rev.4254.b181bf9-1        amd64        openvStorage Web Applications

```
