### ISSUE TITLE
Make it possible to add more than 1 DB disk

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#954]
If its possible to add more than 1 DB disk you will be able to spread your arakoons across those disks. When a DB disk would fail, only a part of the arakoons fail.

**Comment by wimpers** [comment]
Allow to define multiple DB roles per host. No sharding of a single Arakoon across multiple SSDs.
Multiple Arakoon DBs must be stored across the SSDs in a round robin fashion.

**Comment by wimpers** [comment]
The DB disk is also used for the metadata servers, do we want to roundrobin these also across the db disks?

**Comment by wimpers** [comment]
@saelbrec , I'm tend to close this one down as it is already possible to use more than 1 disk for the Arakoons by setting up external arakoons.

I also don't see a use case for spreading the vol metadata across 2 separate (non-raid 1 disks). 1GB of SSD space can address 1TB of data (8KB blocksize).

If you would disagree, feel free to re-open.
