### ISSUE TITLE
Finetune fragment cache settings of the ALBA proxies used for scrubbing

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#964]
Comment from @domsj on issue: https://github.com/openvstorage/framework/issues/727
Just a quick note here:
Currently the scrubber doesn't use partial reads, so this is fine.
If the scrubber were to ever start using partial reads this could be painful (in case of an hdd backend).
Most awesome fragment cache for the scrubber proxy would be, for a fragment cache (on the related storage drivers) of type
'alba': -> 'alba' with cache_on_read=${scrubber_uses_partial_reads} & cache_on_write=true(? - not sure about this one)
'local': if ${scrubber_uses_partial_reads} then 'local' with cache_on_read=true & cache_on_write=false else 'none'
'none': -> 'none'

**Comment by wimpers** [comment]
@domsj why would the scrubber start doing partial reads? Do you see this as an use case?

**Comment by domsj** [comment]
@redlicha considered it a possible use case
I think it comes down to this: if only a very small part of a SCO is still relevant after scrubbing then it is probably more efficient to partially read only the relevant parts (instead of the entire SCO).

**Comment by domsj** [comment]
Actually configuring the fragment cache for the scrub proxy as per my original comment could even make sense when the scrubber doesn't use partial reads.
In case of an accelerated geo scale alba it could avoid reads going to another datacenter.

**Comment by khenderick** [comment]
After some discussions, the scrubbers will now use on-write caching in an accelerated alba scenario.

Fixed by #1285, packaged in openvstorage-2.7.9-rev.4461.92dc644
