### ISSUE TITLE
Blacklist 'vrouter_id' from arakoon volume_router for changes

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#974]
# Problem description

I was reconfiguring the timeouts in the arakoon config using StorageDriverConfiguration(). I used a part of a running arakoon config and I only changed the timeout values. (Unaware that the vrouter_id had to be changed for every storagedriver).
This resulted in the volumedriver pointing to the wrong storagedriver after reloading.

In short: the vrouter_id can be rewriten in the arakoon framework via the framework.
This results in a incorrect pointer.
# Possible root of the problem

storagedriver_config.configure_volume_router(**volume_router) will take in all the variables supplied and won't exclude vrouter_id
# Possible solution

The vrouter_id should not be set in the configure_volume_router.
# Temporary solution

I fetched the storagedriver_id from the model and set them back.
The code failed #number_of_storagedriver times (in my case 6) before all arakoonconfigurations were set. (This is expected as framework will first complain about the mds_nodes due to the storagedrivers changing)

**Comment by wimpers** [comment]
As this is caused by  a picnic: wo'nt fix. BAM thinks blacklisting items isn't a good idea.
