### ISSUE TITLE
Domain with existing name can be added via API

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#999]
When performing a `set_domain` via the API, we can add domains that already exist with the same name.
This can cause problems in some cases when filtering by `name`.

**Comment by wimpers** [comment]
Does the GUI block the creation of duplicates?

**Comment by kvanhijf** [comment]
@wimpers : yes

**Comment by wimpers** [comment]
Best to cover when executing https://github.com/openvstorage/framework/issues/1218.  Do note that I don't see a problem with having 2 same leaves in that case (as long as the parent is different, f.e. rack1 can be in 2 branches of the tree)

**Comment by khenderick** [comment]
Fixed by #1356, packaged on dev in openvstorage-2.7.10-dev.1484735440.d43e582

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-2.7.10.1

**Comment by pploegaert** [comment]
Validation in:
https://github.com/openvstorage/integrationtests/issues/439
